// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/jrpc/eventti.proto

package jrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	eventti "github.com/sky-cloud-tec/proto/v1/eventti"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetNotificationChannelRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNotificationChannelRequest) Reset()         { *m = GetNotificationChannelRequest{} }
func (m *GetNotificationChannelRequest) String() string { return proto.CompactTextString(m) }
func (*GetNotificationChannelRequest) ProtoMessage()    {}
func (*GetNotificationChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6da2fa2c80cfc0d9, []int{0}
}

func (m *GetNotificationChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNotificationChannelRequest.Unmarshal(m, b)
}
func (m *GetNotificationChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNotificationChannelRequest.Marshal(b, m, deterministic)
}
func (m *GetNotificationChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNotificationChannelRequest.Merge(m, src)
}
func (m *GetNotificationChannelRequest) XXX_Size() int {
	return xxx_messageInfo_GetNotificationChannelRequest.Size(m)
}
func (m *GetNotificationChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNotificationChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNotificationChannelRequest proto.InternalMessageInfo

type GetNotificationChannelResponse struct {
	NotificationChannels []*eventti.NotificationChannel `protobuf:"bytes,10,rep,name=notification_channels,json=notificationChannels,proto3" json:"notification_channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GetNotificationChannelResponse) Reset()         { *m = GetNotificationChannelResponse{} }
func (m *GetNotificationChannelResponse) String() string { return proto.CompactTextString(m) }
func (*GetNotificationChannelResponse) ProtoMessage()    {}
func (*GetNotificationChannelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6da2fa2c80cfc0d9, []int{1}
}

func (m *GetNotificationChannelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNotificationChannelResponse.Unmarshal(m, b)
}
func (m *GetNotificationChannelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNotificationChannelResponse.Marshal(b, m, deterministic)
}
func (m *GetNotificationChannelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNotificationChannelResponse.Merge(m, src)
}
func (m *GetNotificationChannelResponse) XXX_Size() int {
	return xxx_messageInfo_GetNotificationChannelResponse.Size(m)
}
func (m *GetNotificationChannelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNotificationChannelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNotificationChannelResponse proto.InternalMessageInfo

func (m *GetNotificationChannelResponse) GetNotificationChannels() []*eventti.NotificationChannel {
	if m != nil {
		return m.NotificationChannels
	}
	return nil
}

type CreateNotificationChannelRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNotificationChannelRequest) Reset()         { *m = CreateNotificationChannelRequest{} }
func (m *CreateNotificationChannelRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNotificationChannelRequest) ProtoMessage()    {}
func (*CreateNotificationChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6da2fa2c80cfc0d9, []int{2}
}

func (m *CreateNotificationChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNotificationChannelRequest.Unmarshal(m, b)
}
func (m *CreateNotificationChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNotificationChannelRequest.Marshal(b, m, deterministic)
}
func (m *CreateNotificationChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNotificationChannelRequest.Merge(m, src)
}
func (m *CreateNotificationChannelRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNotificationChannelRequest.Size(m)
}
func (m *CreateNotificationChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNotificationChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNotificationChannelRequest proto.InternalMessageInfo

type CreateNotificationChannelResponse struct {
	Id                   int32    `protobuf:"varint,20,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNotificationChannelResponse) Reset()         { *m = CreateNotificationChannelResponse{} }
func (m *CreateNotificationChannelResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNotificationChannelResponse) ProtoMessage()    {}
func (*CreateNotificationChannelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6da2fa2c80cfc0d9, []int{3}
}

func (m *CreateNotificationChannelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNotificationChannelResponse.Unmarshal(m, b)
}
func (m *CreateNotificationChannelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNotificationChannelResponse.Marshal(b, m, deterministic)
}
func (m *CreateNotificationChannelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNotificationChannelResponse.Merge(m, src)
}
func (m *CreateNotificationChannelResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNotificationChannelResponse.Size(m)
}
func (m *CreateNotificationChannelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNotificationChannelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNotificationChannelResponse proto.InternalMessageInfo

func (m *CreateNotificationChannelResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*GetNotificationChannelRequest)(nil), "jrpc.GetNotificationChannelRequest")
	proto.RegisterType((*GetNotificationChannelResponse)(nil), "jrpc.GetNotificationChannelResponse")
	proto.RegisterType((*CreateNotificationChannelRequest)(nil), "jrpc.CreateNotificationChannelRequest")
	proto.RegisterType((*CreateNotificationChannelResponse)(nil), "jrpc.CreateNotificationChannelResponse")
}

func init() { proto.RegisterFile("src/jrpc/eventti.proto", fileDescriptor_6da2fa2c80cfc0d9) }

var fileDescriptor_6da2fa2c80cfc0d9 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x2e, 0x4a, 0xd6,
	0xcf, 0x2a, 0x2a, 0x48, 0xd6, 0x4f, 0x2d, 0x4b, 0xcd, 0x2b, 0x29, 0xc9, 0xd4, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x01, 0x89, 0x49, 0x49, 0x82, 0x64, 0xa1, 0x12, 0xa8, 0x0a, 0x94, 0xe4,
	0xb9, 0x64, 0xdd, 0x53, 0x4b, 0xfc, 0xf2, 0x4b, 0x32, 0xd3, 0x32, 0x93, 0x13, 0x4b, 0x32, 0xf3,
	0xf3, 0x9c, 0x33, 0x12, 0xf3, 0xf2, 0x52, 0x73, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x94,
	0x8a, 0xb9, 0xe4, 0x70, 0x29, 0x28, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x0a, 0xe4, 0x12, 0xcd,
	0x43, 0x92, 0x8e, 0x4f, 0x86, 0xc8, 0x17, 0x4b, 0x70, 0x29, 0x30, 0x6b, 0x70, 0x1b, 0xc9, 0xe8,
	0xc1, 0x6c, 0xc4, 0x66, 0x88, 0x48, 0x1e, 0xa6, 0x60, 0xb1, 0x92, 0x12, 0x97, 0x82, 0x73, 0x51,
	0x6a, 0x62, 0x49, 0x2a, 0x1e, 0x87, 0x19, 0x73, 0x29, 0xe2, 0x51, 0x03, 0x75, 0x1b, 0x1f, 0x17,
	0x53, 0x66, 0x8a, 0x84, 0x88, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x53, 0x66, 0x8a, 0x93, 0x23, 0x97,
	0x78, 0x5e, 0x6a, 0x89, 0x5e, 0x71, 0x76, 0x65, 0x72, 0x4e, 0x7e, 0x69, 0x0a, 0x24, 0x10, 0xf4,
	0x40, 0x81, 0x14, 0xa5, 0x96, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x5f,
	0x9c, 0x5d, 0xa9, 0x0b, 0x56, 0xa0, 0x5b, 0x92, 0x9a, 0xac, 0x0f, 0x56, 0xa4, 0x5f, 0x66, 0x08,
	0x0e, 0xe0, 0x24, 0x36, 0x30, 0xd7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x13, 0x61, 0xef, 0x73,
	0x73, 0x01, 0x00, 0x00,
}
