// Code generated by protoc-gen-go. DO NOT EDIT.
// source: irequest.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/sky-cloud-tec/proto/v1/common"
	eventti "github.com/sky-cloud-tec/proto/v1/eventti"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Page struct {
	Index int32 `protobuf:"varint,10,opt,name=index,proto3" json:"index,omitempty"`
	Num   int32 `protobuf:"varint,20,opt,name=num,proto3" json:"num,omitempty"`
	Size  int32 `protobuf:"varint,30,opt,name=size,proto3" json:"size,omitempty"`
	All   int32 `protobuf:"varint,50,opt,name=all,proto3" json:"all,omitempty"`
	Total int32 `protobuf:"varint,60,opt,name=total,proto3" json:"total,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*Page_NumValue
	Data                 isPage_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_21a794dd40f73a08, []int{0}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Page) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *Page) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Page) GetAll() int32 {
	if m != nil {
		return m.All
	}
	return 0
}

func (m *Page) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type isPage_Data interface {
	isPage_Data()
}

type Page_NumValue struct {
	NumValue int64 `protobuf:"varint,130,opt,name=numValue,proto3,oneof"`
}

func (*Page_NumValue) isPage_Data() {}

func (m *Page) GetData() isPage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Page) GetNumValue() int64 {
	if x, ok := m.GetData().(*Page_NumValue); ok {
		return x.NumValue
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Page) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Page_NumValue)(nil),
	}
}

type IResponse struct {
	Code common.Retcode `protobuf:"varint,10,opt,name=code,proto3,enum=common.Retcode" json:"code,omitempty"`
	Msg  string         `protobuf:"bytes,20,opt,name=msg,proto3" json:"msg,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*IResponse_NumValue
	//	*IResponse_StrValue
	//	*IResponse_BoolValue
	//	*IResponse_Page
	Data                 isIResponse_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *IResponse) Reset()         { *m = IResponse{} }
func (m *IResponse) String() string { return proto.CompactTextString(m) }
func (*IResponse) ProtoMessage()    {}
func (*IResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_21a794dd40f73a08, []int{1}
}

func (m *IResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IResponse.Unmarshal(m, b)
}
func (m *IResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IResponse.Marshal(b, m, deterministic)
}
func (m *IResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IResponse.Merge(m, src)
}
func (m *IResponse) XXX_Size() int {
	return xxx_messageInfo_IResponse.Size(m)
}
func (m *IResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IResponse proto.InternalMessageInfo

func (m *IResponse) GetCode() common.Retcode {
	if m != nil {
		return m.Code
	}
	return common.Retcode_UNKNOWN_RETCODE
}

func (m *IResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type isIResponse_Data interface {
	isIResponse_Data()
}

type IResponse_NumValue struct {
	NumValue int64 `protobuf:"varint,30,opt,name=numValue,proto3,oneof"`
}

type IResponse_StrValue struct {
	StrValue string `protobuf:"bytes,40,opt,name=strValue,proto3,oneof"`
}

type IResponse_BoolValue struct {
	BoolValue bool `protobuf:"varint,50,opt,name=boolValue,proto3,oneof"`
}

type IResponse_Page struct {
	Page *Page `protobuf:"bytes,150,opt,name=page,proto3,oneof"`
}

func (*IResponse_NumValue) isIResponse_Data() {}

func (*IResponse_StrValue) isIResponse_Data() {}

func (*IResponse_BoolValue) isIResponse_Data() {}

func (*IResponse_Page) isIResponse_Data() {}

func (m *IResponse) GetData() isIResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *IResponse) GetNumValue() int64 {
	if x, ok := m.GetData().(*IResponse_NumValue); ok {
		return x.NumValue
	}
	return 0
}

func (m *IResponse) GetStrValue() string {
	if x, ok := m.GetData().(*IResponse_StrValue); ok {
		return x.StrValue
	}
	return ""
}

func (m *IResponse) GetBoolValue() bool {
	if x, ok := m.GetData().(*IResponse_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (m *IResponse) GetPage() *Page {
	if x, ok := m.GetData().(*IResponse_Page); ok {
		return x.Page
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*IResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*IResponse_NumValue)(nil),
		(*IResponse_StrValue)(nil),
		(*IResponse_BoolValue)(nil),
		(*IResponse_Page)(nil),
	}
}

type IRequest struct {
	Url     string            `protobuf:"bytes,10,opt,name=url,proto3" json:"url,omitempty"`
	Headers map[string]string `protobuf:"bytes,20,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Types that are valid to be assigned to Body:
	//	*IRequest_CreateNotificationChannelReq
	Body                 isIRequest_Body `protobuf_oneof:"body"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *IRequest) Reset()         { *m = IRequest{} }
func (m *IRequest) String() string { return proto.CompactTextString(m) }
func (*IRequest) ProtoMessage()    {}
func (*IRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_21a794dd40f73a08, []int{2}
}

func (m *IRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IRequest.Unmarshal(m, b)
}
func (m *IRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IRequest.Marshal(b, m, deterministic)
}
func (m *IRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IRequest.Merge(m, src)
}
func (m *IRequest) XXX_Size() int {
	return xxx_messageInfo_IRequest.Size(m)
}
func (m *IRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IRequest proto.InternalMessageInfo

func (m *IRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *IRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

type isIRequest_Body interface {
	isIRequest_Body()
}

type IRequest_CreateNotificationChannelReq struct {
	CreateNotificationChannelReq *eventti.CreateNotificationChannelReq `protobuf:"bytes,30,opt,name=create_notification_channel_req,json=createNotificationChannelReq,proto3,oneof"`
}

func (*IRequest_CreateNotificationChannelReq) isIRequest_Body() {}

func (m *IRequest) GetBody() isIRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *IRequest) GetCreateNotificationChannelReq() *eventti.CreateNotificationChannelReq {
	if x, ok := m.GetBody().(*IRequest_CreateNotificationChannelReq); ok {
		return x.CreateNotificationChannelReq
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*IRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*IRequest_CreateNotificationChannelReq)(nil),
	}
}

func init() {
	proto.RegisterType((*Page)(nil), "proto.Page")
	proto.RegisterType((*IResponse)(nil), "proto.IResponse")
	proto.RegisterType((*IRequest)(nil), "proto.IRequest")
	proto.RegisterMapType((map[string]string)(nil), "proto.IRequest.HeadersEntry")
}

func init() {
	proto.RegisterFile("irequest.proto", fileDescriptor_21a794dd40f73a08)
}

var fileDescriptor_21a794dd40f73a08 = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x41, 0xaf, 0x12, 0x31,
	0x10, 0x66, 0x61, 0x79, 0x42, 0x31, 0x4f, 0x53, 0x31, 0x69, 0x08, 0x22, 0x62, 0x4c, 0xb8, 0xbc,
	0xdd, 0xb8, 0x26, 0x6a, 0x5e, 0x3c, 0xbd, 0x17, 0x93, 0x7d, 0x17, 0x63, 0x7a, 0xf0, 0xe0, 0x85,
	0x94, 0xdd, 0x11, 0x36, 0x74, 0x5b, 0xd8, 0x76, 0x89, 0xeb, 0xd1, 0x93, 0x57, 0x2f, 0xfe, 0x28,
	0x7f, 0x95, 0x99, 0x16, 0x90, 0x78, 0xf0, 0x34, 0x33, 0xdf, 0xf7, 0x75, 0x3a, 0xdf, 0x0c, 0xb9,
	0x2c, 0x2a, 0xd8, 0xd5, 0x60, 0x6c, 0xb4, 0xad, 0xb4, 0xd5, 0xb4, 0xeb, 0xc2, 0xe8, 0x51, 0xa6,
	0xcb, 0x52, 0xab, 0xd8, 0x07, 0xcf, 0x8d, 0x1e, 0xc3, 0x1e, 0x94, 0xb5, 0x45, 0x7c, 0x88, 0x1e,
	0x9e, 0xfd, 0x0c, 0x48, 0xf8, 0x51, 0xac, 0x80, 0x0e, 0x49, 0xb7, 0x50, 0x39, 0x7c, 0x65, 0x64,
	0x1a, 0xcc, 0xbb, 0xdc, 0x17, 0xf4, 0x21, 0xe9, 0xa8, 0xba, 0x64, 0x43, 0x87, 0x61, 0x4a, 0x29,
	0x09, 0x4d, 0xf1, 0x0d, 0xd8, 0xc4, 0x41, 0x2e, 0x47, 0x95, 0x90, 0x92, 0x25, 0x5e, 0x25, 0xa4,
	0xc4, 0x6e, 0x56, 0x5b, 0x21, 0xd9, 0x3b, 0xdf, 0xcd, 0x15, 0xf4, 0x09, 0xe9, 0xa9, 0xba, 0xfc,
	0x24, 0x64, 0x0d, 0xec, 0x7b, 0x30, 0x0d, 0xe6, 0x9d, 0xb4, 0xc5, 0x4f, 0xd0, 0xcd, 0x05, 0x09,
	0x73, 0x61, 0xc5, 0xec, 0x77, 0x40, 0xfa, 0x77, 0x1c, 0xcc, 0x56, 0x2b, 0x03, 0xf4, 0x39, 0x09,
	0x33, 0x9d, 0x83, 0x9b, 0xeb, 0x32, 0x79, 0x10, 0x1d, 0x5c, 0x71, 0xb0, 0x08, 0x73, 0x47, 0xe2,
	0x04, 0xa5, 0x59, 0xb9, 0x39, 0xfb, 0x1c, 0x53, 0x3a, 0x3e, 0xfb, 0x6b, 0xf2, 0xef, 0x57, 0xc8,
	0x1a, 0x5b, 0x79, 0x76, 0x8e, 0x8f, 0x90, 0x3d, 0x22, 0x74, 0x42, 0xfa, 0x4b, 0xad, 0xa5, 0xa7,
	0xd1, 0x55, 0x2f, 0x6d, 0xf1, 0xbf, 0x10, 0x9d, 0x91, 0x70, 0x2b, 0x56, 0xc0, 0x7e, 0xa1, 0x87,
	0x41, 0x32, 0xf0, 0xbb, 0x8c, 0x70, 0x8f, 0x69, 0x8b, 0x3b, 0xee, 0x64, 0xe6, 0x47, 0x9b, 0xf4,
	0xee, 0xb8, 0x3f, 0x13, 0x8e, 0x59, 0x57, 0xd2, 0x59, 0xe9, 0x73, 0x4c, 0xe9, 0x6b, 0x72, 0x6f,
	0x0d, 0x22, 0x87, 0xca, 0xb0, 0xe1, 0xb4, 0x33, 0x1f, 0x24, 0xe3, 0x43, 0xb3, 0xe3, 0x9b, 0x28,
	0xf5, 0xf4, 0x7b, 0x65, 0xab, 0x86, 0x1f, 0xc5, 0x54, 0x91, 0xa7, 0x59, 0x05, 0xc2, 0xc2, 0x42,
	0x69, 0x5b, 0x7c, 0x29, 0x32, 0x61, 0x0b, 0xad, 0x16, 0xd9, 0x5a, 0x28, 0x05, 0x72, 0x51, 0xc1,
	0xce, 0xb9, 0x1e, 0x24, 0x2f, 0xa2, 0xe3, 0xc1, 0x6f, 0x9d, 0xfe, 0xc3, 0x99, 0xfc, 0xd6, 0xab,
	0x39, 0xec, 0xd2, 0x16, 0x1f, 0x67, 0xff, 0xe1, 0x47, 0xd7, 0xe4, 0xfe, 0xf9, 0x20, 0xe8, 0x64,
	0x03, 0x0d, 0x0b, 0xbc, 0x93, 0x0d, 0x34, 0x78, 0xf2, 0xbd, 0x5b, 0x58, 0xdb, 0x61, 0xbe, 0xb8,
	0x6e, 0xbf, 0x0d, 0x70, 0x15, 0x4b, 0x9d, 0x37, 0x37, 0x6f, 0x08, 0x55, 0x60, 0x23, 0xb3, 0x69,
	0x32, 0xa9, 0xeb, 0xdc, 0x1b, 0xfd, 0xfc, 0x6c, 0x55, 0xd8, 0x75, 0xbd, 0xc4, 0xbb, 0xc6, 0x66,
	0xd3, 0x5c, 0x39, 0xee, 0xca, 0x42, 0x16, 0x3b, 0x3e, 0xde, 0xbf, 0x5c, 0x5e, 0xb8, 0xec, 0xd5,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x96, 0x71, 0x20, 0x54, 0xf0, 0x02, 0x00, 0x00,
}
