// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: src/grpc/inetMail.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailType int32

const (
	MailType_TEXT MailType = 0
	MailType_MIME MailType = 1
)

// Enum value maps for MailType.
var (
	MailType_name = map[int32]string{
		0: "TEXT",
		1: "MIME",
	}
	MailType_value = map[string]int32{
		"TEXT": 0,
		"MIME": 1,
	}
)

func (x MailType) Enum() *MailType {
	p := new(MailType)
	*p = x
	return p
}

func (x MailType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MailType) Descriptor() protoreflect.EnumDescriptor {
	return file_src_grpc_inetMail_proto_enumTypes[0].Descriptor()
}

func (MailType) Type() protoreflect.EnumType {
	return &file_src_grpc_inetMail_proto_enumTypes[0]
}

func (x MailType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MailType.Descriptor instead.
func (MailType) EnumDescriptor() ([]byte, []int) {
	return file_src_grpc_inetMail_proto_rawDescGZIP(), []int{0}
}

type IncomingMailStatus int32

const (
	IncomingMailStatus_DRAFT IncomingMailStatus = 0
	IncomingMailStatus_SEND  IncomingMailStatus = 1
)

// Enum value maps for IncomingMailStatus.
var (
	IncomingMailStatus_name = map[int32]string{
		0: "DRAFT",
		1: "SEND",
	}
	IncomingMailStatus_value = map[string]int32{
		"DRAFT": 0,
		"SEND":  1,
	}
)

func (x IncomingMailStatus) Enum() *IncomingMailStatus {
	p := new(IncomingMailStatus)
	*p = x
	return p
}

func (x IncomingMailStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IncomingMailStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_src_grpc_inetMail_proto_enumTypes[1].Descriptor()
}

func (IncomingMailStatus) Type() protoreflect.EnumType {
	return &file_src_grpc_inetMail_proto_enumTypes[1]
}

func (x IncomingMailStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IncomingMailStatus.Descriptor instead.
func (IncomingMailStatus) EnumDescriptor() ([]byte, []int) {
	return file_src_grpc_inetMail_proto_rawDescGZIP(), []int{1}
}

type AddMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cc      []string          `protobuf:"bytes,10,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc     []string          `protobuf:"bytes,20,rep,name=bcc,proto3" json:"bcc,omitempty"`
	To      []string          `protobuf:"bytes,30,rep,name=to,proto3" json:"to,omitempty"`
	Subject string            `protobuf:"bytes,40,opt,name=subject,proto3" json:"subject,omitempty"`
	Content string            `protobuf:"bytes,50,opt,name=content,proto3" json:"content,omitempty"`
	Type    MailType          `protobuf:"varint,60,opt,name=type,proto3,enum=rpc.MailType" json:"type,omitempty"`
	Files   map[string][]byte `protobuf:"bytes,70,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AddMailRequest) Reset() {
	*x = AddMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_grpc_inetMail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMailRequest) ProtoMessage() {}

func (x *AddMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_inetMail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMailRequest.ProtoReflect.Descriptor instead.
func (*AddMailRequest) Descriptor() ([]byte, []int) {
	return file_src_grpc_inetMail_proto_rawDescGZIP(), []int{0}
}

func (x *AddMailRequest) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *AddMailRequest) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *AddMailRequest) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *AddMailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AddMailRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddMailRequest) GetType() MailType {
	if x != nil {
		return x.Type
	}
	return MailType_TEXT
}

func (x *AddMailRequest) GetFiles() map[string][]byte {
	if x != nil {
		return x.Files
	}
	return nil
}

type AddMailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AddMailResponse) Reset() {
	*x = AddMailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_grpc_inetMail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMailResponse) ProtoMessage() {}

func (x *AddMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_inetMail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMailResponse.ProtoReflect.Descriptor instead.
func (*AddMailResponse) Descriptor() ([]byte, []int) {
	return file_src_grpc_inetMail_proto_rawDescGZIP(), []int{1}
}

func (x *AddMailResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_src_grpc_inetMail_proto protoreflect.FileDescriptor

var file_src_grpc_inetMail_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x72, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x6e, 0x65, 0x74, 0x4d,
	0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0x89,
	0x02, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x63, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x63,
	0x63, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x63, 0x63, 0x18, 0x14, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03,
	0x62, 0x63, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x1e, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x02, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x28,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x32, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x3c, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x61, 0x69, 0x6c,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x18, 0x46, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x41, 0x64, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x1a, 0x38, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x29, 0x0a, 0x0f, 0x41, 0x64,
	0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x1e, 0x0a, 0x08, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d,
	0x49, 0x4d, 0x45, 0x10, 0x01, 0x2a, 0x29, 0x0a, 0x12, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e,
	0x67, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x44,
	0x52, 0x41, 0x46, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x45, 0x4e, 0x44, 0x10, 0x01,
	0x32, 0x47, 0x0a, 0x0d, 0x50, 0x6f, 0x73, 0x74, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x36, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x13, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3f, 0x0a, 0x16, 0x6e, 0x65, 0x74,
	0x2e, 0x73, 0x6b, 0x79, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x72, 0x70, 0x63, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x6b, 0x79, 0x2d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x74, 0x65, 0x63, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_src_grpc_inetMail_proto_rawDescOnce sync.Once
	file_src_grpc_inetMail_proto_rawDescData = file_src_grpc_inetMail_proto_rawDesc
)

func file_src_grpc_inetMail_proto_rawDescGZIP() []byte {
	file_src_grpc_inetMail_proto_rawDescOnce.Do(func() {
		file_src_grpc_inetMail_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_grpc_inetMail_proto_rawDescData)
	})
	return file_src_grpc_inetMail_proto_rawDescData
}

var file_src_grpc_inetMail_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_src_grpc_inetMail_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_src_grpc_inetMail_proto_goTypes = []interface{}{
	(MailType)(0),           // 0: rpc.MailType
	(IncomingMailStatus)(0), // 1: rpc.IncomingMailStatus
	(*AddMailRequest)(nil),  // 2: rpc.AddMailRequest
	(*AddMailResponse)(nil), // 3: rpc.AddMailResponse
	nil,                     // 4: rpc.AddMailRequest.FilesEntry
}
var file_src_grpc_inetMail_proto_depIdxs = []int32{
	0, // 0: rpc.AddMailRequest.type:type_name -> rpc.MailType
	4, // 1: rpc.AddMailRequest.files:type_name -> rpc.AddMailRequest.FilesEntry
	2, // 2: rpc.PostalService.AddMail:input_type -> rpc.AddMailRequest
	3, // 3: rpc.PostalService.AddMail:output_type -> rpc.AddMailResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_grpc_inetMail_proto_init() }
func file_src_grpc_inetMail_proto_init() {
	if File_src_grpc_inetMail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_grpc_inetMail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_grpc_inetMail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_grpc_inetMail_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_grpc_inetMail_proto_goTypes,
		DependencyIndexes: file_src_grpc_inetMail_proto_depIdxs,
		EnumInfos:         file_src_grpc_inetMail_proto_enumTypes,
		MessageInfos:      file_src_grpc_inetMail_proto_msgTypes,
	}.Build()
	File_src_grpc_inetMail_proto = out.File
	file_src_grpc_inetMail_proto_rawDesc = nil
	file_src_grpc_inetMail_proto_goTypes = nil
	file_src_grpc_inetMail_proto_depIdxs = nil
}
