// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/trigger/trigger.proto

package trigger

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	anypb "google.golang.org/protobuf/types/known/anypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TriggerType int32

const (
	TriggerType_TIMER TriggerType = 0
	TriggerType_HTTP  TriggerType = 1
)

var TriggerType_name = map[int32]string{
	0: "TIMER",
	1: "HTTP",
}

var TriggerType_value = map[string]int32{
	"TIMER": 0,
	"HTTP":  1,
}

func (x TriggerType) String() string {
	return proto.EnumName(TriggerType_name, int32(x))
}

func (TriggerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_76dd8a955a08cebd, []int{0}
}

type ActionType int32

const (
	ActionType_RPC   ActionType = 0
	ActionType_EVENT ActionType = 1
)

var ActionType_name = map[int32]string{
	0: "RPC",
	1: "EVENT",
}

var ActionType_value = map[string]int32{
	"RPC":   0,
	"EVENT": 1,
}

func (x ActionType) String() string {
	return proto.EnumName(ActionType_name, int32(x))
}

func (ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_76dd8a955a08cebd, []int{1}
}

type TimerType int32

const (
	TimerType_CRON     TimerType = 0
	TimerType_REPEATED TimerType = 1
	TimerType_ONCE     TimerType = 2
)

var TimerType_name = map[int32]string{
	0: "CRON",
	1: "REPEATED",
	2: "ONCE",
}

var TimerType_value = map[string]int32{
	"CRON":     0,
	"REPEATED": 1,
	"ONCE":     2,
}

func (x TimerType) String() string {
	return proto.EnumName(TimerType_name, int32(x))
}

func (TimerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_76dd8a955a08cebd, []int{2}
}

type UNIT int32

const (
	UNIT_SECOND UNIT = 0
	UNIT_MINUTE UNIT = 1
	UNIT_HOUR   UNIT = 2
	UNIT_DAY    UNIT = 3
)

var UNIT_name = map[int32]string{
	0: "SECOND",
	1: "MINUTE",
	2: "HOUR",
	3: "DAY",
}

var UNIT_value = map[string]int32{
	"SECOND": 0,
	"MINUTE": 1,
	"HOUR":   2,
	"DAY":    3,
}

func (x UNIT) String() string {
	return proto.EnumName(UNIT_name, int32(x))
}

func (UNIT) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_76dd8a955a08cebd, []int{3}
}

type TypeValue struct {
	Type TimerType `protobuf:"varint,10,opt,name=type,proto3,enum=trigger.TimerType" json:"type,omitempty"`
	// 当type 为 CRON/ONCE 填充下面这个值
	ParamValue string `protobuf:"bytes,20,opt,name=paramValue,proto3" json:"paramValue,omitempty"`
	// 当type 为 REPEATED 填充下面两个值
	Unit                 UNIT     `protobuf:"varint,30,opt,name=unit,proto3,enum=trigger.UNIT" json:"unit,omitempty"`
	Value                int32    `protobuf:"varint,40,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeValue) Reset()         { *m = TypeValue{} }
func (m *TypeValue) String() string { return proto.CompactTextString(m) }
func (*TypeValue) ProtoMessage()    {}
func (*TypeValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_76dd8a955a08cebd, []int{0}
}

func (m *TypeValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeValue.Unmarshal(m, b)
}
func (m *TypeValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeValue.Marshal(b, m, deterministic)
}
func (m *TypeValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeValue.Merge(m, src)
}
func (m *TypeValue) XXX_Size() int {
	return xxx_messageInfo_TypeValue.Size(m)
}
func (m *TypeValue) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeValue.DiscardUnknown(m)
}

var xxx_messageInfo_TypeValue proto.InternalMessageInfo

func (m *TypeValue) GetType() TimerType {
	if m != nil {
		return m.Type
	}
	return TimerType_CRON
}

func (m *TypeValue) GetParamValue() string {
	if m != nil {
		return m.ParamValue
	}
	return ""
}

func (m *TypeValue) GetUnit() UNIT {
	if m != nil {
		return m.Unit
	}
	return UNIT_SECOND
}

func (m *TypeValue) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type TypeValueOfTimer struct {
	Type                 TimerType `protobuf:"varint,10,opt,name=type,proto3,enum=trigger.TimerType" json:"type,omitempty"`
	ParamValue           string    `protobuf:"bytes,20,opt,name=paramValue,proto3" json:"paramValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TypeValueOfTimer) Reset()         { *m = TypeValueOfTimer{} }
func (m *TypeValueOfTimer) String() string { return proto.CompactTextString(m) }
func (*TypeValueOfTimer) ProtoMessage()    {}
func (*TypeValueOfTimer) Descriptor() ([]byte, []int) {
	return fileDescriptor_76dd8a955a08cebd, []int{1}
}

func (m *TypeValueOfTimer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeValueOfTimer.Unmarshal(m, b)
}
func (m *TypeValueOfTimer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeValueOfTimer.Marshal(b, m, deterministic)
}
func (m *TypeValueOfTimer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeValueOfTimer.Merge(m, src)
}
func (m *TypeValueOfTimer) XXX_Size() int {
	return xxx_messageInfo_TypeValueOfTimer.Size(m)
}
func (m *TypeValueOfTimer) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeValueOfTimer.DiscardUnknown(m)
}

var xxx_messageInfo_TypeValueOfTimer proto.InternalMessageInfo

func (m *TypeValueOfTimer) GetType() TimerType {
	if m != nil {
		return m.Type
	}
	return TimerType_CRON
}

func (m *TypeValueOfTimer) GetParamValue() string {
	if m != nil {
		return m.ParamValue
	}
	return ""
}

type PaasResource struct {
	ResourceType         string   `protobuf:"bytes,10,opt,name=resourceType,proto3" json:"resourceType,omitempty"`
	ResourceId           string   `protobuf:"bytes,20,opt,name=resourceId,proto3" json:"resourceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaasResource) Reset()         { *m = PaasResource{} }
func (m *PaasResource) String() string { return proto.CompactTextString(m) }
func (*PaasResource) ProtoMessage()    {}
func (*PaasResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_76dd8a955a08cebd, []int{2}
}

func (m *PaasResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaasResource.Unmarshal(m, b)
}
func (m *PaasResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaasResource.Marshal(b, m, deterministic)
}
func (m *PaasResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaasResource.Merge(m, src)
}
func (m *PaasResource) XXX_Size() int {
	return xxx_messageInfo_PaasResource.Size(m)
}
func (m *PaasResource) XXX_DiscardUnknown() {
	xxx_messageInfo_PaasResource.DiscardUnknown(m)
}

var xxx_messageInfo_PaasResource proto.InternalMessageInfo

func (m *PaasResource) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *PaasResource) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

type MapFieldEntry struct {
	Key                  string   `protobuf:"bytes,10,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,20,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapFieldEntry) Reset()         { *m = MapFieldEntry{} }
func (m *MapFieldEntry) String() string { return proto.CompactTextString(m) }
func (*MapFieldEntry) ProtoMessage()    {}
func (*MapFieldEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_76dd8a955a08cebd, []int{3}
}

func (m *MapFieldEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapFieldEntry.Unmarshal(m, b)
}
func (m *MapFieldEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapFieldEntry.Marshal(b, m, deterministic)
}
func (m *MapFieldEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapFieldEntry.Merge(m, src)
}
func (m *MapFieldEntry) XXX_Size() int {
	return xxx_messageInfo_MapFieldEntry.Size(m)
}
func (m *MapFieldEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_MapFieldEntry.DiscardUnknown(m)
}

var xxx_messageInfo_MapFieldEntry proto.InternalMessageInfo

func (m *MapFieldEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MapFieldEntry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ActionParams struct {
	Service              string           `protobuf:"bytes,10,opt,name=service,proto3" json:"service,omitempty"`
	Params               []*MapFieldEntry `protobuf:"bytes,20,rep,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ActionParams) Reset()         { *m = ActionParams{} }
func (m *ActionParams) String() string { return proto.CompactTextString(m) }
func (*ActionParams) ProtoMessage()    {}
func (*ActionParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_76dd8a955a08cebd, []int{4}
}

func (m *ActionParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionParams.Unmarshal(m, b)
}
func (m *ActionParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionParams.Marshal(b, m, deterministic)
}
func (m *ActionParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionParams.Merge(m, src)
}
func (m *ActionParams) XXX_Size() int {
	return xxx_messageInfo_ActionParams.Size(m)
}
func (m *ActionParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionParams.DiscardUnknown(m)
}

var xxx_messageInfo_ActionParams proto.InternalMessageInfo

func (m *ActionParams) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ActionParams) GetParams() []*MapFieldEntry {
	if m != nil {
		return m.Params
	}
	return nil
}

type ActionParamsOfRpc struct {
	Service              string                `protobuf:"bytes,10,opt,name=service,proto3" json:"service,omitempty"`
	Param                map[string]*anypb.Any `protobuf:"bytes,20,rep,name=param,proto3" json:"param,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ActionParamsOfRpc) Reset()         { *m = ActionParamsOfRpc{} }
func (m *ActionParamsOfRpc) String() string { return proto.CompactTextString(m) }
func (*ActionParamsOfRpc) ProtoMessage()    {}
func (*ActionParamsOfRpc) Descriptor() ([]byte, []int) {
	return fileDescriptor_76dd8a955a08cebd, []int{5}
}

func (m *ActionParamsOfRpc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionParamsOfRpc.Unmarshal(m, b)
}
func (m *ActionParamsOfRpc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionParamsOfRpc.Marshal(b, m, deterministic)
}
func (m *ActionParamsOfRpc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionParamsOfRpc.Merge(m, src)
}
func (m *ActionParamsOfRpc) XXX_Size() int {
	return xxx_messageInfo_ActionParamsOfRpc.Size(m)
}
func (m *ActionParamsOfRpc) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionParamsOfRpc.DiscardUnknown(m)
}

var xxx_messageInfo_ActionParamsOfRpc proto.InternalMessageInfo

func (m *ActionParamsOfRpc) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ActionParamsOfRpc) GetParam() map[string]*anypb.Any {
	if m != nil {
		return m.Param
	}
	return nil
}

type Trigger struct {
	Id                   int64           `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	TriggerName          string          `protobuf:"bytes,20,opt,name=triggerName,proto3" json:"triggerName,omitempty"`
	Disabled             bool            `protobuf:"varint,30,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Description          string          `protobuf:"bytes,40,opt,name=description,proto3" json:"description,omitempty"`
	Bindings             []*PaasResource `protobuf:"bytes,50,rep,name=bindings,proto3" json:"bindings,omitempty"`
	CreatedTime          string          `protobuf:"bytes,60,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime          string          `protobuf:"bytes,70,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	TriggerType          TriggerType     `protobuf:"varint,80,opt,name=triggerType,proto3,enum=trigger.TriggerType" json:"triggerType,omitempty"`
	TypeValue            *TypeValue      `protobuf:"bytes,90,opt,name=typeValue,proto3" json:"typeValue,omitempty"`
	ActionType           ActionType      `protobuf:"varint,100,opt,name=actionType,proto3,enum=trigger.ActionType" json:"actionType,omitempty"`
	ActionParams         *ActionParams   `protobuf:"bytes,110,opt,name=actionParams,proto3" json:"actionParams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Trigger) Reset()         { *m = Trigger{} }
func (m *Trigger) String() string { return proto.CompactTextString(m) }
func (*Trigger) ProtoMessage()    {}
func (*Trigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_76dd8a955a08cebd, []int{6}
}

func (m *Trigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trigger.Unmarshal(m, b)
}
func (m *Trigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trigger.Marshal(b, m, deterministic)
}
func (m *Trigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trigger.Merge(m, src)
}
func (m *Trigger) XXX_Size() int {
	return xxx_messageInfo_Trigger.Size(m)
}
func (m *Trigger) XXX_DiscardUnknown() {
	xxx_messageInfo_Trigger.DiscardUnknown(m)
}

var xxx_messageInfo_Trigger proto.InternalMessageInfo

func (m *Trigger) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Trigger) GetTriggerName() string {
	if m != nil {
		return m.TriggerName
	}
	return ""
}

func (m *Trigger) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *Trigger) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Trigger) GetBindings() []*PaasResource {
	if m != nil {
		return m.Bindings
	}
	return nil
}

func (m *Trigger) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

func (m *Trigger) GetUpdatedTime() string {
	if m != nil {
		return m.UpdatedTime
	}
	return ""
}

func (m *Trigger) GetTriggerType() TriggerType {
	if m != nil {
		return m.TriggerType
	}
	return TriggerType_TIMER
}

func (m *Trigger) GetTypeValue() *TypeValue {
	if m != nil {
		return m.TypeValue
	}
	return nil
}

func (m *Trigger) GetActionType() ActionType {
	if m != nil {
		return m.ActionType
	}
	return ActionType_RPC
}

func (m *Trigger) GetActionParams() *ActionParams {
	if m != nil {
		return m.ActionParams
	}
	return nil
}

func init() {
	proto.RegisterEnum("trigger.TriggerType", TriggerType_name, TriggerType_value)
	proto.RegisterEnum("trigger.ActionType", ActionType_name, ActionType_value)
	proto.RegisterEnum("trigger.TimerType", TimerType_name, TimerType_value)
	proto.RegisterEnum("trigger.UNIT", UNIT_name, UNIT_value)
	proto.RegisterType((*TypeValue)(nil), "trigger.TypeValue")
	proto.RegisterType((*TypeValueOfTimer)(nil), "trigger.TypeValueOfTimer")
	proto.RegisterType((*PaasResource)(nil), "trigger.PaasResource")
	proto.RegisterType((*MapFieldEntry)(nil), "trigger.MapFieldEntry")
	proto.RegisterType((*ActionParams)(nil), "trigger.ActionParams")
	proto.RegisterType((*ActionParamsOfRpc)(nil), "trigger.ActionParamsOfRpc")
	proto.RegisterMapType((map[string]*anypb.Any)(nil), "trigger.ActionParamsOfRpc.ParamEntry")
	proto.RegisterType((*Trigger)(nil), "trigger.Trigger")
}

func init() { proto.RegisterFile("src/trigger/trigger.proto", fileDescriptor_76dd8a955a08cebd) }

var fileDescriptor_76dd8a955a08cebd = []byte{
	// 694 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcb, 0x6e, 0x9b, 0x40,
	0x14, 0x35, 0x7e, 0xc4, 0xe6, 0xda, 0x89, 0xe8, 0xd4, 0xa9, 0x88, 0x17, 0x11, 0x45, 0x6a, 0xe5,
	0x5a, 0x0a, 0x6e, 0x1c, 0xa9, 0xef, 0x8d, 0xeb, 0x90, 0xc6, 0x8b, 0x60, 0x6b, 0x4a, 0xa2, 0x36,
	0x3b, 0x0c, 0x13, 0x17, 0xc5, 0x06, 0xc4, 0x23, 0x12, 0xff, 0xd0, 0x2f, 0xea, 0x27, 0xf4, 0xab,
	0xaa, 0x19, 0x18, 0xc0, 0x6d, 0xd5, 0x55, 0x57, 0xcc, 0x9c, 0x39, 0xf7, 0xdc, 0x07, 0x67, 0x06,
	0x8e, 0xa2, 0xd0, 0x1e, 0xc7, 0xa1, 0xbb, 0x5e, 0x93, 0x90, 0x7f, 0xb5, 0x20, 0xf4, 0x63, 0x1f,
	0xb5, 0xf3, 0xed, 0xe0, 0x68, 0xed, 0xfb, 0xeb, 0x0d, 0x19, 0x33, 0x78, 0x95, 0xdc, 0x8d, 0x2d,
	0x2f, 0xcd, 0x38, 0xea, 0x77, 0x01, 0x44, 0x33, 0x0d, 0xc8, 0x8d, 0xb5, 0x49, 0x08, 0x7a, 0x0e,
	0xcd, 0x38, 0x0d, 0x88, 0x0c, 0x8a, 0x30, 0x3c, 0x98, 0x20, 0x8d, 0xeb, 0x99, 0xee, 0x96, 0x84,
	0x94, 0x86, 0xd9, 0x39, 0x3a, 0x06, 0x08, 0xac, 0xd0, 0xda, 0xb2, 0x28, 0xb9, 0xaf, 0x08, 0x43,
	0x11, 0x57, 0x10, 0xf4, 0x14, 0x9a, 0x89, 0xe7, 0xc6, 0xf2, 0x31, 0xd3, 0xd9, 0x2f, 0x74, 0xae,
	0x8d, 0xb9, 0x89, 0xd9, 0x11, 0xea, 0x43, 0xeb, 0x81, 0x45, 0x0f, 0x15, 0x61, 0xd8, 0xc2, 0xd9,
	0x46, 0xbd, 0x05, 0xa9, 0xa8, 0x66, 0x71, 0xc7, 0xd2, 0xfe, 0xaf, 0xa2, 0x54, 0x0c, 0xbd, 0xa5,
	0x65, 0x45, 0x98, 0x44, 0x7e, 0x12, 0xda, 0x04, 0xa9, 0xd0, 0x0b, 0xf3, 0xb5, 0xc9, 0xf5, 0x45,
	0xbc, 0x83, 0x51, 0x4d, 0xbe, 0x9f, 0x3b, 0x5c, 0xb3, 0x44, 0xd4, 0xd7, 0xb0, 0x7f, 0x65, 0x05,
	0x17, 0x2e, 0xd9, 0x38, 0xba, 0x17, 0x87, 0x29, 0x92, 0xa0, 0x71, 0x4f, 0xd2, 0x5c, 0x8b, 0x2e,
	0xcb, 0x46, 0xb3, 0xe8, 0xbc, 0xd1, 0x2f, 0xd0, 0x9b, 0xda, 0xb1, 0xeb, 0x7b, 0x4b, 0x5a, 0x60,
	0x84, 0x64, 0x68, 0x47, 0x24, 0x7c, 0x70, 0x6d, 0x5e, 0x07, 0xdf, 0x22, 0x0d, 0xf6, 0x58, 0x13,
	0x91, 0xdc, 0x57, 0x1a, 0xc3, 0xee, 0xe4, 0x49, 0x31, 0x80, 0x9d, 0xcc, 0x38, 0x67, 0xa9, 0x3f,
	0x04, 0x78, 0x54, 0x95, 0x5e, 0xdc, 0xe1, 0xc0, 0xfe, 0x87, 0xfe, 0x7b, 0x68, 0xb1, 0xc8, 0x5c,
	0xfe, 0x59, 0x21, 0xff, 0x87, 0x88, 0xc6, 0xd6, 0x59, 0xb6, 0x2c, 0x66, 0x60, 0x00, 0x94, 0x20,
	0x6f, 0x5e, 0x28, 0x9b, 0x1f, 0xf1, 0xe6, 0xeb, 0x8a, 0x30, 0xec, 0x4e, 0xfa, 0x5a, 0xe6, 0x44,
	0x8d, 0x3b, 0x51, 0x9b, 0x7a, 0x69, 0x3e, 0x92, 0x77, 0xf5, 0x37, 0x82, 0xfa, 0xb3, 0x01, 0x6d,
	0x33, 0xcb, 0x8f, 0x0e, 0xa0, 0xee, 0x3a, 0xac, 0xda, 0x06, 0xae, 0xbb, 0x0e, 0x52, 0xa0, 0x9b,
	0x97, 0x66, 0x58, 0x5b, 0x3e, 0xce, 0x2a, 0x84, 0x06, 0xd0, 0x71, 0xdc, 0xc8, 0x5a, 0x6d, 0x88,
	0xc3, 0xac, 0xd7, 0xc1, 0xc5, 0x9e, 0x46, 0x3b, 0x24, 0xb2, 0x43, 0x37, 0xa0, 0x5d, 0x31, 0xd7,
	0x89, 0xb8, 0x0a, 0xa1, 0x53, 0xe8, 0xac, 0x5c, 0xcf, 0x71, 0xbd, 0x75, 0x24, 0x4f, 0xd8, 0x2c,
	0x0e, 0x8b, 0x59, 0x54, 0x8d, 0x83, 0x0b, 0x1a, 0x15, 0xb5, 0x43, 0x62, 0xc5, 0xc4, 0xa1, 0x66,
	0x94, 0x3f, 0x64, 0xa2, 0x15, 0x88, 0x32, 0x92, 0xc0, 0x29, 0x18, 0x17, 0x19, 0xa3, 0x02, 0xa1,
	0x57, 0x45, 0x5b, 0xcc, 0x85, 0x4b, 0xe6, 0xf2, 0x7e, 0xe9, 0xf2, 0xf2, 0x0c, 0x57, 0x89, 0xe8,
	0x25, 0x88, 0x31, 0xbf, 0x2a, 0xf2, 0x2d, 0x1b, 0x6f, 0xe5, 0x6e, 0xf0, 0x13, 0x5c, 0x92, 0xd0,
	0x19, 0x80, 0xc5, 0xfe, 0x29, 0x4b, 0xe4, 0xb0, 0x44, 0x8f, 0x7f, 0xfb, 0xdd, 0x2c, 0x4f, 0x85,
	0x86, 0xde, 0x42, 0xcf, 0xaa, 0x18, 0x41, 0xf6, 0x58, 0xa6, 0xc3, 0xbf, 0xba, 0x04, 0xef, 0x50,
	0x47, 0x2a, 0x74, 0x2b, 0xd5, 0x23, 0x11, 0x5a, 0xe6, 0xfc, 0x4a, 0xc7, 0x52, 0x0d, 0x75, 0xa0,
	0x79, 0x69, 0x9a, 0x4b, 0x49, 0x18, 0x29, 0x00, 0x65, 0x62, 0xd4, 0x86, 0x06, 0x5e, 0xce, 0xa4,
	0x1a, 0xe5, 0xea, 0x37, 0xba, 0x61, 0x4a, 0xc2, 0xe8, 0x04, 0xc4, 0xe2, 0xa6, 0xd3, 0xc0, 0x19,
	0x5e, 0x18, 0x52, 0x0d, 0xf5, 0xa0, 0x83, 0xf5, 0xa5, 0x3e, 0x35, 0xf5, 0x73, 0x49, 0xa0, 0xf8,
	0xc2, 0x98, 0xe9, 0x52, 0x7d, 0x74, 0x0a, 0x4d, 0xfa, 0xca, 0x20, 0x80, 0xbd, 0xcf, 0xfa, 0x6c,
	0x61, 0x9c, 0x4b, 0x35, 0xba, 0xbe, 0x9a, 0x1b, 0xd7, 0xa6, 0x9e, 0x31, 0x2f, 0x17, 0xd7, 0x58,
	0xaa, 0xd3, 0x64, 0xe7, 0xd3, 0xaf, 0x52, 0xe3, 0xe3, 0x27, 0x18, 0x78, 0x24, 0xd6, 0xa2, 0xfb,
	0xd4, 0xde, 0xf8, 0x89, 0x93, 0x99, 0x93, 0x37, 0x78, 0xfb, 0x62, 0xed, 0xc6, 0xdf, 0x92, 0x95,
	0x66, 0xfb, 0xdb, 0x71, 0x74, 0x9f, 0x9e, 0x30, 0xce, 0x49, 0x4c, 0xec, 0xec, 0x39, 0x1d, 0x3f,
	0x9c, 0xf2, 0x67, 0x77, 0xb5, 0xc7, 0x90, 0xb3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x42,
	0x36, 0xe5, 0x94, 0x05, 0x00, 0x00,
}
