// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Retcode int32

const (
	Retcode_UNKNOWN_RETCODE Retcode = 0
	Retcode_OK              Retcode = 200
	Retcode_BadRequest      Retcode = 400
)

var Retcode_name = map[int32]string{
	0:   "UNKNOWN_RETCODE",
	200: "OK",
	400: "BadRequest",
}

var Retcode_value = map[string]int32{
	"UNKNOWN_RETCODE": 0,
	"OK":              200,
	"BadRequest":      400,
}

func (x Retcode) String() string {
	return proto.EnumName(Retcode_name, int32(x))
}

func (Retcode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

type BaseRet struct {
	Retcode              Retcode  `protobuf:"varint,10,opt,name=retcode,proto3,enum=common.Retcode" json:"retcode,omitempty"`
	Message              string   `protobuf:"bytes,20,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseRet) Reset()         { *m = BaseRet{} }
func (m *BaseRet) String() string { return proto.CompactTextString(m) }
func (*BaseRet) ProtoMessage()    {}
func (*BaseRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

func (m *BaseRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseRet.Unmarshal(m, b)
}
func (m *BaseRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseRet.Marshal(b, m, deterministic)
}
func (m *BaseRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseRet.Merge(m, src)
}
func (m *BaseRet) XXX_Size() int {
	return xxx_messageInfo_BaseRet.Size(m)
}
func (m *BaseRet) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseRet.DiscardUnknown(m)
}

var xxx_messageInfo_BaseRet proto.InternalMessageInfo

func (m *BaseRet) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_UNKNOWN_RETCODE
}

func (m *BaseRet) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Page struct {
	Index                int32      `protobuf:"varint,10,opt,name=index,proto3" json:"index,omitempty"`
	Num                  int32      `protobuf:"varint,20,opt,name=num,proto3" json:"num,omitempty"`
	Size                 int32      `protobuf:"varint,30,opt,name=size,proto3" json:"size,omitempty"`
	All                  int32      `protobuf:"varint,50,opt,name=all,proto3" json:"all,omitempty"`
	Total                int32      `protobuf:"varint,60,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*any.Any `protobuf:"bytes,70,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{1}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Page) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *Page) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Page) GetAll() int32 {
	if m != nil {
		return m.All
	}
	return 0
}

func (m *Page) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Page) GetData() []*any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("common.Retcode", Retcode_name, Retcode_value)
	proto.RegisterType((*BaseRet)(nil), "common.BaseRet")
	proto.RegisterType((*Page)(nil), "common.Page")
}

func init() {
	proto.RegisterFile("common/common.proto", fileDescriptor_8f954d82c0b891f6)
}

var fileDescriptor_8f954d82c0b891f6 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x50, 0xcd, 0x4a, 0xc3, 0x40,
	0x18, 0x34, 0xf6, 0x27, 0xf8, 0x09, 0x36, 0x6c, 0x7b, 0x58, 0x3d, 0x48, 0xe9, 0x29, 0x0a, 0x4d,
	0x30, 0x5e, 0x3c, 0x78, 0xb1, 0x5a, 0x2f, 0x85, 0x54, 0x16, 0x45, 0xf0, 0x22, 0xdb, 0xe4, 0x33,
	0x06, 0x37, 0x59, 0xed, 0x6e, 0xc4, 0xf8, 0x14, 0x1e, 0x7c, 0x28, 0x1f, 0x4b, 0xb2, 0x9b, 0x9c,
	0x76, 0x66, 0x76, 0xbe, 0x81, 0x19, 0x18, 0x27, 0xb2, 0x28, 0x64, 0x19, 0xda, 0x27, 0x78, 0xdf,
	0x4a, 0x2d, 0xc9, 0xd0, 0xb2, 0xa3, 0xc3, 0x4c, 0xca, 0x4c, 0x60, 0x68, 0xd4, 0x4d, 0xf5, 0x12,
	0xf2, 0xb2, 0xb6, 0x96, 0x59, 0x0c, 0xee, 0x82, 0x2b, 0x64, 0xa8, 0xc9, 0x09, 0xb8, 0x5b, 0xd4,
	0x89, 0x4c, 0x91, 0xc2, 0xd4, 0xf1, 0x0f, 0xa2, 0x51, 0xd0, 0xa6, 0x31, 0x2b, 0xb3, 0xee, 0x9f,
	0x50, 0x70, 0x0b, 0x54, 0x8a, 0x67, 0x48, 0x27, 0x53, 0xc7, 0xdf, 0x63, 0x1d, 0x9d, 0xfd, 0x3a,
	0xd0, 0xbf, 0xe3, 0x19, 0x92, 0x09, 0x0c, 0xf2, 0x32, 0xc5, 0x2f, 0x93, 0x35, 0x60, 0x96, 0x10,
	0x0f, 0x7a, 0x65, 0x55, 0x98, 0xa3, 0x01, 0x6b, 0x20, 0x21, 0xd0, 0x57, 0xf9, 0x37, 0xd2, 0x63,
	0x23, 0x19, 0xdc, 0xb8, 0xb8, 0x10, 0x34, 0xb2, 0x2e, 0x2e, 0x44, 0x93, 0xa6, 0xa5, 0xe6, 0x82,
	0x5e, 0xda, 0x34, 0x43, 0x88, 0x0f, 0xfd, 0x94, 0x6b, 0x4e, 0x6f, 0xa7, 0x3d, 0x7f, 0x3f, 0x9a,
	0x04, 0xb6, 0x66, 0xd0, 0xd5, 0x0c, 0xae, 0xca, 0x9a, 0x19, 0xc7, 0xe9, 0x05, 0xb8, 0x6d, 0x09,
	0x32, 0x86, 0xd1, 0x43, 0xbc, 0x8a, 0xd7, 0x8f, 0xf1, 0x33, 0x5b, 0xde, 0x5f, 0xaf, 0x6f, 0x96,
	0xde, 0x0e, 0x71, 0x61, 0x77, 0xbd, 0xf2, 0xfe, 0x1c, 0x32, 0x02, 0x58, 0xf0, 0x94, 0xe1, 0x47,
	0x85, 0x4a, 0x7b, 0x3f, 0xbd, 0x45, 0x04, 0xed, 0x8a, 0x4f, 0x7e, 0x96, 0xeb, 0xd7, 0x6a, 0xd3,
	0x8c, 0x12, 0xaa, 0xb7, 0x7a, 0x9e, 0x08, 0x59, 0xa5, 0x73, 0x8d, 0x89, 0xdd, 0x35, 0xfc, 0x3c,
	0x6b, 0xd7, 0xdf, 0x0c, 0x8d, 0x70, 0xfe, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xd2, 0xa9, 0x19,
	0x95, 0x01, 0x00, 0x00,
}
