// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/common.proto

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	common/common.proto

It has these top-level messages:
	BaseRet
	Page
	IResponse
	IRequest
*/
package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Retcode int32

const (
	Retcode_UNKNOWN_RETCODE Retcode = 0
	Retcode_OK              Retcode = 200
	Retcode_BadRequest      Retcode = 400
)

var Retcode_name = map[int32]string{
	0:   "UNKNOWN_RETCODE",
	200: "OK",
	400: "BadRequest",
}
var Retcode_value = map[string]int32{
	"UNKNOWN_RETCODE": 0,
	"OK":              200,
	"BadRequest":      400,
}

func (x Retcode) String() string {
	return proto.EnumName(Retcode_name, int32(x))
}
func (Retcode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BaseRet struct {
	Retcode Retcode `protobuf:"varint,10,opt,name=retcode,enum=common.Retcode" json:"retcode,omitempty"`
	Message string  `protobuf:"bytes,20,opt,name=message" json:"message,omitempty"`
}

func (m *BaseRet) Reset()                    { *m = BaseRet{} }
func (m *BaseRet) String() string            { return proto.CompactTextString(m) }
func (*BaseRet) ProtoMessage()               {}
func (*BaseRet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BaseRet) GetRetcode() Retcode {
	if m != nil {
		return m.Retcode
	}
	return Retcode_UNKNOWN_RETCODE
}

func (m *BaseRet) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Page struct {
	Index int32                  `protobuf:"varint,10,opt,name=index" json:"index,omitempty"`
	Num   int32                  `protobuf:"varint,20,opt,name=num" json:"num,omitempty"`
	Size  int32                  `protobuf:"varint,30,opt,name=size" json:"size,omitempty"`
	All   int32                  `protobuf:"varint,50,opt,name=all" json:"all,omitempty"`
	Total int32                  `protobuf:"varint,60,opt,name=total" json:"total,omitempty"`
	Data  []*google_protobuf.Any `protobuf:"bytes,70,rep,name=data" json:"data,omitempty"`
}

func (m *Page) Reset()                    { *m = Page{} }
func (m *Page) String() string            { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()               {}
func (*Page) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Page) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Page) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *Page) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Page) GetAll() int32 {
	if m != nil {
		return m.All
	}
	return 0
}

func (m *Page) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Page) GetData() []*google_protobuf.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type IResponse struct {
	Code Retcode              `protobuf:"varint,10,opt,name=code,enum=common.Retcode" json:"code,omitempty"`
	Msg  string               `protobuf:"bytes,20,opt,name=msg" json:"msg,omitempty"`
	Data *google_protobuf.Any `protobuf:"bytes,30,opt,name=data" json:"data,omitempty"`
}

func (m *IResponse) Reset()                    { *m = IResponse{} }
func (m *IResponse) String() string            { return proto.CompactTextString(m) }
func (*IResponse) ProtoMessage()               {}
func (*IResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IResponse) GetCode() Retcode {
	if m != nil {
		return m.Code
	}
	return Retcode_UNKNOWN_RETCODE
}

func (m *IResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *IResponse) GetData() *google_protobuf.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type IRequest struct {
}

func (m *IRequest) Reset()                    { *m = IRequest{} }
func (m *IRequest) String() string            { return proto.CompactTextString(m) }
func (*IRequest) ProtoMessage()               {}
func (*IRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*BaseRet)(nil), "common.BaseRet")
	proto.RegisterType((*Page)(nil), "common.Page")
	proto.RegisterType((*IResponse)(nil), "common.IResponse")
	proto.RegisterType((*IRequest)(nil), "common.IRequest")
	proto.RegisterEnum("common.Retcode", Retcode_name, Retcode_value)
}

func init() { proto.RegisterFile("common/common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0xfd, 0xf2, 0x35, 0x6d, 0xec, 0x08, 0x36, 0x6c, 0x7b, 0x88, 0x1e, 0xa4, 0xd4, 0x4b, 0x14,
	0x9a, 0x60, 0xbc, 0x78, 0xf0, 0x62, 0xb5, 0x42, 0x29, 0xa4, 0xb2, 0x28, 0x82, 0x17, 0xd9, 0x26,
	0x63, 0x2c, 0x6e, 0xb2, 0xb5, 0xbb, 0x11, 0xeb, 0xaf, 0xf0, 0xe0, 0x8f, 0xf2, 0x67, 0x49, 0x76,
	0x53, 0x8f, 0x3d, 0xed, 0xbc, 0xb7, 0x6f, 0xde, 0xcc, 0x63, 0xa0, 0x9b, 0x88, 0x3c, 0x17, 0x45,
	0x68, 0x9e, 0x60, 0xb9, 0x12, 0x4a, 0x90, 0x96, 0x41, 0x07, 0xfb, 0x99, 0x10, 0x19, 0xc7, 0x50,
	0xb3, 0xf3, 0xf2, 0x39, 0x64, 0xc5, 0xda, 0x48, 0x06, 0x31, 0x38, 0x23, 0x26, 0x91, 0xa2, 0x22,
	0xc7, 0xe0, 0xac, 0x50, 0x25, 0x22, 0x45, 0x0f, 0xfa, 0x96, 0xbf, 0x17, 0x75, 0x82, 0xda, 0x8d,
	0x1a, 0x9a, 0x6e, 0xfe, 0x89, 0x07, 0x4e, 0x8e, 0x52, 0xb2, 0x0c, 0xbd, 0x5e, 0xdf, 0xf2, 0xdb,
	0x74, 0x03, 0x07, 0xdf, 0x16, 0xd8, 0xb7, 0x2c, 0x43, 0xd2, 0x83, 0xe6, 0xa2, 0x48, 0xf1, 0x43,
	0x7b, 0x35, 0xa9, 0x01, 0xc4, 0x85, 0x46, 0x51, 0xe6, 0xba, 0xa9, 0x49, 0xab, 0x92, 0x10, 0xb0,
	0xe5, 0xe2, 0x13, 0xbd, 0x43, 0x4d, 0xe9, 0xba, 0x52, 0x31, 0xce, 0xbd, 0xc8, 0xa8, 0x18, 0xe7,
	0x95, 0x9b, 0x12, 0x8a, 0x71, 0xef, 0xc2, 0xb8, 0x69, 0x40, 0x7c, 0xb0, 0x53, 0xa6, 0x98, 0x77,
	0xd3, 0x6f, 0xf8, 0xbb, 0x51, 0x2f, 0x30, 0x31, 0x83, 0x4d, 0xcc, 0xe0, 0xb2, 0x58, 0x53, 0xad,
	0x18, 0x70, 0x68, 0x4f, 0x28, 0xca, 0xa5, 0x28, 0x24, 0x92, 0x23, 0xb0, 0xb7, 0xa5, 0xd4, 0x9f,
	0xd5, 0x0e, 0xb9, 0xcc, 0xea, 0x78, 0x55, 0xf9, 0x37, 0xad, 0xda, 0x74, 0xfb, 0x34, 0x80, 0x9d,
	0x09, 0xc5, 0xb7, 0x12, 0xa5, 0x3a, 0x39, 0x07, 0xa7, 0x36, 0x26, 0x5d, 0xe8, 0xdc, 0xc7, 0xd3,
	0x78, 0xf6, 0x10, 0x3f, 0xd1, 0xf1, 0xdd, 0xd5, 0xec, 0x7a, 0xec, 0xfe, 0x23, 0x0e, 0xfc, 0x9f,
	0x4d, 0xdd, 0x1f, 0x8b, 0x74, 0x00, 0x46, 0x2c, 0xad, 0xdb, 0xdc, 0xaf, 0xc6, 0x28, 0x82, 0xfa,
	0x7e, 0x8f, 0x7e, 0xb6, 0x50, 0x2f, 0xe5, 0xbc, 0x5a, 0x34, 0x94, 0xaf, 0xeb, 0x61, 0xc2, 0x45,
	0x99, 0x0e, 0x15, 0x26, 0xe6, 0xa2, 0xe1, 0xfb, 0x69, 0x7d, 0xf7, 0x79, 0x4b, 0x13, 0x67, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x19, 0xe8, 0xe6, 0x0f, 0x02, 0x00, 0x00,
}
