// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.4
// source: src/dom/dom.proto

package dom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExcelImortState int32

const (
	ExcelImortState_UNKNOWN_Excel_Import_STATE ExcelImortState = 0
	ExcelImortState_RUNNING                    ExcelImortState = 1 //运行中
	ExcelImortState_SUCCEEDED                  ExcelImortState = 2 //成功
	ExcelImortState_FAILED                     ExcelImortState = 3 //失败
)

// Enum value maps for ExcelImortState.
var (
	ExcelImortState_name = map[int32]string{
		0: "UNKNOWN_Excel_Import_STATE",
		1: "RUNNING",
		2: "SUCCEEDED",
		3: "FAILED",
	}
	ExcelImortState_value = map[string]int32{
		"UNKNOWN_Excel_Import_STATE": 0,
		"RUNNING":                    1,
		"SUCCEEDED":                  2,
		"FAILED":                     3,
	}
)

func (x ExcelImortState) Enum() *ExcelImortState {
	p := new(ExcelImortState)
	*p = x
	return p
}

func (x ExcelImortState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExcelImortState) Descriptor() protoreflect.EnumDescriptor {
	return file_src_dom_dom_proto_enumTypes[0].Descriptor()
}

func (ExcelImortState) Type() protoreflect.EnumType {
	return &file_src_dom_dom_proto_enumTypes[0]
}

func (x ExcelImortState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExcelImortState.Descriptor instead.
func (ExcelImortState) EnumDescriptor() ([]byte, []int) {
	return file_src_dom_dom_proto_rawDescGZIP(), []int{0}
}

var File_src_dom_dom_proto protoreflect.FileDescriptor

var file_src_dom_dom_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x72, 0x63, 0x2f, 0x64, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x64, 0x6f, 0x6d, 0x2a, 0x59, 0x0a, 0x0f, 0x45, 0x78, 0x63, 0x65,
	0x6c, 0x49, 0x6d, 0x6f, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x1a, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x78, 0x63, 0x65, 0x6c, 0x5f, 0x49, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52,
	0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x55, 0x43, 0x43,
	0x45, 0x45, 0x44, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45,
	0x44, 0x10, 0x03, 0x42, 0x3f, 0x0a, 0x16, 0x6e, 0x65, 0x74, 0x2e, 0x73, 0x6b, 0x79, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x6f, 0x6d, 0x5a, 0x25, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6b, 0x79, 0x2d, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2d, 0x74, 0x65, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31,
	0x2f, 0x64, 0x6f, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_dom_dom_proto_rawDescOnce sync.Once
	file_src_dom_dom_proto_rawDescData = file_src_dom_dom_proto_rawDesc
)

func file_src_dom_dom_proto_rawDescGZIP() []byte {
	file_src_dom_dom_proto_rawDescOnce.Do(func() {
		file_src_dom_dom_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_dom_dom_proto_rawDescData)
	})
	return file_src_dom_dom_proto_rawDescData
}

var file_src_dom_dom_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_dom_dom_proto_goTypes = []interface{}{
	(ExcelImortState)(0), // 0: dom.ExcelImortState
}
var file_src_dom_dom_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_dom_dom_proto_init() }
func file_src_dom_dom_proto_init() {
	if File_src_dom_dom_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_dom_dom_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_dom_dom_proto_goTypes,
		DependencyIndexes: file_src_dom_dom_proto_depIdxs,
		EnumInfos:         file_src_dom_dom_proto_enumTypes,
	}.Build()
	File_src_dom_dom_proto = out.File
	file_src_dom_dom_proto_rawDesc = nil
	file_src_dom_dom_proto_goTypes = nil
	file_src_dom_dom_proto_depIdxs = nil
}
