// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/ipam/ipam.proto

package ipam

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IpamItem struct {
	Ip                   string   `protobuf:"bytes,10,opt,name=ip,proto3" json:"ip,omitempty"`
	Status               string   `protobuf:"bytes,20,opt,name=status,proto3" json:"status,omitempty"`
	Os                   string   `protobuf:"bytes,30,opt,name=os,proto3" json:"os,omitempty"`
	Mac                  string   `protobuf:"bytes,40,opt,name=mac,proto3" json:"mac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IpamItem) Reset()         { *m = IpamItem{} }
func (m *IpamItem) String() string { return proto.CompactTextString(m) }
func (*IpamItem) ProtoMessage()    {}
func (*IpamItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_be5d99b2e0ed52ae, []int{0}
}

func (m *IpamItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpamItem.Unmarshal(m, b)
}
func (m *IpamItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpamItem.Marshal(b, m, deterministic)
}
func (m *IpamItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpamItem.Merge(m, src)
}
func (m *IpamItem) XXX_Size() int {
	return xxx_messageInfo_IpamItem.Size(m)
}
func (m *IpamItem) XXX_DiscardUnknown() {
	xxx_messageInfo_IpamItem.DiscardUnknown(m)
}

var xxx_messageInfo_IpamItem proto.InternalMessageInfo

func (m *IpamItem) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *IpamItem) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *IpamItem) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *IpamItem) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func init() {
	proto.RegisterType((*IpamItem)(nil), "ipam.IpamItem")
}

func init() { proto.RegisterFile("src/ipam/ipam.proto", fileDescriptor_be5d99b2e0ed52ae) }

var fileDescriptor_be5d99b2e0ed52ae = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2e, 0x4a, 0xd6,
	0xcf, 0x2c, 0x48, 0xcc, 0x05, 0x13, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6,
	0x52, 0x08, 0x17, 0x87, 0x67, 0x41, 0x62, 0xae, 0x67, 0x49, 0x6a, 0xae, 0x10, 0x1f, 0x17, 0x53,
	0x66, 0x81, 0x04, 0x97, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x53, 0x66, 0x81, 0x90, 0x18, 0x17, 0x5b,
	0x71, 0x49, 0x62, 0x49, 0x69, 0xb1, 0x84, 0x08, 0x58, 0x0c, 0xca, 0x03, 0xa9, 0xcb, 0x2f, 0x96,
	0x90, 0x83, 0xa8, 0xcb, 0x2f, 0x16, 0x12, 0xe0, 0x62, 0xce, 0x4d, 0x4c, 0x96, 0xd0, 0x00, 0x0b,
	0x80, 0x98, 0x4e, 0x8e, 0x5c, 0xe2, 0x79, 0xa9, 0x25, 0x7a, 0xc5, 0xd9, 0x95, 0xc9, 0x39, 0xf9,
	0xa5, 0x29, 0x10, 0x1b, 0xf5, 0x40, 0x16, 0x46, 0xa9, 0xa5, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9,
	0x25, 0xe7, 0xe7, 0xea, 0x17, 0x67, 0x57, 0xea, 0x82, 0x15, 0xe8, 0x96, 0xa4, 0x26, 0xeb, 0x83,
	0x15, 0xe9, 0x97, 0x19, 0x82, 0x1d, 0x99, 0xc4, 0x06, 0xe6, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x2b, 0xe7, 0xf3, 0xe2, 0xbc, 0x00, 0x00, 0x00,
}
