// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eventti/eventti.proto

/*
Package eventti is a generated protocol buffer package.

It is generated from these files:
	eventti/eventti.proto

It has these top-level messages:
	From
	DeviceConfigUpdatedMsg
	Event
	EmailServerCfg
	SmsCfg
	GuosenPushOverCfg
	WSServerCfg
	Target
	CreateNotificationChannelReq
	NotificationChannel
	CreateNotificationChannelRes
	GetNotificationChannelReq
	GetNotificationChannelRes
	CandidateCreatedValue
	StateChangedValue
	TicketCreatedValue
	TicketExpireNotifyValue
	TicketStateChangedValue
	WorkflowStateValue
	WorkflowStateChangedMsg
*/
package eventti

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/sky-cloud-tec/proto/v1/common"
import nap "github.com/sky-cloud-tec/proto/v1/nap"
import workflow "github.com/sky-cloud-tec/proto/v1/workflow"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventType int32

const (
	EventType_UNKNOWN_EVENT_TYPE            EventType = 0
	EventType_DEVICE_CONFIG_UPDATED         EventType = 1
	EventType_DEVICE_RAW_CONFIG_SYNCING     EventType = 2
	EventType_DEVICE_RAW_CONFIG_SYNCED      EventType = 3
	EventType_DEVICE_OBJECT_CONFIG_ANALYSED EventType = 4
	EventType_DEVICE_STATE_CHANGED          EventType = 5
	EventType_DEVICE_CANDIDATE_CREATED      EventType = 6
	EventType_DEVICE_DELETE                 EventType = 7
	EventType_TICKET_CREATED                EventType = 8
	EventType_TICKET_STATE_CHANGED          EventType = 9
	EventType_TICKET_WILL_EXPIRED           EventType = 10
	EventType_ACTIVITY_FAIL                 EventType = 11
	EventType_WORKFLOW_STATE_CHANGED        EventType = 12
)

var EventType_name = map[int32]string{
	0:  "UNKNOWN_EVENT_TYPE",
	1:  "DEVICE_CONFIG_UPDATED",
	2:  "DEVICE_RAW_CONFIG_SYNCING",
	3:  "DEVICE_RAW_CONFIG_SYNCED",
	4:  "DEVICE_OBJECT_CONFIG_ANALYSED",
	5:  "DEVICE_STATE_CHANGED",
	6:  "DEVICE_CANDIDATE_CREATED",
	7:  "DEVICE_DELETE",
	8:  "TICKET_CREATED",
	9:  "TICKET_STATE_CHANGED",
	10: "TICKET_WILL_EXPIRED",
	11: "ACTIVITY_FAIL",
	12: "WORKFLOW_STATE_CHANGED",
}
var EventType_value = map[string]int32{
	"UNKNOWN_EVENT_TYPE":            0,
	"DEVICE_CONFIG_UPDATED":         1,
	"DEVICE_RAW_CONFIG_SYNCING":     2,
	"DEVICE_RAW_CONFIG_SYNCED":      3,
	"DEVICE_OBJECT_CONFIG_ANALYSED": 4,
	"DEVICE_STATE_CHANGED":          5,
	"DEVICE_CANDIDATE_CREATED":      6,
	"DEVICE_DELETE":                 7,
	"TICKET_CREATED":                8,
	"TICKET_STATE_CHANGED":          9,
	"TICKET_WILL_EXPIRED":           10,
	"ACTIVITY_FAIL":                 11,
	"WORKFLOW_STATE_CHANGED":        12,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}
func (EventType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NotificationChannelType int32

const (
	NotificationChannelType_UNKNOWN_NOTIFICATION_CHANNEL_TYPE NotificationChannelType = 0
	NotificationChannelType_EMAIL                             NotificationChannelType = 10
	NotificationChannelType_PHONE                             NotificationChannelType = 20
	NotificationChannelType_WEBSOCKET                         NotificationChannelType = 30
	NotificationChannelType_GUOSEN_PUSH_OVER                  NotificationChannelType = 40
)

var NotificationChannelType_name = map[int32]string{
	0:  "UNKNOWN_NOTIFICATION_CHANNEL_TYPE",
	10: "EMAIL",
	20: "PHONE",
	30: "WEBSOCKET",
	40: "GUOSEN_PUSH_OVER",
}
var NotificationChannelType_value = map[string]int32{
	"UNKNOWN_NOTIFICATION_CHANNEL_TYPE": 0,
	"EMAIL":            10,
	"PHONE":            20,
	"WEBSOCKET":        30,
	"GUOSEN_PUSH_OVER": 40,
}

func (x NotificationChannelType) String() string {
	return proto.EnumName(NotificationChannelType_name, int32(x))
}
func (NotificationChannelType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type EmailProtocol int32

const (
	EmailProtocol_UNKNOWN_PROTOCOL EmailProtocol = 0
	EmailProtocol_SMTP             EmailProtocol = 10
	EmailProtocol_SECURE_SMTP      EmailProtocol = 20
)

var EmailProtocol_name = map[int32]string{
	0:  "UNKNOWN_PROTOCOL",
	10: "SMTP",
	20: "SECURE_SMTP",
}
var EmailProtocol_value = map[string]int32{
	"UNKNOWN_PROTOCOL": 0,
	"SMTP":             10,
	"SECURE_SMTP":      20,
}

func (x EmailProtocol) String() string {
	return proto.EnumName(EmailProtocol_name, int32(x))
}
func (EmailProtocol) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type From struct {
	Host   string `protobuf:"bytes,10,opt,name=host" json:"host,omitempty"`
	Module string `protobuf:"bytes,20,opt,name=module" json:"module,omitempty"`
}

func (m *From) Reset()                    { *m = From{} }
func (m *From) String() string            { return proto.CompactTextString(m) }
func (*From) ProtoMessage()               {}
func (*From) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *From) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *From) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

type DeviceConfigUpdatedMsg struct {
	DeviceId   string `protobuf:"bytes,10,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	DeviceName string `protobuf:"bytes,20,opt,name=device_name,json=deviceName" json:"device_name,omitempty"`
	Message    string `protobuf:"bytes,30,opt,name=message" json:"message,omitempty"`
}

func (m *DeviceConfigUpdatedMsg) Reset()                    { *m = DeviceConfigUpdatedMsg{} }
func (m *DeviceConfigUpdatedMsg) String() string            { return proto.CompactTextString(m) }
func (*DeviceConfigUpdatedMsg) ProtoMessage()               {}
func (*DeviceConfigUpdatedMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeviceConfigUpdatedMsg) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeviceConfigUpdatedMsg) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *DeviceConfigUpdatedMsg) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Event struct {
	Id        string    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type      EventType `protobuf:"varint,20,opt,name=type,enum=eventti.EventType" json:"type,omitempty"`
	Timestamp int64     `protobuf:"varint,30,opt,name=timestamp" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Metadata:
	//	*Event_Wscm
	//	*Event_Dcum
	Metadata isEvent_Metadata `protobuf_oneof:"metadata"`
	Target   *Target          `protobuf:"bytes,50,opt,name=target" json:"target,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isEvent_Metadata interface {
	isEvent_Metadata()
}

type Event_Wscm struct {
	Wscm *WorkflowStateChangedMsg `protobuf:"bytes,210,opt,name=wscm,oneof"`
}
type Event_Dcum struct {
	Dcum *DeviceConfigUpdatedMsg `protobuf:"bytes,220,opt,name=dcum,oneof"`
}

func (*Event_Wscm) isEvent_Metadata() {}
func (*Event_Dcum) isEvent_Metadata() {}

func (m *Event) GetMetadata() isEvent_Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_UNKNOWN_EVENT_TYPE
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetWscm() *WorkflowStateChangedMsg {
	if x, ok := m.GetMetadata().(*Event_Wscm); ok {
		return x.Wscm
	}
	return nil
}

func (m *Event) GetDcum() *DeviceConfigUpdatedMsg {
	if x, ok := m.GetMetadata().(*Event_Dcum); ok {
		return x.Dcum
	}
	return nil
}

func (m *Event) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Event) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Event_OneofMarshaler, _Event_OneofUnmarshaler, _Event_OneofSizer, []interface{}{
		(*Event_Wscm)(nil),
		(*Event_Dcum)(nil),
	}
}

func _Event_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Event)
	// metadata
	switch x := m.Metadata.(type) {
	case *Event_Wscm:
		b.EncodeVarint(210<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Wscm); err != nil {
			return err
		}
	case *Event_Dcum:
		b.EncodeVarint(220<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Dcum); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Event.Metadata has unexpected type %T", x)
	}
	return nil
}

func _Event_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Event)
	switch tag {
	case 210: // metadata.wscm
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WorkflowStateChangedMsg)
		err := b.DecodeMessage(msg)
		m.Metadata = &Event_Wscm{msg}
		return true, err
	case 220: // metadata.dcum
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DeviceConfigUpdatedMsg)
		err := b.DecodeMessage(msg)
		m.Metadata = &Event_Dcum{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Event_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Event)
	// metadata
	switch x := m.Metadata.(type) {
	case *Event_Wscm:
		s := proto.Size(x.Wscm)
		n += proto.SizeVarint(210<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Event_Dcum:
		s := proto.Size(x.Dcum)
		n += proto.SizeVarint(220<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type EmailServerCfg struct {
	Account  string        `protobuf:"bytes,10,opt,name=account" json:"account,omitempty"`
	Password string        `protobuf:"bytes,20,opt,name=password" json:"password,omitempty"`
	Host     string        `protobuf:"bytes,30,opt,name=host" json:"host,omitempty"`
	Port     int32         `protobuf:"varint,40,opt,name=port" json:"port,omitempty"`
	Protocol EmailProtocol `protobuf:"varint,50,opt,name=protocol,enum=eventti.EmailProtocol" json:"protocol,omitempty"`
	Timeout  int32         `protobuf:"varint,60,opt,name=timeout" json:"timeout,omitempty"`
}

func (m *EmailServerCfg) Reset()                    { *m = EmailServerCfg{} }
func (m *EmailServerCfg) String() string            { return proto.CompactTextString(m) }
func (*EmailServerCfg) ProtoMessage()               {}
func (*EmailServerCfg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EmailServerCfg) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *EmailServerCfg) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *EmailServerCfg) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *EmailServerCfg) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *EmailServerCfg) GetProtocol() EmailProtocol {
	if m != nil {
		return m.Protocol
	}
	return EmailProtocol_UNKNOWN_PROTOCOL
}

func (m *EmailServerCfg) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type SmsCfg struct {
}

func (m *SmsCfg) Reset()                    { *m = SmsCfg{} }
func (m *SmsCfg) String() string            { return proto.CompactTextString(m) }
func (*SmsCfg) ProtoMessage()               {}
func (*SmsCfg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type GuosenPushOverCfg struct {
	Username  string `protobuf:"bytes,10,opt,name=username" json:"username,omitempty"`
	Password  string `protobuf:"bytes,20,opt,name=password" json:"password,omitempty"`
	LoginUrl  string `protobuf:"bytes,30,opt,name=loginUrl" json:"loginUrl,omitempty"`
	IssuedUrl string `protobuf:"bytes,40,opt,name=issuedUrl" json:"issuedUrl,omitempty"`
}

func (m *GuosenPushOverCfg) Reset()                    { *m = GuosenPushOverCfg{} }
func (m *GuosenPushOverCfg) String() string            { return proto.CompactTextString(m) }
func (*GuosenPushOverCfg) ProtoMessage()               {}
func (*GuosenPushOverCfg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GuosenPushOverCfg) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GuosenPushOverCfg) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GuosenPushOverCfg) GetLoginUrl() string {
	if m != nil {
		return m.LoginUrl
	}
	return ""
}

func (m *GuosenPushOverCfg) GetIssuedUrl() string {
	if m != nil {
		return m.IssuedUrl
	}
	return ""
}

type WSServerCfg struct {
	Port string `protobuf:"bytes,10,opt,name=port" json:"port,omitempty"`
	Path string `protobuf:"bytes,20,opt,name=path" json:"path,omitempty"`
}

func (m *WSServerCfg) Reset()                    { *m = WSServerCfg{} }
func (m *WSServerCfg) String() string            { return proto.CompactTextString(m) }
func (*WSServerCfg) ProtoMessage()               {}
func (*WSServerCfg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *WSServerCfg) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *WSServerCfg) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Target struct {
	Users []string `protobuf:"bytes,10,rep,name=users" json:"users,omitempty"`
	Roles []string `protobuf:"bytes,20,rep,name=roles" json:"roles,omitempty"`
}

func (m *Target) Reset()                    { *m = Target{} }
func (m *Target) String() string            { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()               {}
func (*Target) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Target) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Target) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type CreateNotificationChannelReq struct {
	Nc *NotificationChannel `protobuf:"bytes,10,opt,name=nc" json:"nc,omitempty"`
}

func (m *CreateNotificationChannelReq) Reset()                    { *m = CreateNotificationChannelReq{} }
func (m *CreateNotificationChannelReq) String() string            { return proto.CompactTextString(m) }
func (*CreateNotificationChannelReq) ProtoMessage()               {}
func (*CreateNotificationChannelReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CreateNotificationChannelReq) GetNc() *NotificationChannel {
	if m != nil {
		return m.Nc
	}
	return nil
}

type NotificationChannel struct {
	Id          string                  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string                  `protobuf:"bytes,10,opt,name=name" json:"name,omitempty"`
	Etypes      []EventType             `protobuf:"varint,15,rep,packed,name=etypes,enum=eventti.EventType" json:"etypes,omitempty"`
	Type        NotificationChannelType `protobuf:"varint,20,opt,name=type,enum=eventti.NotificationChannelType" json:"type,omitempty"`
	Description string                  `protobuf:"bytes,25,opt,name=description" json:"description,omitempty"`
	Target      *Target                 `protobuf:"bytes,30,opt,name=target" json:"target,omitempty"`
	// Types that are valid to be assigned to Cfg:
	//	*NotificationChannel_EmailServerCfg
	//	*NotificationChannel_SmsCfg
	//	*NotificationChannel_GpoCfg
	//	*NotificationChannel_WsServerCfg
	Cfg isNotificationChannel_Cfg `protobuf_oneof:"cfg"`
}

func (m *NotificationChannel) Reset()                    { *m = NotificationChannel{} }
func (m *NotificationChannel) String() string            { return proto.CompactTextString(m) }
func (*NotificationChannel) ProtoMessage()               {}
func (*NotificationChannel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type isNotificationChannel_Cfg interface {
	isNotificationChannel_Cfg()
}

type NotificationChannel_EmailServerCfg struct {
	EmailServerCfg *EmailServerCfg `protobuf:"bytes,40,opt,name=email_server_cfg,json=emailServerCfg,oneof"`
}
type NotificationChannel_SmsCfg struct {
	SmsCfg *SmsCfg `protobuf:"bytes,50,opt,name=sms_cfg,json=smsCfg,oneof"`
}
type NotificationChannel_GpoCfg struct {
	GpoCfg *GuosenPushOverCfg `protobuf:"bytes,60,opt,name=gpo_cfg,json=gpoCfg,oneof"`
}
type NotificationChannel_WsServerCfg struct {
	WsServerCfg *WSServerCfg `protobuf:"bytes,70,opt,name=ws_server_cfg,json=wsServerCfg,oneof"`
}

func (*NotificationChannel_EmailServerCfg) isNotificationChannel_Cfg() {}
func (*NotificationChannel_SmsCfg) isNotificationChannel_Cfg()         {}
func (*NotificationChannel_GpoCfg) isNotificationChannel_Cfg()         {}
func (*NotificationChannel_WsServerCfg) isNotificationChannel_Cfg()    {}

func (m *NotificationChannel) GetCfg() isNotificationChannel_Cfg {
	if m != nil {
		return m.Cfg
	}
	return nil
}

func (m *NotificationChannel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NotificationChannel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NotificationChannel) GetEtypes() []EventType {
	if m != nil {
		return m.Etypes
	}
	return nil
}

func (m *NotificationChannel) GetType() NotificationChannelType {
	if m != nil {
		return m.Type
	}
	return NotificationChannelType_UNKNOWN_NOTIFICATION_CHANNEL_TYPE
}

func (m *NotificationChannel) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NotificationChannel) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *NotificationChannel) GetEmailServerCfg() *EmailServerCfg {
	if x, ok := m.GetCfg().(*NotificationChannel_EmailServerCfg); ok {
		return x.EmailServerCfg
	}
	return nil
}

func (m *NotificationChannel) GetSmsCfg() *SmsCfg {
	if x, ok := m.GetCfg().(*NotificationChannel_SmsCfg); ok {
		return x.SmsCfg
	}
	return nil
}

func (m *NotificationChannel) GetGpoCfg() *GuosenPushOverCfg {
	if x, ok := m.GetCfg().(*NotificationChannel_GpoCfg); ok {
		return x.GpoCfg
	}
	return nil
}

func (m *NotificationChannel) GetWsServerCfg() *WSServerCfg {
	if x, ok := m.GetCfg().(*NotificationChannel_WsServerCfg); ok {
		return x.WsServerCfg
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*NotificationChannel) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _NotificationChannel_OneofMarshaler, _NotificationChannel_OneofUnmarshaler, _NotificationChannel_OneofSizer, []interface{}{
		(*NotificationChannel_EmailServerCfg)(nil),
		(*NotificationChannel_SmsCfg)(nil),
		(*NotificationChannel_GpoCfg)(nil),
		(*NotificationChannel_WsServerCfg)(nil),
	}
}

func _NotificationChannel_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*NotificationChannel)
	// cfg
	switch x := m.Cfg.(type) {
	case *NotificationChannel_EmailServerCfg:
		b.EncodeVarint(40<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EmailServerCfg); err != nil {
			return err
		}
	case *NotificationChannel_SmsCfg:
		b.EncodeVarint(50<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SmsCfg); err != nil {
			return err
		}
	case *NotificationChannel_GpoCfg:
		b.EncodeVarint(60<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GpoCfg); err != nil {
			return err
		}
	case *NotificationChannel_WsServerCfg:
		b.EncodeVarint(70<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WsServerCfg); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("NotificationChannel.Cfg has unexpected type %T", x)
	}
	return nil
}

func _NotificationChannel_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*NotificationChannel)
	switch tag {
	case 40: // cfg.email_server_cfg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EmailServerCfg)
		err := b.DecodeMessage(msg)
		m.Cfg = &NotificationChannel_EmailServerCfg{msg}
		return true, err
	case 50: // cfg.sms_cfg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SmsCfg)
		err := b.DecodeMessage(msg)
		m.Cfg = &NotificationChannel_SmsCfg{msg}
		return true, err
	case 60: // cfg.gpo_cfg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GuosenPushOverCfg)
		err := b.DecodeMessage(msg)
		m.Cfg = &NotificationChannel_GpoCfg{msg}
		return true, err
	case 70: // cfg.ws_server_cfg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WSServerCfg)
		err := b.DecodeMessage(msg)
		m.Cfg = &NotificationChannel_WsServerCfg{msg}
		return true, err
	default:
		return false, nil
	}
}

func _NotificationChannel_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*NotificationChannel)
	// cfg
	switch x := m.Cfg.(type) {
	case *NotificationChannel_EmailServerCfg:
		s := proto.Size(x.EmailServerCfg)
		n += proto.SizeVarint(40<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *NotificationChannel_SmsCfg:
		s := proto.Size(x.SmsCfg)
		n += proto.SizeVarint(50<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *NotificationChannel_GpoCfg:
		s := proto.Size(x.GpoCfg)
		n += proto.SizeVarint(60<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *NotificationChannel_WsServerCfg:
		s := proto.Size(x.WsServerCfg)
		n += proto.SizeVarint(70<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CreateNotificationChannelRes struct {
	Ret *common.BaseRet `protobuf:"bytes,10,opt,name=ret" json:"ret,omitempty"`
	Id  int32           `protobuf:"varint,20,opt,name=id" json:"id,omitempty"`
}

func (m *CreateNotificationChannelRes) Reset()                    { *m = CreateNotificationChannelRes{} }
func (m *CreateNotificationChannelRes) String() string            { return proto.CompactTextString(m) }
func (*CreateNotificationChannelRes) ProtoMessage()               {}
func (*CreateNotificationChannelRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CreateNotificationChannelRes) GetRet() *common.BaseRet {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *CreateNotificationChannelRes) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetNotificationChannelReq struct {
	Page *common.Page `protobuf:"bytes,10,opt,name=page" json:"page,omitempty"`
}

func (m *GetNotificationChannelReq) Reset()                    { *m = GetNotificationChannelReq{} }
func (m *GetNotificationChannelReq) String() string            { return proto.CompactTextString(m) }
func (*GetNotificationChannelReq) ProtoMessage()               {}
func (*GetNotificationChannelReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetNotificationChannelReq) GetPage() *common.Page {
	if m != nil {
		return m.Page
	}
	return nil
}

type GetNotificationChannelRes struct {
	Ret   *common.BaseRet        `protobuf:"bytes,10,opt,name=ret" json:"ret,omitempty"`
	Page  *common.Page           `protobuf:"bytes,20,opt,name=page" json:"page,omitempty"`
	Total int32                  `protobuf:"varint,30,opt,name=total" json:"total,omitempty"`
	Ncs   []*NotificationChannel `protobuf:"bytes,40,rep,name=ncs" json:"ncs,omitempty"`
}

func (m *GetNotificationChannelRes) Reset()                    { *m = GetNotificationChannelRes{} }
func (m *GetNotificationChannelRes) String() string            { return proto.CompactTextString(m) }
func (*GetNotificationChannelRes) ProtoMessage()               {}
func (*GetNotificationChannelRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetNotificationChannelRes) GetRet() *common.BaseRet {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *GetNotificationChannelRes) GetPage() *common.Page {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *GetNotificationChannelRes) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetNotificationChannelRes) GetNcs() []*NotificationChannel {
	if m != nil {
		return m.Ncs
	}
	return nil
}

type CandidateCreatedValue struct {
	Device    string `protobuf:"bytes,10,opt,name=device" json:"device,omitempty"`
	Candidate string `protobuf:"bytes,20,opt,name=candidate" json:"candidate,omitempty"`
}

func (m *CandidateCreatedValue) Reset()                    { *m = CandidateCreatedValue{} }
func (m *CandidateCreatedValue) String() string            { return proto.CompactTextString(m) }
func (*CandidateCreatedValue) ProtoMessage()               {}
func (*CandidateCreatedValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *CandidateCreatedValue) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *CandidateCreatedValue) GetCandidate() string {
	if m != nil {
		return m.Candidate
	}
	return ""
}

type StateChangedValue struct {
	Device string          `protobuf:"bytes,10,opt,name=device" json:"device,omitempty"`
	State  nap.DeviceState `protobuf:"varint,20,opt,name=state,enum=nap.DeviceState" json:"state,omitempty"`
}

func (m *StateChangedValue) Reset()                    { *m = StateChangedValue{} }
func (m *StateChangedValue) String() string            { return proto.CompactTextString(m) }
func (*StateChangedValue) ProtoMessage()               {}
func (*StateChangedValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *StateChangedValue) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *StateChangedValue) GetState() nap.DeviceState {
	if m != nil {
		return m.State
	}
	return nap.DeviceState_UNKNOWN_DEVICE_STATE
}

type TicketCreatedValue struct {
	Ticket string `protobuf:"bytes,10,opt,name=ticket" json:"ticket,omitempty"`
	Owner  string `protobuf:"bytes,20,opt,name=owner" json:"owner,omitempty"`
	Cap    string `protobuf:"bytes,30,opt,name=cap" json:"cap,omitempty"`
}

func (m *TicketCreatedValue) Reset()                    { *m = TicketCreatedValue{} }
func (m *TicketCreatedValue) String() string            { return proto.CompactTextString(m) }
func (*TicketCreatedValue) ProtoMessage()               {}
func (*TicketCreatedValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *TicketCreatedValue) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *TicketCreatedValue) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *TicketCreatedValue) GetCap() string {
	if m != nil {
		return m.Cap
	}
	return ""
}

type TicketExpireNotifyValue struct {
	Ticket string `protobuf:"bytes,10,opt,name=ticket" json:"ticket,omitempty"`
	Owner  string `protobuf:"bytes,20,opt,name=owner" json:"owner,omitempty"`
	Expire int64  `protobuf:"varint,30,opt,name=expire" json:"expire,omitempty"`
	Cap    string `protobuf:"bytes,40,opt,name=cap" json:"cap,omitempty"`
}

func (m *TicketExpireNotifyValue) Reset()                    { *m = TicketExpireNotifyValue{} }
func (m *TicketExpireNotifyValue) String() string            { return proto.CompactTextString(m) }
func (*TicketExpireNotifyValue) ProtoMessage()               {}
func (*TicketExpireNotifyValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *TicketExpireNotifyValue) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *TicketExpireNotifyValue) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *TicketExpireNotifyValue) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

func (m *TicketExpireNotifyValue) GetCap() string {
	if m != nil {
		return m.Cap
	}
	return ""
}

type TicketStateChangedValue struct {
	Ticket  string                `protobuf:"bytes,10,opt,name=ticket" json:"ticket,omitempty"`
	Before  nap.PolicyTicketStage `protobuf:"varint,20,opt,name=before,enum=nap.PolicyTicketStage" json:"before,omitempty"`
	Current nap.PolicyTicketStage `protobuf:"varint,30,opt,name=current,enum=nap.PolicyTicketStage" json:"current,omitempty"`
	Cap     string                `protobuf:"bytes,40,opt,name=cap" json:"cap,omitempty"`
}

func (m *TicketStateChangedValue) Reset()                    { *m = TicketStateChangedValue{} }
func (m *TicketStateChangedValue) String() string            { return proto.CompactTextString(m) }
func (*TicketStateChangedValue) ProtoMessage()               {}
func (*TicketStateChangedValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *TicketStateChangedValue) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *TicketStateChangedValue) GetBefore() nap.PolicyTicketStage {
	if m != nil {
		return m.Before
	}
	return nap.PolicyTicketStage_UNKNOWN_POLICY_TICKET_STAGE
}

func (m *TicketStateChangedValue) GetCurrent() nap.PolicyTicketStage {
	if m != nil {
		return m.Current
	}
	return nap.PolicyTicketStage_UNKNOWN_POLICY_TICKET_STAGE
}

func (m *TicketStateChangedValue) GetCap() string {
	if m != nil {
		return m.Cap
	}
	return ""
}

type WorkflowStateValue struct {
	Name     string                 `protobuf:"bytes,10,opt,name=name" json:"name,omitempty"`
	Username string                 `protobuf:"bytes,20,opt,name=username" json:"username,omitempty"`
	State    workflow.WorkflowState `protobuf:"varint,30,opt,name=state,enum=workflow.WorkflowState" json:"state,omitempty"`
	StartAt  int64                  `protobuf:"varint,40,opt,name=startAt" json:"startAt,omitempty"`
	EndAt    int64                  `protobuf:"varint,50,opt,name=endAt" json:"endAt,omitempty"`
}

func (m *WorkflowStateValue) Reset()                    { *m = WorkflowStateValue{} }
func (m *WorkflowStateValue) String() string            { return proto.CompactTextString(m) }
func (*WorkflowStateValue) ProtoMessage()               {}
func (*WorkflowStateValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *WorkflowStateValue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WorkflowStateValue) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *WorkflowStateValue) GetState() workflow.WorkflowState {
	if m != nil {
		return m.State
	}
	return workflow.WorkflowState_UNKNOWN_WORKFLOW_STATE
}

func (m *WorkflowStateValue) GetStartAt() int64 {
	if m != nil {
		return m.StartAt
	}
	return 0
}

func (m *WorkflowStateValue) GetEndAt() int64 {
	if m != nil {
		return m.EndAt
	}
	return 0
}

type WorkflowStateChangedMsg struct {
	Id  string                `protobuf:"bytes,10,opt,name=id" json:"id,omitempty"`
	Wsv []*WorkflowStateValue `protobuf:"bytes,20,rep,name=wsv" json:"wsv,omitempty"`
}

func (m *WorkflowStateChangedMsg) Reset()                    { *m = WorkflowStateChangedMsg{} }
func (m *WorkflowStateChangedMsg) String() string            { return proto.CompactTextString(m) }
func (*WorkflowStateChangedMsg) ProtoMessage()               {}
func (*WorkflowStateChangedMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *WorkflowStateChangedMsg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WorkflowStateChangedMsg) GetWsv() []*WorkflowStateValue {
	if m != nil {
		return m.Wsv
	}
	return nil
}

func init() {
	proto.RegisterType((*From)(nil), "eventti.From")
	proto.RegisterType((*DeviceConfigUpdatedMsg)(nil), "eventti.DeviceConfigUpdatedMsg")
	proto.RegisterType((*Event)(nil), "eventti.Event")
	proto.RegisterType((*EmailServerCfg)(nil), "eventti.EmailServerCfg")
	proto.RegisterType((*SmsCfg)(nil), "eventti.SmsCfg")
	proto.RegisterType((*GuosenPushOverCfg)(nil), "eventti.GuosenPushOverCfg")
	proto.RegisterType((*WSServerCfg)(nil), "eventti.WSServerCfg")
	proto.RegisterType((*Target)(nil), "eventti.Target")
	proto.RegisterType((*CreateNotificationChannelReq)(nil), "eventti.CreateNotificationChannelReq")
	proto.RegisterType((*NotificationChannel)(nil), "eventti.NotificationChannel")
	proto.RegisterType((*CreateNotificationChannelRes)(nil), "eventti.CreateNotificationChannelRes")
	proto.RegisterType((*GetNotificationChannelReq)(nil), "eventti.GetNotificationChannelReq")
	proto.RegisterType((*GetNotificationChannelRes)(nil), "eventti.GetNotificationChannelRes")
	proto.RegisterType((*CandidateCreatedValue)(nil), "eventti.CandidateCreatedValue")
	proto.RegisterType((*StateChangedValue)(nil), "eventti.StateChangedValue")
	proto.RegisterType((*TicketCreatedValue)(nil), "eventti.TicketCreatedValue")
	proto.RegisterType((*TicketExpireNotifyValue)(nil), "eventti.TicketExpireNotifyValue")
	proto.RegisterType((*TicketStateChangedValue)(nil), "eventti.TicketStateChangedValue")
	proto.RegisterType((*WorkflowStateValue)(nil), "eventti.WorkflowStateValue")
	proto.RegisterType((*WorkflowStateChangedMsg)(nil), "eventti.WorkflowStateChangedMsg")
	proto.RegisterEnum("eventti.EventType", EventType_name, EventType_value)
	proto.RegisterEnum("eventti.NotificationChannelType", NotificationChannelType_name, NotificationChannelType_value)
	proto.RegisterEnum("eventti.EmailProtocol", EmailProtocol_name, EmailProtocol_value)
}

func init() { proto.RegisterFile("eventti/eventti.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xef, 0x6e, 0xdb, 0xc8,
	0x11, 0xb7, 0xfe, 0x5a, 0x1a, 0xc5, 0x36, 0xb3, 0x51, 0x6c, 0x5a, 0x71, 0x1c, 0x85, 0x40, 0x53,
	0xd5, 0xa8, 0xe5, 0x56, 0x4d, 0x5a, 0xa0, 0x48, 0x81, 0xca, 0x14, 0x6d, 0xab, 0x91, 0x29, 0x95,
	0xa2, 0xad, 0xb8, 0x5f, 0x04, 0x86, 0x5c, 0xd1, 0x84, 0x25, 0x52, 0xe1, 0xae, 0xac, 0x1a, 0xfd,
	0x58, 0xdc, 0x93, 0x1c, 0xee, 0x9e, 0xe2, 0x5e, 0xe2, 0xee, 0xf3, 0x01, 0xf7, 0x2a, 0x87, 0x5d,
	0x2e, 0x69, 0xd9, 0x91, 0x7d, 0x87, 0xfb, 0xa4, 0x9d, 0xf9, 0xcd, 0xfc, 0x76, 0x76, 0x76, 0x66,
	0x87, 0x82, 0xe7, 0xf8, 0x1a, 0xfb, 0x94, 0x7a, 0x07, 0xe2, 0xb7, 0x3e, 0x0d, 0x03, 0x1a, 0xa0,
	0x55, 0x21, 0x56, 0x9e, 0xd9, 0xc1, 0x64, 0x12, 0xf8, 0x07, 0xd1, 0x4f, 0x84, 0x56, 0xd6, 0x7c,
	0x6b, 0x7a, 0xe0, 0x5b, 0x53, 0x21, 0x6e, 0xcd, 0x83, 0xf0, 0x6a, 0x34, 0x0e, 0xe6, 0x07, 0xf1,
	0x22, 0x02, 0x94, 0x06, 0x64, 0x8f, 0xc2, 0x60, 0x82, 0x10, 0x64, 0x2f, 0x03, 0x42, 0x65, 0xa8,
	0xa6, 0x6a, 0x45, 0x83, 0xaf, 0xd1, 0x26, 0xe4, 0x27, 0x81, 0x33, 0x1b, 0x63, 0xb9, 0xcc, 0xb5,
	0x42, 0x52, 0xa6, 0xb0, 0xd9, 0xc2, 0xd7, 0x9e, 0x8d, 0xd5, 0xc0, 0x1f, 0x79, 0xee, 0xd9, 0xd4,
	0xb1, 0x28, 0x76, 0x4e, 0x89, 0x8b, 0x5e, 0x40, 0xd1, 0xe1, 0xc8, 0xd0, 0x73, 0x04, 0x55, 0x21,
	0x52, 0xb4, 0x1d, 0xf4, 0x0a, 0x4a, 0x02, 0xf4, 0xad, 0x49, 0xcc, 0x09, 0x91, 0x4a, 0xb7, 0x26,
	0x18, 0xc9, 0xb0, 0x3a, 0xc1, 0x84, 0x58, 0x2e, 0x96, 0x77, 0x39, 0x18, 0x8b, 0xca, 0xff, 0xd3,
	0x90, 0xd3, 0xd8, 0x71, 0xd1, 0x3a, 0xa4, 0x3d, 0x47, 0x4e, 0x71, 0x38, 0xed, 0x39, 0xe8, 0x0d,
	0x64, 0xe9, 0xcd, 0x34, 0x62, 0x5b, 0x6f, 0xa0, 0x7a, 0x9c, 0x23, 0x6e, 0x6d, 0xde, 0x4c, 0xb1,
	0xc1, 0x71, 0xb4, 0x03, 0x45, 0xea, 0x4d, 0x30, 0xa1, 0xd6, 0x64, 0xca, 0xd9, 0x33, 0xc6, 0xad,
	0x02, 0xfd, 0x0d, 0xb2, 0x73, 0x62, 0x4f, 0xe4, 0x1f, 0x18, 0x71, 0xa9, 0x51, 0x4d, 0x68, 0x06,
	0x22, 0x5b, 0x7d, 0x6a, 0x51, 0xac, 0x5e, 0x5a, 0xbe, 0xcb, 0x0f, 0x7a, 0xb2, 0x62, 0x70, 0x07,
	0xf4, 0x57, 0xc8, 0x3a, 0xf6, 0x6c, 0x22, 0xff, 0x18, 0x39, 0xbe, 0x4a, 0x1c, 0x97, 0x27, 0x88,
	0xf9, 0x31, 0x7b, 0xf4, 0x7b, 0xc8, 0x53, 0x2b, 0x74, 0x31, 0x95, 0x1b, 0xdc, 0x71, 0x23, 0x71,
	0x34, 0xb9, 0xda, 0x10, 0xf0, 0x21, 0x40, 0x61, 0x82, 0xa9, 0xe5, 0x58, 0xd4, 0x52, 0xbe, 0x4b,
	0xc1, 0xba, 0x36, 0xb1, 0xbc, 0x71, 0x1f, 0x87, 0xd7, 0x38, 0x54, 0x47, 0x2e, 0x4b, 0x99, 0x65,
	0xdb, 0xc1, 0xcc, 0x8f, 0x6f, 0x2e, 0x16, 0x51, 0x05, 0x0a, 0x53, 0x8b, 0x90, 0x79, 0x10, 0x3a,
	0x22, 0xd5, 0x89, 0x9c, 0x5c, 0xf6, 0xee, 0xc2, 0x65, 0x23, 0xc8, 0x4e, 0x83, 0x90, 0xca, 0xb5,
	0x6a, 0xaa, 0x96, 0x33, 0xf8, 0x1a, 0x35, 0xa0, 0xc0, 0xab, 0xc4, 0x0e, 0xc6, 0x3c, 0xce, 0xf5,
	0xc6, 0xe6, 0x6d, 0x82, 0x59, 0x20, 0x3d, 0x81, 0x1a, 0x89, 0x1d, 0x8b, 0x88, 0xe5, 0x35, 0x98,
	0x51, 0xf9, 0x3d, 0xa7, 0x8a, 0x45, 0xa5, 0x00, 0xf9, 0xfe, 0x84, 0xa8, 0x23, 0x57, 0xf9, 0x2a,
	0x05, 0x4f, 0x8f, 0x67, 0x01, 0xc1, 0x7e, 0x6f, 0x46, 0x2e, 0xbb, 0xe2, 0x2c, 0x15, 0x28, 0xcc,
	0x08, 0x0e, 0x79, 0x71, 0x88, 0xda, 0x89, 0xe5, 0x47, 0x4f, 0x53, 0x81, 0xc2, 0x38, 0x70, 0x3d,
	0xff, 0x2c, 0x1c, 0x8b, 0x13, 0x25, 0x32, 0xbb, 0x76, 0x8f, 0x90, 0x19, 0x76, 0x18, 0x58, 0xe3,
	0xe0, 0xad, 0x42, 0x79, 0x07, 0xa5, 0x41, 0xff, 0x36, 0x99, 0x71, 0x0a, 0x44, 0x0f, 0xf0, 0x14,
	0x30, 0x9d, 0x45, 0x2f, 0xc5, 0xa6, 0x7c, 0xad, 0xbc, 0x85, 0x7c, 0x74, 0x4b, 0xa8, 0x0c, 0x39,
	0x16, 0x22, 0x91, 0xa1, 0x9a, 0xa9, 0x15, 0x8d, 0x48, 0x60, 0xda, 0x30, 0x18, 0x63, 0x22, 0x97,
	0x23, 0x2d, 0x17, 0x94, 0x0e, 0xec, 0xa8, 0x21, 0xb6, 0x28, 0xd6, 0x03, 0xea, 0x8d, 0x3c, 0xdb,
	0xa2, 0x5e, 0xe0, 0xb3, 0x92, 0xf2, 0xf1, 0xd8, 0xc0, 0x9f, 0xd1, 0x1f, 0x21, 0xed, 0xdb, 0x7c,
	0xef, 0x52, 0x63, 0x27, 0x49, 0xf3, 0x32, 0xe3, 0xb4, 0x6f, 0x2b, 0xdf, 0x67, 0xe0, 0xd9, 0x12,
	0xec, 0x8b, 0xfe, 0x40, 0x90, 0x5d, 0x48, 0x28, 0x5f, 0xa3, 0x3d, 0xc8, 0x63, 0xd6, 0x14, 0x44,
	0xde, 0xa8, 0x66, 0x1e, 0xe8, 0x1a, 0x61, 0x81, 0xde, 0xde, 0xe9, 0xaf, 0xea, 0x63, 0x71, 0x2d,
	0x74, 0x5b, 0x95, 0xb5, 0x3a, 0xb1, 0x43, 0x6f, 0xca, 0x70, 0x79, 0x9b, 0x6f, 0xbe, 0xa8, 0x5a,
	0x68, 0x80, 0xdd, 0x47, 0x1b, 0x00, 0xa9, 0x20, 0x61, 0x56, 0x6a, 0x43, 0xc2, 0xef, 0x69, 0x68,
	0x8f, 0x5c, 0x7e, 0x91, 0xa5, 0xc6, 0xd6, 0xdd, 0x5a, 0x4c, 0xee, 0xf1, 0x64, 0xc5, 0x58, 0xc7,
	0x77, 0xdb, 0x64, 0x0f, 0x56, 0xc9, 0x84, 0x70, 0xdf, 0xfb, 0xfd, 0x16, 0x95, 0xe4, 0xc9, 0x8a,
	0x91, 0x27, 0x7c, 0x85, 0xde, 0xc1, 0xaa, 0x3b, 0x0d, 0xb8, 0xed, 0x7b, 0x6e, 0x5b, 0x49, 0x6c,
	0xbf, 0xa8, 0x59, 0xe6, 0xe6, 0x4e, 0x03, 0xe6, 0xf6, 0x77, 0x58, 0x9b, 0x93, 0xc5, 0x20, 0x8f,
	0xb8, 0x73, 0xf9, 0xf6, 0x29, 0xe9, 0x2f, 0x46, 0x58, 0x9a, 0x93, 0x44, 0x3c, 0xcc, 0x41, 0xc6,
	0x1e, 0xb9, 0xca, 0xbf, 0x1f, 0xad, 0x10, 0x82, 0x5e, 0x43, 0x26, 0xc4, 0x54, 0x94, 0xc8, 0x46,
	0x5d, 0xbc, 0xf7, 0x87, 0x16, 0xc1, 0x06, 0xa6, 0x06, 0xc3, 0xc4, 0xf5, 0x97, 0x79, 0xe3, 0xa5,
	0x3d, 0x47, 0xf9, 0x07, 0x6c, 0x1f, 0x63, 0xfa, 0x40, 0xc5, 0x55, 0x59, 0x6d, 0xbb, 0x58, 0x10,
	0x3e, 0x89, 0x09, 0x7b, 0x96, 0x8b, 0x0d, 0x8e, 0x28, 0xdf, 0xa6, 0x1e, 0xf6, 0xff, 0x55, 0xf1,
	0xc4, 0x5b, 0x94, 0x1f, 0xda, 0x82, 0x35, 0x0b, 0x0d, 0xa8, 0x15, 0xb5, 0x6e, 0xce, 0x88, 0x04,
	0x54, 0x87, 0x8c, 0x6f, 0x13, 0xb9, 0x56, 0xcd, 0xfc, 0x62, 0x37, 0x30, 0x43, 0xe5, 0x14, 0x9e,
	0xab, 0x96, 0xef, 0x78, 0xec, 0xa1, 0x8d, 0x72, 0xe8, 0x9c, 0x5b, 0xe3, 0x19, 0x66, 0x33, 0x2c,
	0x9a, 0x30, 0xa2, 0x03, 0x84, 0xc4, 0x1e, 0x06, 0x3b, 0x76, 0x10, 0xcd, 0x7d, 0xab, 0x50, 0xfa,
	0xf0, 0x74, 0xf1, 0xc5, 0x7f, 0x9c, 0xea, 0x0d, 0xe4, 0x08, 0x8d, 0x69, 0xd6, 0x1b, 0x52, 0x9d,
	0x8d, 0xdd, 0xe8, 0xfd, 0xe7, 0x24, 0x46, 0x04, 0x2b, 0x26, 0x20, 0xd3, 0xb3, 0xaf, 0x30, 0xbd,
	0x1f, 0x20, 0xe5, 0xda, 0x98, 0x35, 0x92, 0x58, 0x5e, 0x82, 0xb9, 0x8f, 0x43, 0x11, 0x5c, 0x24,
	0x20, 0x09, 0x32, 0xb6, 0x35, 0x15, 0xcf, 0x1c, 0x5b, 0x2a, 0x9f, 0x61, 0x2b, 0x62, 0xd5, 0xfe,
	0x3b, 0xf5, 0xc2, 0xa8, 0x74, 0x6e, 0x7e, 0x0b, 0xf5, 0x26, 0xe4, 0x31, 0xa7, 0x10, 0xe3, 0x51,
	0x48, 0xf1, 0x96, 0xb5, 0xdb, 0x2d, 0xbf, 0x49, 0xc5, 0x7b, 0x2e, 0x4d, 0xd2, 0xd2, 0x3d, 0xeb,
	0x90, 0xff, 0x84, 0x47, 0x41, 0x18, 0x67, 0x69, 0x93, 0x67, 0xa9, 0x17, 0x8c, 0x3d, 0xfb, 0x26,
	0xe1, 0x72, 0xb1, 0x21, 0xac, 0xd0, 0x9f, 0x60, 0xd5, 0x9e, 0x85, 0x21, 0xf6, 0xa3, 0x07, 0xe2,
	0x61, 0x87, 0xd8, 0x6c, 0x49, 0x9c, 0x5f, 0xa7, 0x00, 0xdd, 0x19, 0xe0, 0x51, 0x88, 0xcb, 0x9e,
	0xc4, 0xc5, 0xd9, 0x53, 0xbe, 0x37, 0x7b, 0xf6, 0xe3, 0xfb, 0x8d, 0x02, 0xd9, 0xaa, 0x27, 0x9f,
	0x50, 0x77, 0xc8, 0xc5, 0x35, 0xb3, 0x01, 0x48, 0xa8, 0x15, 0xd2, 0x66, 0x34, 0x4b, 0x33, 0x46,
	0x2c, 0xb2, 0xbc, 0x63, 0xdf, 0x69, 0x46, 0x33, 0x3f, 0x63, 0x44, 0x82, 0xf2, 0x11, 0xb6, 0x1e,
	0xf8, 0xca, 0x10, 0xdd, 0x0c, 0xc9, 0x63, 0xbe, 0x0f, 0x99, 0x39, 0xb9, 0xe6, 0x63, 0xa5, 0xd4,
	0x78, 0xb1, 0xfc, 0x23, 0x85, 0x9f, 0xd1, 0x60, 0x76, 0x7b, 0x3f, 0xa5, 0xa1, 0x98, 0xbc, 0xe8,
	0x68, 0x13, 0xd0, 0x99, 0xfe, 0x41, 0xef, 0x0e, 0xf4, 0xa1, 0x76, 0xae, 0xe9, 0xe6, 0xd0, 0xbc,
	0xe8, 0x69, 0xd2, 0x0a, 0xda, 0x86, 0xe7, 0x2d, 0xed, 0xbc, 0xad, 0x6a, 0x43, 0xb5, 0xab, 0x1f,
	0xb5, 0x8f, 0x87, 0x67, 0xbd, 0x56, 0xd3, 0xd4, 0x5a, 0x52, 0x0a, 0xbd, 0x84, 0x6d, 0x01, 0x19,
	0xcd, 0x41, 0x0c, 0xf7, 0x2f, 0x74, 0xb5, 0xad, 0x1f, 0x4b, 0x69, 0xb4, 0x03, 0xf2, 0x72, 0x58,
	0x6b, 0x49, 0x19, 0xf4, 0x1a, 0x5e, 0x0a, 0xb4, 0x7b, 0xf8, 0x2f, 0x4d, 0x35, 0x63, 0x83, 0xa6,
	0xde, 0xec, 0x5c, 0xf4, 0xb5, 0x96, 0x94, 0x45, 0x32, 0x94, 0x85, 0x49, 0xdf, 0x6c, 0x9a, 0xda,
	0x50, 0x3d, 0x69, 0xea, 0xc7, 0x5a, 0x4b, 0xca, 0x2d, 0x50, 0xab, 0x4d, 0xbd, 0xd5, 0x6e, 0x71,
	0xd4, 0xd0, 0x78, 0x5c, 0x79, 0xf4, 0x14, 0xd6, 0x04, 0xda, 0xd2, 0x3a, 0x9a, 0xa9, 0x49, 0xab,
	0x08, 0xc1, 0xba, 0xd9, 0x56, 0x3f, 0x68, 0x66, 0x62, 0x56, 0x60, 0xf4, 0x42, 0x77, 0x97, 0xbe,
	0x88, 0xb6, 0xe0, 0x99, 0x40, 0x06, 0xed, 0x4e, 0x67, 0xa8, 0x7d, 0xec, 0xb5, 0x0d, 0xad, 0x25,
	0x01, 0x63, 0x6e, 0xaa, 0x66, 0xfb, 0xbc, 0x6d, 0x5e, 0x0c, 0x8f, 0x9a, 0xed, 0x8e, 0x54, 0x42,
	0x15, 0xd8, 0x1c, 0x74, 0x8d, 0x0f, 0x47, 0x9d, 0xee, 0xe0, 0x1e, 0xcf, 0x93, 0xbd, 0xff, 0xc1,
	0xd6, 0x03, 0x83, 0x10, 0xfd, 0x0e, 0x5e, 0xc7, 0xe9, 0xd6, 0xbb, 0x66, 0xfb, 0xa8, 0xad, 0x36,
	0xcd, 0x76, 0x57, 0xe7, 0xce, 0xba, 0xd6, 0x89, 0xb3, 0x5f, 0x84, 0x9c, 0x76, 0xca, 0x36, 0x02,
	0xb6, 0xec, 0x9d, 0x74, 0x75, 0x4d, 0x2a, 0xa3, 0x35, 0x28, 0x0e, 0xb4, 0xc3, 0x7e, 0x97, 0x85,
	0x28, 0xed, 0xa2, 0x32, 0x48, 0xc7, 0x67, 0xdd, 0xbe, 0xa6, 0x0f, 0x7b, 0x67, 0xfd, 0x93, 0x61,
	0xf7, 0x5c, 0x33, 0xa4, 0xda, 0xde, 0x3f, 0x61, 0xed, 0xce, 0x47, 0x18, 0x33, 0x8b, 0xb7, 0xec,
	0x19, 0x5d, 0xb3, 0xab, 0x76, 0x3b, 0xd2, 0x0a, 0x2a, 0x40, 0xb6, 0x7f, 0x6a, 0xf6, 0x24, 0x40,
	0x1b, 0x50, 0xea, 0x6b, 0xea, 0x99, 0xa1, 0x0d, 0xb9, 0xa2, 0x7c, 0x78, 0x0c, 0x15, 0x1f, 0xd3,
	0x3a, 0xb9, 0xba, 0xb1, 0xc7, 0xc1, 0xcc, 0x89, 0xfe, 0x12, 0xc4, 0x65, 0xf5, 0x9f, 0x3f, 0xb8,
	0x1e, 0xbd, 0x9c, 0x7d, 0x62, 0x6f, 0xf6, 0x01, 0xb9, 0xba, 0xd9, 0xe7, 0x36, 0xfb, 0x14, 0xdb,
	0x07, 0xdc, 0xee, 0xe0, 0xfa, 0xcf, 0xf1, 0x3f, 0x92, 0x4f, 0x79, 0xae, 0xf9, 0xcb, 0xcf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x9f, 0xc2, 0x90, 0x4e, 0xab, 0x0c, 0x00, 0x00,
}
