// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eventti/eventti.proto

package eventti

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/sky-cloud-tec/proto/v1/common"
	nap "github.com/sky-cloud-tec/proto/v1/nap"
	workflow "github.com/sky-cloud-tec/proto/v1/workflow"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_UNKNOWN_EVENT_TYPE            EventType = 0
	EventType_DEVICE_CONFIG_UPDATED         EventType = 1
	EventType_DEVICE_RAW_CONFIG_SYNCING     EventType = 2
	EventType_DEVICE_RAW_CONFIG_SYNCED      EventType = 3
	EventType_DEVICE_OBJECT_CONFIG_ANALYSED EventType = 4
	EventType_DEVICE_STATE_CHANGED          EventType = 5
	EventType_DEVICE_CANDIDATE_CREATED      EventType = 6
	EventType_DEVICE_DELETE                 EventType = 7
	EventType_TICKET_CREATED                EventType = 8
	EventType_TICKET_STATE_CHANGED          EventType = 9
	EventType_TICKET_WILL_EXPIRED           EventType = 10
	EventType_ACTIVITY_FAIL                 EventType = 11
	EventType_WORKFLOW_STATE_CHANGED        EventType = 12
	EventType_WORKFLOW_STAGE_STATE_CHANGED  EventType = 13
)

var EventType_name = map[int32]string{
	0:  "UNKNOWN_EVENT_TYPE",
	1:  "DEVICE_CONFIG_UPDATED",
	2:  "DEVICE_RAW_CONFIG_SYNCING",
	3:  "DEVICE_RAW_CONFIG_SYNCED",
	4:  "DEVICE_OBJECT_CONFIG_ANALYSED",
	5:  "DEVICE_STATE_CHANGED",
	6:  "DEVICE_CANDIDATE_CREATED",
	7:  "DEVICE_DELETE",
	8:  "TICKET_CREATED",
	9:  "TICKET_STATE_CHANGED",
	10: "TICKET_WILL_EXPIRED",
	11: "ACTIVITY_FAIL",
	12: "WORKFLOW_STATE_CHANGED",
	13: "WORKFLOW_STAGE_STATE_CHANGED",
}

var EventType_value = map[string]int32{
	"UNKNOWN_EVENT_TYPE":            0,
	"DEVICE_CONFIG_UPDATED":         1,
	"DEVICE_RAW_CONFIG_SYNCING":     2,
	"DEVICE_RAW_CONFIG_SYNCED":      3,
	"DEVICE_OBJECT_CONFIG_ANALYSED": 4,
	"DEVICE_STATE_CHANGED":          5,
	"DEVICE_CANDIDATE_CREATED":      6,
	"DEVICE_DELETE":                 7,
	"TICKET_CREATED":                8,
	"TICKET_STATE_CHANGED":          9,
	"TICKET_WILL_EXPIRED":           10,
	"ACTIVITY_FAIL":                 11,
	"WORKFLOW_STATE_CHANGED":        12,
	"WORKFLOW_STAGE_STATE_CHANGED":  13,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{0}
}

type NotificationChannelType int32

const (
	NotificationChannelType_UNKNOWN_NOTIFICATION_CHANNEL_TYPE NotificationChannelType = 0
	NotificationChannelType_EMAIL                             NotificationChannelType = 10
	NotificationChannelType_PHONE                             NotificationChannelType = 20
	NotificationChannelType_WEBSOCKET                         NotificationChannelType = 30
	NotificationChannelType_GUOSEN_PUSH_OVER                  NotificationChannelType = 40
)

var NotificationChannelType_name = map[int32]string{
	0:  "UNKNOWN_NOTIFICATION_CHANNEL_TYPE",
	10: "EMAIL",
	20: "PHONE",
	30: "WEBSOCKET",
	40: "GUOSEN_PUSH_OVER",
}

var NotificationChannelType_value = map[string]int32{
	"UNKNOWN_NOTIFICATION_CHANNEL_TYPE": 0,
	"EMAIL":                             10,
	"PHONE":                             20,
	"WEBSOCKET":                         30,
	"GUOSEN_PUSH_OVER":                  40,
}

func (x NotificationChannelType) String() string {
	return proto.EnumName(NotificationChannelType_name, int32(x))
}

func (NotificationChannelType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{1}
}

type EmailProtocol int32

const (
	EmailProtocol_UNKNOWN_PROTOCOL EmailProtocol = 0
	EmailProtocol_SMTP             EmailProtocol = 10
	EmailProtocol_SECURE_SMTP      EmailProtocol = 20
)

var EmailProtocol_name = map[int32]string{
	0:  "UNKNOWN_PROTOCOL",
	10: "SMTP",
	20: "SECURE_SMTP",
}

var EmailProtocol_value = map[string]int32{
	"UNKNOWN_PROTOCOL": 0,
	"SMTP":             10,
	"SECURE_SMTP":      20,
}

func (x EmailProtocol) String() string {
	return proto.EnumName(EmailProtocol_name, int32(x))
}

func (EmailProtocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{2}
}

type From struct {
	Host                 string   `protobuf:"bytes,10,opt,name=host,proto3" json:"host,omitempty"`
	Module               string   `protobuf:"bytes,20,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *From) Reset()         { *m = From{} }
func (m *From) String() string { return proto.CompactTextString(m) }
func (*From) ProtoMessage()    {}
func (*From) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{0}
}

func (m *From) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_From.Unmarshal(m, b)
}
func (m *From) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_From.Marshal(b, m, deterministic)
}
func (m *From) XXX_Merge(src proto.Message) {
	xxx_messageInfo_From.Merge(m, src)
}
func (m *From) XXX_Size() int {
	return xxx_messageInfo_From.Size(m)
}
func (m *From) XXX_DiscardUnknown() {
	xxx_messageInfo_From.DiscardUnknown(m)
}

var xxx_messageInfo_From proto.InternalMessageInfo

func (m *From) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *From) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

type DeviceConfigUpdatedMsg struct {
	DeviceId             string   `protobuf:"bytes,10,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName           string   `protobuf:"bytes,20,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	Message              string   `protobuf:"bytes,30,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceConfigUpdatedMsg) Reset()         { *m = DeviceConfigUpdatedMsg{} }
func (m *DeviceConfigUpdatedMsg) String() string { return proto.CompactTextString(m) }
func (*DeviceConfigUpdatedMsg) ProtoMessage()    {}
func (*DeviceConfigUpdatedMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{1}
}

func (m *DeviceConfigUpdatedMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceConfigUpdatedMsg.Unmarshal(m, b)
}
func (m *DeviceConfigUpdatedMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceConfigUpdatedMsg.Marshal(b, m, deterministic)
}
func (m *DeviceConfigUpdatedMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceConfigUpdatedMsg.Merge(m, src)
}
func (m *DeviceConfigUpdatedMsg) XXX_Size() int {
	return xxx_messageInfo_DeviceConfigUpdatedMsg.Size(m)
}
func (m *DeviceConfigUpdatedMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceConfigUpdatedMsg.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceConfigUpdatedMsg proto.InternalMessageInfo

func (m *DeviceConfigUpdatedMsg) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeviceConfigUpdatedMsg) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *DeviceConfigUpdatedMsg) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Event struct {
	Id        string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type      EventType `protobuf:"varint,20,opt,name=type,proto3,enum=eventti.EventType" json:"type,omitempty"`
	Timestamp int64     `protobuf:"varint,30,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Metadata:
	//	*Event_Wscm
	//	*Event_Dcum
	//	*Event_Wsscm
	Metadata             isEvent_Metadata `protobuf_oneof:"metadata"`
	Target               *Target          `protobuf:"bytes,50,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{2}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_UNKNOWN_EVENT_TYPE
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type isEvent_Metadata interface {
	isEvent_Metadata()
}

type Event_Wscm struct {
	Wscm *WorkflowStateChangedMsg `protobuf:"bytes,210,opt,name=wscm,proto3,oneof"`
}

type Event_Dcum struct {
	Dcum *DeviceConfigUpdatedMsg `protobuf:"bytes,220,opt,name=dcum,proto3,oneof"`
}

type Event_Wsscm struct {
	Wsscm *WorkflowStageStateChangedMsg `protobuf:"bytes,230,opt,name=wsscm,proto3,oneof"`
}

func (*Event_Wscm) isEvent_Metadata() {}

func (*Event_Dcum) isEvent_Metadata() {}

func (*Event_Wsscm) isEvent_Metadata() {}

func (m *Event) GetMetadata() isEvent_Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Event) GetWscm() *WorkflowStateChangedMsg {
	if x, ok := m.GetMetadata().(*Event_Wscm); ok {
		return x.Wscm
	}
	return nil
}

func (m *Event) GetDcum() *DeviceConfigUpdatedMsg {
	if x, ok := m.GetMetadata().(*Event_Dcum); ok {
		return x.Dcum
	}
	return nil
}

func (m *Event) GetWsscm() *WorkflowStageStateChangedMsg {
	if x, ok := m.GetMetadata().(*Event_Wsscm); ok {
		return x.Wsscm
	}
	return nil
}

func (m *Event) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Event) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Event_Wscm)(nil),
		(*Event_Dcum)(nil),
		(*Event_Wsscm)(nil),
	}
}

type EmailServerCfg struct {
	Account              string        `protobuf:"bytes,10,opt,name=account,proto3" json:"account,omitempty"`
	Password             string        `protobuf:"bytes,20,opt,name=password,proto3" json:"password,omitempty"`
	Host                 string        `protobuf:"bytes,30,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32         `protobuf:"varint,40,opt,name=port,proto3" json:"port,omitempty"`
	Protocol             EmailProtocol `protobuf:"varint,50,opt,name=protocol,proto3,enum=eventti.EmailProtocol" json:"protocol,omitempty"`
	Timeout              int32         `protobuf:"varint,60,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *EmailServerCfg) Reset()         { *m = EmailServerCfg{} }
func (m *EmailServerCfg) String() string { return proto.CompactTextString(m) }
func (*EmailServerCfg) ProtoMessage()    {}
func (*EmailServerCfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{3}
}

func (m *EmailServerCfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailServerCfg.Unmarshal(m, b)
}
func (m *EmailServerCfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailServerCfg.Marshal(b, m, deterministic)
}
func (m *EmailServerCfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailServerCfg.Merge(m, src)
}
func (m *EmailServerCfg) XXX_Size() int {
	return xxx_messageInfo_EmailServerCfg.Size(m)
}
func (m *EmailServerCfg) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailServerCfg.DiscardUnknown(m)
}

var xxx_messageInfo_EmailServerCfg proto.InternalMessageInfo

func (m *EmailServerCfg) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *EmailServerCfg) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *EmailServerCfg) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *EmailServerCfg) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *EmailServerCfg) GetProtocol() EmailProtocol {
	if m != nil {
		return m.Protocol
	}
	return EmailProtocol_UNKNOWN_PROTOCOL
}

func (m *EmailServerCfg) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type SmsCfg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsCfg) Reset()         { *m = SmsCfg{} }
func (m *SmsCfg) String() string { return proto.CompactTextString(m) }
func (*SmsCfg) ProtoMessage()    {}
func (*SmsCfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{4}
}

func (m *SmsCfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsCfg.Unmarshal(m, b)
}
func (m *SmsCfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsCfg.Marshal(b, m, deterministic)
}
func (m *SmsCfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsCfg.Merge(m, src)
}
func (m *SmsCfg) XXX_Size() int {
	return xxx_messageInfo_SmsCfg.Size(m)
}
func (m *SmsCfg) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsCfg.DiscardUnknown(m)
}

var xxx_messageInfo_SmsCfg proto.InternalMessageInfo

type GuosenPushOverCfg struct {
	Username             string   `protobuf:"bytes,10,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,20,opt,name=password,proto3" json:"password,omitempty"`
	LoginUrl             string   `protobuf:"bytes,30,opt,name=loginUrl,proto3" json:"loginUrl,omitempty"`
	IssuedUrl            string   `protobuf:"bytes,40,opt,name=issuedUrl,proto3" json:"issuedUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GuosenPushOverCfg) Reset()         { *m = GuosenPushOverCfg{} }
func (m *GuosenPushOverCfg) String() string { return proto.CompactTextString(m) }
func (*GuosenPushOverCfg) ProtoMessage()    {}
func (*GuosenPushOverCfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{5}
}

func (m *GuosenPushOverCfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuosenPushOverCfg.Unmarshal(m, b)
}
func (m *GuosenPushOverCfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuosenPushOverCfg.Marshal(b, m, deterministic)
}
func (m *GuosenPushOverCfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuosenPushOverCfg.Merge(m, src)
}
func (m *GuosenPushOverCfg) XXX_Size() int {
	return xxx_messageInfo_GuosenPushOverCfg.Size(m)
}
func (m *GuosenPushOverCfg) XXX_DiscardUnknown() {
	xxx_messageInfo_GuosenPushOverCfg.DiscardUnknown(m)
}

var xxx_messageInfo_GuosenPushOverCfg proto.InternalMessageInfo

func (m *GuosenPushOverCfg) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GuosenPushOverCfg) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GuosenPushOverCfg) GetLoginUrl() string {
	if m != nil {
		return m.LoginUrl
	}
	return ""
}

func (m *GuosenPushOverCfg) GetIssuedUrl() string {
	if m != nil {
		return m.IssuedUrl
	}
	return ""
}

type WSServerCfg struct {
	Port                 string   `protobuf:"bytes,10,opt,name=port,proto3" json:"port,omitempty"`
	Path                 string   `protobuf:"bytes,20,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WSServerCfg) Reset()         { *m = WSServerCfg{} }
func (m *WSServerCfg) String() string { return proto.CompactTextString(m) }
func (*WSServerCfg) ProtoMessage()    {}
func (*WSServerCfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{6}
}

func (m *WSServerCfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WSServerCfg.Unmarshal(m, b)
}
func (m *WSServerCfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WSServerCfg.Marshal(b, m, deterministic)
}
func (m *WSServerCfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WSServerCfg.Merge(m, src)
}
func (m *WSServerCfg) XXX_Size() int {
	return xxx_messageInfo_WSServerCfg.Size(m)
}
func (m *WSServerCfg) XXX_DiscardUnknown() {
	xxx_messageInfo_WSServerCfg.DiscardUnknown(m)
}

var xxx_messageInfo_WSServerCfg proto.InternalMessageInfo

func (m *WSServerCfg) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *WSServerCfg) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Target struct {
	Users                []string `protobuf:"bytes,10,rep,name=users,proto3" json:"users,omitempty"`
	Roles                []string `protobuf:"bytes,20,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}
func (*Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{7}
}

func (m *Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target.Unmarshal(m, b)
}
func (m *Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target.Marshal(b, m, deterministic)
}
func (m *Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target.Merge(m, src)
}
func (m *Target) XXX_Size() int {
	return xxx_messageInfo_Target.Size(m)
}
func (m *Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Target proto.InternalMessageInfo

func (m *Target) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Target) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type CreateNotificationChannelReq struct {
	Nc                   *NotificationChannel `protobuf:"bytes,10,opt,name=nc,proto3" json:"nc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateNotificationChannelReq) Reset()         { *m = CreateNotificationChannelReq{} }
func (m *CreateNotificationChannelReq) String() string { return proto.CompactTextString(m) }
func (*CreateNotificationChannelReq) ProtoMessage()    {}
func (*CreateNotificationChannelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{8}
}

func (m *CreateNotificationChannelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNotificationChannelReq.Unmarshal(m, b)
}
func (m *CreateNotificationChannelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNotificationChannelReq.Marshal(b, m, deterministic)
}
func (m *CreateNotificationChannelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNotificationChannelReq.Merge(m, src)
}
func (m *CreateNotificationChannelReq) XXX_Size() int {
	return xxx_messageInfo_CreateNotificationChannelReq.Size(m)
}
func (m *CreateNotificationChannelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNotificationChannelReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNotificationChannelReq proto.InternalMessageInfo

func (m *CreateNotificationChannelReq) GetNc() *NotificationChannel {
	if m != nil {
		return m.Nc
	}
	return nil
}

type NotificationChannel struct {
	Id          string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                  `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Etypes      []EventType             `protobuf:"varint,15,rep,packed,name=etypes,proto3,enum=eventti.EventType" json:"etypes,omitempty"`
	Type        NotificationChannelType `protobuf:"varint,20,opt,name=type,proto3,enum=eventti.NotificationChannelType" json:"type,omitempty"`
	Description string                  `protobuf:"bytes,25,opt,name=description,proto3" json:"description,omitempty"`
	Target      *Target                 `protobuf:"bytes,30,opt,name=target,proto3" json:"target,omitempty"`
	// Types that are valid to be assigned to Cfg:
	//	*NotificationChannel_EmailServerCfg
	//	*NotificationChannel_SmsCfg
	//	*NotificationChannel_GpoCfg
	//	*NotificationChannel_WsServerCfg
	Cfg                  isNotificationChannel_Cfg `protobuf_oneof:"cfg"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *NotificationChannel) Reset()         { *m = NotificationChannel{} }
func (m *NotificationChannel) String() string { return proto.CompactTextString(m) }
func (*NotificationChannel) ProtoMessage()    {}
func (*NotificationChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{9}
}

func (m *NotificationChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationChannel.Unmarshal(m, b)
}
func (m *NotificationChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationChannel.Marshal(b, m, deterministic)
}
func (m *NotificationChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationChannel.Merge(m, src)
}
func (m *NotificationChannel) XXX_Size() int {
	return xxx_messageInfo_NotificationChannel.Size(m)
}
func (m *NotificationChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationChannel.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationChannel proto.InternalMessageInfo

func (m *NotificationChannel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NotificationChannel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NotificationChannel) GetEtypes() []EventType {
	if m != nil {
		return m.Etypes
	}
	return nil
}

func (m *NotificationChannel) GetType() NotificationChannelType {
	if m != nil {
		return m.Type
	}
	return NotificationChannelType_UNKNOWN_NOTIFICATION_CHANNEL_TYPE
}

func (m *NotificationChannel) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NotificationChannel) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

type isNotificationChannel_Cfg interface {
	isNotificationChannel_Cfg()
}

type NotificationChannel_EmailServerCfg struct {
	EmailServerCfg *EmailServerCfg `protobuf:"bytes,40,opt,name=email_server_cfg,json=emailServerCfg,proto3,oneof"`
}

type NotificationChannel_SmsCfg struct {
	SmsCfg *SmsCfg `protobuf:"bytes,50,opt,name=sms_cfg,json=smsCfg,proto3,oneof"`
}

type NotificationChannel_GpoCfg struct {
	GpoCfg *GuosenPushOverCfg `protobuf:"bytes,60,opt,name=gpo_cfg,json=gpoCfg,proto3,oneof"`
}

type NotificationChannel_WsServerCfg struct {
	WsServerCfg *WSServerCfg `protobuf:"bytes,70,opt,name=ws_server_cfg,json=wsServerCfg,proto3,oneof"`
}

func (*NotificationChannel_EmailServerCfg) isNotificationChannel_Cfg() {}

func (*NotificationChannel_SmsCfg) isNotificationChannel_Cfg() {}

func (*NotificationChannel_GpoCfg) isNotificationChannel_Cfg() {}

func (*NotificationChannel_WsServerCfg) isNotificationChannel_Cfg() {}

func (m *NotificationChannel) GetCfg() isNotificationChannel_Cfg {
	if m != nil {
		return m.Cfg
	}
	return nil
}

func (m *NotificationChannel) GetEmailServerCfg() *EmailServerCfg {
	if x, ok := m.GetCfg().(*NotificationChannel_EmailServerCfg); ok {
		return x.EmailServerCfg
	}
	return nil
}

func (m *NotificationChannel) GetSmsCfg() *SmsCfg {
	if x, ok := m.GetCfg().(*NotificationChannel_SmsCfg); ok {
		return x.SmsCfg
	}
	return nil
}

func (m *NotificationChannel) GetGpoCfg() *GuosenPushOverCfg {
	if x, ok := m.GetCfg().(*NotificationChannel_GpoCfg); ok {
		return x.GpoCfg
	}
	return nil
}

func (m *NotificationChannel) GetWsServerCfg() *WSServerCfg {
	if x, ok := m.GetCfg().(*NotificationChannel_WsServerCfg); ok {
		return x.WsServerCfg
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*NotificationChannel) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*NotificationChannel_EmailServerCfg)(nil),
		(*NotificationChannel_SmsCfg)(nil),
		(*NotificationChannel_GpoCfg)(nil),
		(*NotificationChannel_WsServerCfg)(nil),
	}
}

type CreateNotificationChannelRes struct {
	Ret                  *common.BaseRet `protobuf:"bytes,10,opt,name=ret,proto3" json:"ret,omitempty"`
	Id                   int32           `protobuf:"varint,20,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateNotificationChannelRes) Reset()         { *m = CreateNotificationChannelRes{} }
func (m *CreateNotificationChannelRes) String() string { return proto.CompactTextString(m) }
func (*CreateNotificationChannelRes) ProtoMessage()    {}
func (*CreateNotificationChannelRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{10}
}

func (m *CreateNotificationChannelRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNotificationChannelRes.Unmarshal(m, b)
}
func (m *CreateNotificationChannelRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNotificationChannelRes.Marshal(b, m, deterministic)
}
func (m *CreateNotificationChannelRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNotificationChannelRes.Merge(m, src)
}
func (m *CreateNotificationChannelRes) XXX_Size() int {
	return xxx_messageInfo_CreateNotificationChannelRes.Size(m)
}
func (m *CreateNotificationChannelRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNotificationChannelRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNotificationChannelRes proto.InternalMessageInfo

func (m *CreateNotificationChannelRes) GetRet() *common.BaseRet {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *CreateNotificationChannelRes) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetNotificationChannelReq struct {
	Page                 *common.Page `protobuf:"bytes,10,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetNotificationChannelReq) Reset()         { *m = GetNotificationChannelReq{} }
func (m *GetNotificationChannelReq) String() string { return proto.CompactTextString(m) }
func (*GetNotificationChannelReq) ProtoMessage()    {}
func (*GetNotificationChannelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{11}
}

func (m *GetNotificationChannelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNotificationChannelReq.Unmarshal(m, b)
}
func (m *GetNotificationChannelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNotificationChannelReq.Marshal(b, m, deterministic)
}
func (m *GetNotificationChannelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNotificationChannelReq.Merge(m, src)
}
func (m *GetNotificationChannelReq) XXX_Size() int {
	return xxx_messageInfo_GetNotificationChannelReq.Size(m)
}
func (m *GetNotificationChannelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNotificationChannelReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetNotificationChannelReq proto.InternalMessageInfo

func (m *GetNotificationChannelReq) GetPage() *common.Page {
	if m != nil {
		return m.Page
	}
	return nil
}

type GetNotificationChannelRes struct {
	Ret                  *common.BaseRet        `protobuf:"bytes,10,opt,name=ret,proto3" json:"ret,omitempty"`
	Page                 *common.Page           `protobuf:"bytes,20,opt,name=page,proto3" json:"page,omitempty"`
	Total                int32                  `protobuf:"varint,30,opt,name=total,proto3" json:"total,omitempty"`
	Ncs                  []*NotificationChannel `protobuf:"bytes,40,rep,name=ncs,proto3" json:"ncs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetNotificationChannelRes) Reset()         { *m = GetNotificationChannelRes{} }
func (m *GetNotificationChannelRes) String() string { return proto.CompactTextString(m) }
func (*GetNotificationChannelRes) ProtoMessage()    {}
func (*GetNotificationChannelRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{12}
}

func (m *GetNotificationChannelRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNotificationChannelRes.Unmarshal(m, b)
}
func (m *GetNotificationChannelRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNotificationChannelRes.Marshal(b, m, deterministic)
}
func (m *GetNotificationChannelRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNotificationChannelRes.Merge(m, src)
}
func (m *GetNotificationChannelRes) XXX_Size() int {
	return xxx_messageInfo_GetNotificationChannelRes.Size(m)
}
func (m *GetNotificationChannelRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNotificationChannelRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetNotificationChannelRes proto.InternalMessageInfo

func (m *GetNotificationChannelRes) GetRet() *common.BaseRet {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *GetNotificationChannelRes) GetPage() *common.Page {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *GetNotificationChannelRes) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetNotificationChannelRes) GetNcs() []*NotificationChannel {
	if m != nil {
		return m.Ncs
	}
	return nil
}

type CandidateCreatedValue struct {
	Device               string   `protobuf:"bytes,10,opt,name=device,proto3" json:"device,omitempty"`
	Candidate            string   `protobuf:"bytes,20,opt,name=candidate,proto3" json:"candidate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CandidateCreatedValue) Reset()         { *m = CandidateCreatedValue{} }
func (m *CandidateCreatedValue) String() string { return proto.CompactTextString(m) }
func (*CandidateCreatedValue) ProtoMessage()    {}
func (*CandidateCreatedValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{13}
}

func (m *CandidateCreatedValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidateCreatedValue.Unmarshal(m, b)
}
func (m *CandidateCreatedValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidateCreatedValue.Marshal(b, m, deterministic)
}
func (m *CandidateCreatedValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidateCreatedValue.Merge(m, src)
}
func (m *CandidateCreatedValue) XXX_Size() int {
	return xxx_messageInfo_CandidateCreatedValue.Size(m)
}
func (m *CandidateCreatedValue) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidateCreatedValue.DiscardUnknown(m)
}

var xxx_messageInfo_CandidateCreatedValue proto.InternalMessageInfo

func (m *CandidateCreatedValue) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *CandidateCreatedValue) GetCandidate() string {
	if m != nil {
		return m.Candidate
	}
	return ""
}

type StateChangedValue struct {
	Device               string          `protobuf:"bytes,10,opt,name=device,proto3" json:"device,omitempty"`
	State                nap.DeviceState `protobuf:"varint,20,opt,name=state,proto3,enum=nap.DeviceState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StateChangedValue) Reset()         { *m = StateChangedValue{} }
func (m *StateChangedValue) String() string { return proto.CompactTextString(m) }
func (*StateChangedValue) ProtoMessage()    {}
func (*StateChangedValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{14}
}

func (m *StateChangedValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateChangedValue.Unmarshal(m, b)
}
func (m *StateChangedValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateChangedValue.Marshal(b, m, deterministic)
}
func (m *StateChangedValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateChangedValue.Merge(m, src)
}
func (m *StateChangedValue) XXX_Size() int {
	return xxx_messageInfo_StateChangedValue.Size(m)
}
func (m *StateChangedValue) XXX_DiscardUnknown() {
	xxx_messageInfo_StateChangedValue.DiscardUnknown(m)
}

var xxx_messageInfo_StateChangedValue proto.InternalMessageInfo

func (m *StateChangedValue) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *StateChangedValue) GetState() nap.DeviceState {
	if m != nil {
		return m.State
	}
	return nap.DeviceState_UNKNOWN_DEVICE_STATE
}

type TicketCreatedValue struct {
	Ticket               string   `protobuf:"bytes,10,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Owner                string   `protobuf:"bytes,20,opt,name=owner,proto3" json:"owner,omitempty"`
	Cap                  string   `protobuf:"bytes,30,opt,name=cap,proto3" json:"cap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TicketCreatedValue) Reset()         { *m = TicketCreatedValue{} }
func (m *TicketCreatedValue) String() string { return proto.CompactTextString(m) }
func (*TicketCreatedValue) ProtoMessage()    {}
func (*TicketCreatedValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{15}
}

func (m *TicketCreatedValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketCreatedValue.Unmarshal(m, b)
}
func (m *TicketCreatedValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketCreatedValue.Marshal(b, m, deterministic)
}
func (m *TicketCreatedValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketCreatedValue.Merge(m, src)
}
func (m *TicketCreatedValue) XXX_Size() int {
	return xxx_messageInfo_TicketCreatedValue.Size(m)
}
func (m *TicketCreatedValue) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketCreatedValue.DiscardUnknown(m)
}

var xxx_messageInfo_TicketCreatedValue proto.InternalMessageInfo

func (m *TicketCreatedValue) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *TicketCreatedValue) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *TicketCreatedValue) GetCap() string {
	if m != nil {
		return m.Cap
	}
	return ""
}

type TicketExpireNotifyValue struct {
	Ticket               string   `protobuf:"bytes,10,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Owner                string   `protobuf:"bytes,20,opt,name=owner,proto3" json:"owner,omitempty"`
	Expire               int64    `protobuf:"varint,30,opt,name=expire,proto3" json:"expire,omitempty"`
	Cap                  string   `protobuf:"bytes,40,opt,name=cap,proto3" json:"cap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TicketExpireNotifyValue) Reset()         { *m = TicketExpireNotifyValue{} }
func (m *TicketExpireNotifyValue) String() string { return proto.CompactTextString(m) }
func (*TicketExpireNotifyValue) ProtoMessage()    {}
func (*TicketExpireNotifyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{16}
}

func (m *TicketExpireNotifyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketExpireNotifyValue.Unmarshal(m, b)
}
func (m *TicketExpireNotifyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketExpireNotifyValue.Marshal(b, m, deterministic)
}
func (m *TicketExpireNotifyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketExpireNotifyValue.Merge(m, src)
}
func (m *TicketExpireNotifyValue) XXX_Size() int {
	return xxx_messageInfo_TicketExpireNotifyValue.Size(m)
}
func (m *TicketExpireNotifyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketExpireNotifyValue.DiscardUnknown(m)
}

var xxx_messageInfo_TicketExpireNotifyValue proto.InternalMessageInfo

func (m *TicketExpireNotifyValue) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *TicketExpireNotifyValue) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *TicketExpireNotifyValue) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

func (m *TicketExpireNotifyValue) GetCap() string {
	if m != nil {
		return m.Cap
	}
	return ""
}

type TicketStateChangedValue struct {
	Ticket               string                `protobuf:"bytes,10,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Before               nap.PolicyTicketStage `protobuf:"varint,20,opt,name=before,proto3,enum=nap.PolicyTicketStage" json:"before,omitempty"`
	Current              nap.PolicyTicketStage `protobuf:"varint,30,opt,name=current,proto3,enum=nap.PolicyTicketStage" json:"current,omitempty"`
	Cap                  string                `protobuf:"bytes,40,opt,name=cap,proto3" json:"cap,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TicketStateChangedValue) Reset()         { *m = TicketStateChangedValue{} }
func (m *TicketStateChangedValue) String() string { return proto.CompactTextString(m) }
func (*TicketStateChangedValue) ProtoMessage()    {}
func (*TicketStateChangedValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{17}
}

func (m *TicketStateChangedValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketStateChangedValue.Unmarshal(m, b)
}
func (m *TicketStateChangedValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketStateChangedValue.Marshal(b, m, deterministic)
}
func (m *TicketStateChangedValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketStateChangedValue.Merge(m, src)
}
func (m *TicketStateChangedValue) XXX_Size() int {
	return xxx_messageInfo_TicketStateChangedValue.Size(m)
}
func (m *TicketStateChangedValue) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketStateChangedValue.DiscardUnknown(m)
}

var xxx_messageInfo_TicketStateChangedValue proto.InternalMessageInfo

func (m *TicketStateChangedValue) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *TicketStateChangedValue) GetBefore() nap.PolicyTicketStage {
	if m != nil {
		return m.Before
	}
	return nap.PolicyTicketStage_UNKNOWN_POLICY_TICKET_STAGE
}

func (m *TicketStateChangedValue) GetCurrent() nap.PolicyTicketStage {
	if m != nil {
		return m.Current
	}
	return nap.PolicyTicketStage_UNKNOWN_POLICY_TICKET_STAGE
}

func (m *TicketStateChangedValue) GetCap() string {
	if m != nil {
		return m.Cap
	}
	return ""
}

type WorkflowStateValue struct {
	Name                 string                 `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Username             string                 `protobuf:"bytes,20,opt,name=username,proto3" json:"username,omitempty"`
	State                workflow.WorkflowState `protobuf:"varint,30,opt,name=state,proto3,enum=workflow.WorkflowState" json:"state,omitempty"`
	StartAt              int64                  `protobuf:"varint,40,opt,name=startAt,proto3" json:"startAt,omitempty"`
	EndAt                int64                  `protobuf:"varint,50,opt,name=endAt,proto3" json:"endAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *WorkflowStateValue) Reset()         { *m = WorkflowStateValue{} }
func (m *WorkflowStateValue) String() string { return proto.CompactTextString(m) }
func (*WorkflowStateValue) ProtoMessage()    {}
func (*WorkflowStateValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{18}
}

func (m *WorkflowStateValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowStateValue.Unmarshal(m, b)
}
func (m *WorkflowStateValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowStateValue.Marshal(b, m, deterministic)
}
func (m *WorkflowStateValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowStateValue.Merge(m, src)
}
func (m *WorkflowStateValue) XXX_Size() int {
	return xxx_messageInfo_WorkflowStateValue.Size(m)
}
func (m *WorkflowStateValue) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowStateValue.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowStateValue proto.InternalMessageInfo

func (m *WorkflowStateValue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WorkflowStateValue) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *WorkflowStateValue) GetState() workflow.WorkflowState {
	if m != nil {
		return m.State
	}
	return workflow.WorkflowState_UNKNOWN_WORKFLOW_STATE
}

func (m *WorkflowStateValue) GetStartAt() int64 {
	if m != nil {
		return m.StartAt
	}
	return 0
}

func (m *WorkflowStateValue) GetEndAt() int64 {
	if m != nil {
		return m.EndAt
	}
	return 0
}

type WorkflowStateChangedMsg struct {
	Id                   string                `protobuf:"bytes,10,opt,name=id,proto3" json:"id,omitempty"`
	Wsv                  []*WorkflowStateValue `protobuf:"bytes,20,rep,name=wsv,proto3" json:"wsv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *WorkflowStateChangedMsg) Reset()         { *m = WorkflowStateChangedMsg{} }
func (m *WorkflowStateChangedMsg) String() string { return proto.CompactTextString(m) }
func (*WorkflowStateChangedMsg) ProtoMessage()    {}
func (*WorkflowStateChangedMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{19}
}

func (m *WorkflowStateChangedMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowStateChangedMsg.Unmarshal(m, b)
}
func (m *WorkflowStateChangedMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowStateChangedMsg.Marshal(b, m, deterministic)
}
func (m *WorkflowStateChangedMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowStateChangedMsg.Merge(m, src)
}
func (m *WorkflowStateChangedMsg) XXX_Size() int {
	return xxx_messageInfo_WorkflowStateChangedMsg.Size(m)
}
func (m *WorkflowStateChangedMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowStateChangedMsg.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowStateChangedMsg proto.InternalMessageInfo

func (m *WorkflowStateChangedMsg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WorkflowStateChangedMsg) GetWsv() []*WorkflowStateValue {
	if m != nil {
		return m.Wsv
	}
	return nil
}

type WorkflowPodStateValue struct {
	Name                 string                 `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	State                workflow.WorkflowState `protobuf:"varint,20,opt,name=state,proto3,enum=workflow.WorkflowState" json:"state,omitempty"`
	Spsvs                []*StagePodStateValue  `protobuf:"bytes,30,rep,name=spsvs,proto3" json:"spsvs,omitempty"`
	StartAt              int64                  `protobuf:"varint,40,opt,name=startAt,proto3" json:"startAt,omitempty"`
	EndAt                int64                  `protobuf:"varint,50,opt,name=endAt,proto3" json:"endAt,omitempty"`
	TotalTime            int64                  `protobuf:"varint,60,opt,name=totalTime,proto3" json:"totalTime,omitempty"`
	Message              string                 `protobuf:"bytes,70,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *WorkflowPodStateValue) Reset()         { *m = WorkflowPodStateValue{} }
func (m *WorkflowPodStateValue) String() string { return proto.CompactTextString(m) }
func (*WorkflowPodStateValue) ProtoMessage()    {}
func (*WorkflowPodStateValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{20}
}

func (m *WorkflowPodStateValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowPodStateValue.Unmarshal(m, b)
}
func (m *WorkflowPodStateValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowPodStateValue.Marshal(b, m, deterministic)
}
func (m *WorkflowPodStateValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowPodStateValue.Merge(m, src)
}
func (m *WorkflowPodStateValue) XXX_Size() int {
	return xxx_messageInfo_WorkflowPodStateValue.Size(m)
}
func (m *WorkflowPodStateValue) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowPodStateValue.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowPodStateValue proto.InternalMessageInfo

func (m *WorkflowPodStateValue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WorkflowPodStateValue) GetState() workflow.WorkflowState {
	if m != nil {
		return m.State
	}
	return workflow.WorkflowState_UNKNOWN_WORKFLOW_STATE
}

func (m *WorkflowPodStateValue) GetSpsvs() []*StagePodStateValue {
	if m != nil {
		return m.Spsvs
	}
	return nil
}

func (m *WorkflowPodStateValue) GetStartAt() int64 {
	if m != nil {
		return m.StartAt
	}
	return 0
}

func (m *WorkflowPodStateValue) GetEndAt() int64 {
	if m != nil {
		return m.EndAt
	}
	return 0
}

func (m *WorkflowPodStateValue) GetTotalTime() int64 {
	if m != nil {
		return m.TotalTime
	}
	return 0
}

func (m *WorkflowPodStateValue) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type StagePodStateValue struct {
	StagesName           string                 `protobuf:"bytes,10,opt,name=stagesName,proto3" json:"stagesName,omitempty"`
	State                workflow.WorkflowState `protobuf:"varint,20,opt,name=state,proto3,enum=workflow.WorkflowState" json:"state,omitempty"`
	Name                 string                 `protobuf:"bytes,30,opt,name=name,proto3" json:"name,omitempty"`
	Log                  string                 `protobuf:"bytes,40,opt,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StagePodStateValue) Reset()         { *m = StagePodStateValue{} }
func (m *StagePodStateValue) String() string { return proto.CompactTextString(m) }
func (*StagePodStateValue) ProtoMessage()    {}
func (*StagePodStateValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{21}
}

func (m *StagePodStateValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StagePodStateValue.Unmarshal(m, b)
}
func (m *StagePodStateValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StagePodStateValue.Marshal(b, m, deterministic)
}
func (m *StagePodStateValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StagePodStateValue.Merge(m, src)
}
func (m *StagePodStateValue) XXX_Size() int {
	return xxx_messageInfo_StagePodStateValue.Size(m)
}
func (m *StagePodStateValue) XXX_DiscardUnknown() {
	xxx_messageInfo_StagePodStateValue.DiscardUnknown(m)
}

var xxx_messageInfo_StagePodStateValue proto.InternalMessageInfo

func (m *StagePodStateValue) GetStagesName() string {
	if m != nil {
		return m.StagesName
	}
	return ""
}

func (m *StagePodStateValue) GetState() workflow.WorkflowState {
	if m != nil {
		return m.State
	}
	return workflow.WorkflowState_UNKNOWN_WORKFLOW_STATE
}

func (m *StagePodStateValue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StagePodStateValue) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

type WorkflowStageStateChangedMsg struct {
	Id                   string                   `protobuf:"bytes,10,opt,name=id,proto3" json:"id,omitempty"`
	Wpsvs                []*WorkflowPodStateValue `protobuf:"bytes,20,rep,name=wpsvs,proto3" json:"wpsvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *WorkflowStageStateChangedMsg) Reset()         { *m = WorkflowStageStateChangedMsg{} }
func (m *WorkflowStageStateChangedMsg) String() string { return proto.CompactTextString(m) }
func (*WorkflowStageStateChangedMsg) ProtoMessage()    {}
func (*WorkflowStageStateChangedMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07c6d6f5d02b81b, []int{22}
}

func (m *WorkflowStageStateChangedMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowStageStateChangedMsg.Unmarshal(m, b)
}
func (m *WorkflowStageStateChangedMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowStageStateChangedMsg.Marshal(b, m, deterministic)
}
func (m *WorkflowStageStateChangedMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowStageStateChangedMsg.Merge(m, src)
}
func (m *WorkflowStageStateChangedMsg) XXX_Size() int {
	return xxx_messageInfo_WorkflowStageStateChangedMsg.Size(m)
}
func (m *WorkflowStageStateChangedMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowStageStateChangedMsg.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowStageStateChangedMsg proto.InternalMessageInfo

func (m *WorkflowStageStateChangedMsg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WorkflowStageStateChangedMsg) GetWpsvs() []*WorkflowPodStateValue {
	if m != nil {
		return m.Wpsvs
	}
	return nil
}

func init() {
	proto.RegisterEnum("eventti.EventType", EventType_name, EventType_value)
	proto.RegisterEnum("eventti.NotificationChannelType", NotificationChannelType_name, NotificationChannelType_value)
	proto.RegisterEnum("eventti.EmailProtocol", EmailProtocol_name, EmailProtocol_value)
	proto.RegisterType((*From)(nil), "eventti.From")
	proto.RegisterType((*DeviceConfigUpdatedMsg)(nil), "eventti.DeviceConfigUpdatedMsg")
	proto.RegisterType((*Event)(nil), "eventti.Event")
	proto.RegisterType((*EmailServerCfg)(nil), "eventti.EmailServerCfg")
	proto.RegisterType((*SmsCfg)(nil), "eventti.SmsCfg")
	proto.RegisterType((*GuosenPushOverCfg)(nil), "eventti.GuosenPushOverCfg")
	proto.RegisterType((*WSServerCfg)(nil), "eventti.WSServerCfg")
	proto.RegisterType((*Target)(nil), "eventti.Target")
	proto.RegisterType((*CreateNotificationChannelReq)(nil), "eventti.CreateNotificationChannelReq")
	proto.RegisterType((*NotificationChannel)(nil), "eventti.NotificationChannel")
	proto.RegisterType((*CreateNotificationChannelRes)(nil), "eventti.CreateNotificationChannelRes")
	proto.RegisterType((*GetNotificationChannelReq)(nil), "eventti.GetNotificationChannelReq")
	proto.RegisterType((*GetNotificationChannelRes)(nil), "eventti.GetNotificationChannelRes")
	proto.RegisterType((*CandidateCreatedValue)(nil), "eventti.CandidateCreatedValue")
	proto.RegisterType((*StateChangedValue)(nil), "eventti.StateChangedValue")
	proto.RegisterType((*TicketCreatedValue)(nil), "eventti.TicketCreatedValue")
	proto.RegisterType((*TicketExpireNotifyValue)(nil), "eventti.TicketExpireNotifyValue")
	proto.RegisterType((*TicketStateChangedValue)(nil), "eventti.TicketStateChangedValue")
	proto.RegisterType((*WorkflowStateValue)(nil), "eventti.WorkflowStateValue")
	proto.RegisterType((*WorkflowStateChangedMsg)(nil), "eventti.WorkflowStateChangedMsg")
	proto.RegisterType((*WorkflowPodStateValue)(nil), "eventti.WorkflowPodStateValue")
	proto.RegisterType((*StagePodStateValue)(nil), "eventti.StagePodStateValue")
	proto.RegisterType((*WorkflowStageStateChangedMsg)(nil), "eventti.WorkflowStageStateChangedMsg")
}

func init() {
	proto.RegisterFile("eventti/eventti.proto", fileDescriptor_e07c6d6f5d02b81b)
}

var fileDescriptor_e07c6d6f5d02b81b = []byte{
	// 1617 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0x4b, 0x73, 0xe3, 0x58,
	0x15, 0x8e, 0xe3, 0x47, 0x9c, 0xe3, 0x49, 0x5a, 0x7d, 0xdb, 0x9d, 0xa8, 0x33, 0x99, 0x8c, 0x5b,
	0x55, 0x33, 0x84, 0x14, 0x49, 0x18, 0xd3, 0x03, 0x55, 0xd4, 0x40, 0xe1, 0xc8, 0x4a, 0x62, 0xda,
	0x2d, 0x1b, 0x59, 0x49, 0xa6, 0xd9, 0xb8, 0xd4, 0xd2, 0xb5, 0xa2, 0x8a, 0xf5, 0x18, 0xdd, 0xeb,
	0x98, 0x14, 0x2b, 0x16, 0x2c, 0xf8, 0x1d, 0x14, 0xfc, 0x0a, 0x76, 0xfc, 0x02, 0x58, 0xb3, 0xe6,
	0x1f, 0xb0, 0xa7, 0xee, 0x43, 0xb2, 0x9d, 0x38, 0x69, 0x86, 0x95, 0x75, 0xce, 0x77, 0x5e, 0xf7,
	0x3c, 0xee, 0xb9, 0x86, 0x97, 0xf8, 0x16, 0x47, 0x94, 0x06, 0xc7, 0xf2, 0xf7, 0x28, 0x49, 0x63,
	0x1a, 0xa3, 0x35, 0x49, 0xee, 0xbc, 0x70, 0xe3, 0x30, 0x8c, 0xa3, 0x63, 0xf1, 0x23, 0xd0, 0x9d,
	0x8d, 0xc8, 0x49, 0x8e, 0x23, 0x27, 0x91, 0xe4, 0xf6, 0x34, 0x4e, 0x6f, 0x46, 0xe3, 0x78, 0x7a,
	0x9c, 0x7d, 0x08, 0x40, 0x6b, 0x42, 0xe9, 0x34, 0x8d, 0x43, 0x84, 0xa0, 0x74, 0x1d, 0x13, 0xaa,
	0x42, 0xa3, 0xb0, 0xbf, 0x6e, 0xf1, 0x6f, 0xb4, 0x05, 0x95, 0x30, 0xf6, 0x26, 0x63, 0xac, 0xd6,
	0x39, 0x57, 0x52, 0x5a, 0x02, 0x5b, 0x6d, 0x7c, 0x1b, 0xb8, 0x58, 0x8f, 0xa3, 0x51, 0xe0, 0x5f,
	0x24, 0x9e, 0x43, 0xb1, 0xf7, 0x8e, 0xf8, 0xe8, 0x53, 0x58, 0xf7, 0x38, 0x32, 0x0c, 0x3c, 0x69,
	0xaa, 0x2a, 0x18, 0x1d, 0x0f, 0x7d, 0x0e, 0x35, 0x09, 0x46, 0x4e, 0x98, 0xd9, 0x04, 0xc1, 0x32,
	0x9d, 0x10, 0x23, 0x15, 0xd6, 0x42, 0x4c, 0x88, 0xe3, 0x63, 0x75, 0x8f, 0x83, 0x19, 0xa9, 0xfd,
	0x7d, 0x15, 0xca, 0x06, 0x3b, 0x2e, 0xda, 0x84, 0xd5, 0xc0, 0x53, 0x0b, 0x1c, 0x5e, 0x0d, 0x3c,
	0xf4, 0x25, 0x94, 0xe8, 0x5d, 0x22, 0xac, 0x6d, 0x36, 0xd1, 0x51, 0x96, 0x23, 0x2e, 0x6d, 0xdf,
	0x25, 0xd8, 0xe2, 0x38, 0xda, 0x85, 0x75, 0x1a, 0x84, 0x98, 0x50, 0x27, 0x4c, 0xb8, 0xf5, 0xa2,
	0x35, 0x63, 0xa0, 0x9f, 0x41, 0x69, 0x4a, 0xdc, 0x50, 0xfd, 0x27, 0x33, 0x5c, 0x6b, 0x36, 0x72,
	0x33, 0x57, 0x32, 0x5b, 0x03, 0xea, 0x50, 0xac, 0x5f, 0x3b, 0x91, 0xcf, 0x0f, 0x7a, 0xbe, 0x62,
	0x71, 0x05, 0xf4, 0x53, 0x28, 0x79, 0xee, 0x24, 0x54, 0xff, 0x25, 0x14, 0x3f, 0xcf, 0x15, 0x97,
	0x27, 0x88, 0xe9, 0x31, 0x79, 0xf4, 0x4b, 0x28, 0x4f, 0x09, 0xf3, 0xf8, 0x6f, 0xa1, 0xf8, 0xc5,
	0x32, 0x8f, 0x3e, 0x7e, 0xe8, 0x56, 0xa8, 0xa1, 0x1f, 0x40, 0x85, 0x3a, 0xa9, 0x8f, 0xa9, 0xda,
	0xe4, 0xfa, 0xcf, 0x72, 0x7d, 0x9b, 0xb3, 0x2d, 0x09, 0x9f, 0x00, 0x54, 0x43, 0x4c, 0x1d, 0xcf,
	0xa1, 0x8e, 0xf6, 0xb7, 0x02, 0x6c, 0x1a, 0xa1, 0x13, 0x8c, 0x07, 0x38, 0xbd, 0xc5, 0xa9, 0x3e,
	0xf2, 0x59, 0xca, 0x1d, 0xd7, 0x8d, 0x27, 0x51, 0x56, 0xf9, 0x8c, 0x44, 0x3b, 0x50, 0x4d, 0x1c,
	0x42, 0xa6, 0x71, 0xea, 0xc9, 0x52, 0xe5, 0x74, 0xde, 0x2c, 0x7b, 0x73, 0xcd, 0x82, 0xa0, 0x94,
	0xc4, 0x29, 0x55, 0xf7, 0x1b, 0x85, 0xfd, 0xb2, 0xc5, 0xbf, 0x51, 0x13, 0xaa, 0xbc, 0xcb, 0xdc,
	0x78, 0xcc, 0xe3, 0xdc, 0x6c, 0x6e, 0xcd, 0x0a, 0xc4, 0x02, 0xe9, 0x4b, 0xd4, 0xca, 0xe5, 0x58,
	0x44, 0xac, 0x2e, 0xf1, 0x84, 0xaa, 0xdf, 0x70, 0x53, 0x19, 0xa9, 0x55, 0xa1, 0x32, 0x08, 0x89,
	0x3e, 0xf2, 0xb5, 0x3f, 0x16, 0xe0, 0xf9, 0xd9, 0x24, 0x26, 0x38, 0xea, 0x4f, 0xc8, 0x75, 0x4f,
	0x9e, 0x65, 0x07, 0xaa, 0x13, 0x82, 0x53, 0xde, 0x5c, 0xb2, 0xf7, 0x32, 0xfa, 0xc9, 0xd3, 0xec,
	0x40, 0x75, 0x1c, 0xfb, 0x41, 0x74, 0x91, 0x8e, 0xe5, 0x89, 0x72, 0x9a, 0xb5, 0x4d, 0x40, 0xc8,
	0x04, 0x7b, 0x0c, 0xdc, 0xe7, 0xe0, 0x8c, 0xa1, 0x7d, 0x0d, 0xb5, 0xab, 0xc1, 0x2c, 0x99, 0x59,
	0x0a, 0xe4, 0x0c, 0xf1, 0x14, 0x30, 0x9e, 0x43, 0xaf, 0xa5, 0x53, 0xfe, 0xad, 0xbd, 0x81, 0x8a,
	0xa8, 0x12, 0xaa, 0x43, 0x99, 0x85, 0x48, 0x54, 0x68, 0x14, 0xf7, 0xd7, 0x2d, 0x41, 0x30, 0x6e,
	0x1a, 0x8f, 0x31, 0x51, 0xeb, 0x82, 0xcb, 0x09, 0xad, 0x0b, 0xbb, 0x7a, 0x8a, 0x1d, 0x8a, 0xcd,
	0x98, 0x06, 0xa3, 0xc0, 0x75, 0x68, 0x10, 0x47, 0xac, 0x37, 0x22, 0x3c, 0xb6, 0xf0, 0x77, 0xe8,
	0x47, 0xb0, 0x1a, 0xb9, 0xdc, 0x77, 0xad, 0xb9, 0x9b, 0xa7, 0x79, 0x99, 0xf0, 0x6a, 0xe4, 0x6a,
	0xff, 0x28, 0xc2, 0x8b, 0x25, 0xd8, 0x83, 0xf9, 0x42, 0x50, 0x9a, 0x4b, 0x28, 0xff, 0x46, 0x07,
	0x50, 0xc1, 0x6c, 0xa8, 0x88, 0xfa, 0xac, 0x51, 0x7c, 0x64, 0xea, 0xa4, 0x04, 0x7a, 0xb3, 0x30,
	0x9f, 0x8d, 0xa7, 0xe2, 0x9a, 0x9b, 0xd6, 0x06, 0xbb, 0x2a, 0x88, 0x9b, 0x06, 0x09, 0xc3, 0xd5,
	0x57, 0xdc, 0xf9, 0x3c, 0x6b, 0x6e, 0x00, 0xf6, 0x9e, 0x1c, 0x00, 0xa4, 0x83, 0x82, 0x59, 0xab,
	0x0d, 0x09, 0xaf, 0xd3, 0xd0, 0x1d, 0xf9, 0xbc, 0x90, 0xb5, 0xe6, 0xf6, 0x62, 0x2f, 0xe6, 0x75,
	0x3c, 0x5f, 0xb1, 0x36, 0xf1, 0xe2, 0x98, 0x1c, 0xc0, 0x1a, 0x09, 0x09, 0xd7, 0xbd, 0x3f, 0x6f,
	0xa2, 0x25, 0xcf, 0x57, 0xac, 0x0a, 0xe1, 0x5f, 0xe8, 0x6b, 0x58, 0xf3, 0x93, 0x98, 0xcb, 0x7e,
	0xc3, 0x65, 0x77, 0x72, 0xd9, 0x07, 0x3d, 0xcb, 0xd4, 0xfc, 0x24, 0x66, 0x6a, 0x3f, 0x87, 0x8d,
	0x29, 0x99, 0x0f, 0xf2, 0x94, 0x2b, 0xd7, 0x67, 0x17, 0xc3, 0x60, 0x3e, 0xc2, 0xda, 0x94, 0xe4,
	0xe4, 0x49, 0x19, 0x8a, 0xee, 0xc8, 0xd7, 0x7e, 0xf3, 0x64, 0x87, 0x10, 0xf4, 0x1a, 0x8a, 0x29,
	0xa6, 0xb2, 0x45, 0x9e, 0x1d, 0xc9, 0x7d, 0x71, 0xe2, 0x10, 0x6c, 0x61, 0x6a, 0x31, 0x4c, 0x96,
	0xbf, 0xce, 0x07, 0x6f, 0x35, 0xf0, 0xb4, 0x5f, 0xc0, 0xab, 0x33, 0x4c, 0x1f, 0xe9, 0xb8, 0x06,
	0xeb, 0x6d, 0x1f, 0x4b, 0x83, 0x9f, 0x64, 0x06, 0xfb, 0x8e, 0x8f, 0x2d, 0x8e, 0x68, 0x7f, 0x2d,
	0x3c, 0xae, 0xff, 0x3f, 0xc5, 0x93, 0xb9, 0xa8, 0x3f, 0xe6, 0x82, 0x0d, 0x0b, 0x8d, 0xa9, 0x23,
	0x46, 0xb7, 0x6c, 0x09, 0x02, 0x1d, 0x41, 0x31, 0x72, 0x89, 0xba, 0xdf, 0x28, 0x7e, 0x74, 0x1a,
	0x98, 0xa0, 0xf6, 0x0e, 0x5e, 0xea, 0x4e, 0xe4, 0x05, 0xec, 0xa2, 0x16, 0x39, 0xf4, 0x2e, 0x9d,
	0xf1, 0x04, 0xb3, 0x1d, 0x28, 0x36, 0x94, 0x9c, 0x00, 0x49, 0xb1, 0x8b, 0xc1, 0xcd, 0x14, 0xe4,
	0x70, 0xcf, 0x18, 0xda, 0x00, 0x9e, 0xcf, 0x5f, 0xdd, 0x4f, 0x9b, 0xfa, 0x12, 0xca, 0x84, 0x66,
	0x66, 0x36, 0x9b, 0xca, 0x11, 0x5b, 0xdb, 0x62, 0x7f, 0x70, 0x23, 0x96, 0x80, 0x35, 0x1b, 0x90,
	0x1d, 0xb8, 0x37, 0x98, 0xde, 0x0f, 0x90, 0x72, 0x6e, 0x66, 0x55, 0x50, 0x2c, 0x2f, 0xf1, 0x34,
	0xc2, 0xa9, 0x0c, 0x4e, 0x10, 0x48, 0x81, 0xa2, 0xeb, 0x24, 0xf2, 0x9a, 0x63, 0x9f, 0xda, 0x77,
	0xb0, 0x2d, 0xac, 0x1a, 0xbf, 0x4b, 0x82, 0x54, 0xb4, 0xce, 0xdd, 0xff, 0x63, 0x7a, 0x0b, 0x2a,
	0x98, 0x9b, 0x90, 0xeb, 0x55, 0x52, 0x99, 0xcb, 0xfd, 0x99, 0xcb, 0xbf, 0x14, 0x32, 0x9f, 0x4b,
	0x93, 0xb4, 0xd4, 0xe7, 0x11, 0x54, 0x3e, 0xe0, 0x51, 0x9c, 0x66, 0x59, 0xda, 0xe2, 0x59, 0xea,
	0xc7, 0xe3, 0xc0, 0xbd, 0xcb, 0x6d, 0xf9, 0xd8, 0x92, 0x52, 0xe8, 0xc7, 0xb0, 0xe6, 0x4e, 0xd2,
	0x14, 0x47, 0xe2, 0x82, 0x78, 0x5c, 0x21, 0x13, 0x5b, 0x12, 0xe7, 0x9f, 0x0b, 0x80, 0x16, 0x1e,
	0x00, 0x22, 0xc4, 0x65, 0x57, 0xe2, 0xfc, 0xee, 0xa9, 0xdf, 0xdb, 0x3d, 0x87, 0x59, 0x7d, 0x45,
	0x20, 0xdb, 0x47, 0xf9, 0x13, 0x6c, 0xc1, 0xb8, 0x2c, 0x33, 0x5b, 0x80, 0x84, 0x3a, 0x29, 0x6d,
	0x89, 0x5d, 0x5a, 0xb4, 0x32, 0x92, 0xe5, 0x1d, 0x47, 0x5e, 0x4b, 0xec, 0xfc, 0xa2, 0x25, 0x08,
	0xed, 0x5b, 0xd8, 0x7e, 0xe4, 0x95, 0x22, 0xa7, 0x19, 0xf2, 0xcb, 0xfc, 0x10, 0x8a, 0x53, 0x72,
	0xcb, 0xd7, 0x4a, 0xad, 0xf9, 0xe9, 0xf2, 0x47, 0x0e, 0x3f, 0xa3, 0xc5, 0xe4, 0xb4, 0xff, 0x14,
	0xe0, 0x65, 0x86, 0xf5, 0x63, 0xef, 0x23, 0x29, 0x38, 0x5c, 0x6c, 0xe3, 0x8f, 0x1d, 0xf3, 0x2b,
	0x28, 0x93, 0x84, 0xdc, 0x12, 0x75, 0xef, 0x5e, 0x34, 0xbc, 0x2c, 0x0b, 0xee, 0x2c, 0x21, 0xf9,
	0x7d, 0x33, 0xc3, 0xdf, 0x7c, 0xec, 0x36, 0xb0, 0x83, 0x10, 0xf3, 0xbb, 0x98, 0xbd, 0xf9, 0x32,
	0xc6, 0xfc, 0x6b, 0xf3, 0x74, 0xf1, 0xb5, 0xf9, 0xa7, 0x02, 0xa0, 0x87, 0x51, 0xa0, 0x3d, 0x00,
	0xc2, 0xb8, 0xc4, 0x9c, 0x1d, 0x7d, 0x8e, 0xf3, 0x7d, 0x13, 0x90, 0xe5, 0x70, 0x6f, 0x2e, 0x87,
	0x0a, 0x14, 0xc7, 0xb1, 0x9f, 0xf5, 0xe0, 0x38, 0xf6, 0x35, 0x0f, 0x76, 0x9f, 0x7a, 0x11, 0x3e,
	0x28, 0xf1, 0x1b, 0x28, 0x4f, 0x79, 0x5a, 0x45, 0x91, 0xf7, 0x1e, 0x14, 0xf9, 0x5e, 0x66, 0xb9,
	0xf0, 0xc1, 0x1f, 0x8a, 0xb0, 0x9e, 0xef, 0x6e, 0xb4, 0x05, 0xe8, 0xc2, 0x7c, 0x6b, 0xf6, 0xae,
	0xcc, 0xa1, 0x71, 0x69, 0x98, 0xf6, 0xd0, 0x7e, 0xdf, 0x37, 0x94, 0x15, 0xf4, 0x0a, 0x5e, 0xb6,
	0x8d, 0xcb, 0x8e, 0x6e, 0x0c, 0xf5, 0x9e, 0x79, 0xda, 0x39, 0x1b, 0x5e, 0xf4, 0xdb, 0x2d, 0xdb,
	0x68, 0x2b, 0x05, 0xf4, 0x19, 0xbc, 0x92, 0x90, 0xd5, 0xba, 0xca, 0xe0, 0xc1, 0x7b, 0x53, 0xef,
	0x98, 0x67, 0xca, 0x2a, 0xda, 0x05, 0x75, 0x39, 0x6c, 0xb4, 0x95, 0x22, 0x7a, 0x0d, 0x9f, 0x49,
	0xb4, 0x77, 0xf2, 0x6b, 0x43, 0xb7, 0x33, 0x81, 0x96, 0xd9, 0xea, 0xbe, 0x1f, 0x18, 0x6d, 0xa5,
	0x84, 0x54, 0xa8, 0x4b, 0x91, 0x81, 0xdd, 0xb2, 0x8d, 0xa1, 0x7e, 0xde, 0x32, 0xcf, 0x8c, 0xb6,
	0x52, 0x9e, 0x33, 0xad, 0xb7, 0xcc, 0x76, 0xa7, 0xcd, 0x51, 0xcb, 0xe0, 0x71, 0x55, 0xd0, 0x73,
	0xd8, 0x90, 0x68, 0xdb, 0xe8, 0x1a, 0xb6, 0xa1, 0xac, 0x21, 0x04, 0x9b, 0x76, 0x47, 0x7f, 0x6b,
	0xd8, 0xb9, 0x58, 0x95, 0x99, 0x97, 0xbc, 0x45, 0xf3, 0xeb, 0x68, 0x1b, 0x5e, 0x48, 0xe4, 0xaa,
	0xd3, 0xed, 0x0e, 0x8d, 0x6f, 0xfb, 0x1d, 0xcb, 0x68, 0x2b, 0xc0, 0x2c, 0xb7, 0x74, 0xbb, 0x73,
	0xd9, 0xb1, 0xdf, 0x0f, 0x4f, 0x5b, 0x9d, 0xae, 0x52, 0x43, 0x3b, 0xb0, 0x75, 0xd5, 0xb3, 0xde,
	0x9e, 0x76, 0x7b, 0x57, 0xf7, 0xec, 0x7c, 0x82, 0x1a, 0xb0, 0x3b, 0x8f, 0x9d, 0xdd, 0x3f, 0xc8,
	0xc6, 0xc1, 0xef, 0x61, 0xfb, 0x91, 0x47, 0x11, 0xfa, 0x02, 0x5e, 0x67, 0x05, 0x31, 0x7b, 0x76,
	0xe7, 0xb4, 0xa3, 0xb7, 0xec, 0x4e, 0xcf, 0xe4, 0xca, 0xa6, 0xd1, 0xcd, 0xea, 0xb3, 0x0e, 0x65,
	0xe3, 0x1d, 0x0b, 0x05, 0xd8, 0x67, 0xff, 0xbc, 0x67, 0x1a, 0x4a, 0x1d, 0x6d, 0xc0, 0xfa, 0x95,
	0x71, 0x32, 0xe8, 0xb1, 0x43, 0x28, 0x7b, 0xa8, 0x0e, 0xca, 0xd9, 0x45, 0x6f, 0x60, 0x98, 0xc3,
	0xfe, 0xc5, 0xe0, 0x7c, 0xd8, 0xbb, 0x34, 0x2c, 0x65, 0xff, 0xe0, 0x57, 0xb0, 0xb1, 0xf0, 0x20,
	0x67, 0x62, 0x99, 0xcb, 0xbe, 0xd5, 0xb3, 0x7b, 0x7a, 0xaf, 0xab, 0xac, 0xa0, 0x2a, 0x94, 0x06,
	0xef, 0xec, 0xbe, 0x02, 0xe8, 0x19, 0xd4, 0x06, 0x86, 0x7e, 0x61, 0x19, 0x43, 0xce, 0xa8, 0x9f,
	0x9c, 0xc1, 0x4e, 0x84, 0xe9, 0x11, 0xb9, 0xb9, 0x73, 0xc7, 0xf1, 0xc4, 0x13, 0x7f, 0x2f, 0xb3,
	0xee, 0xfb, 0xed, 0x0f, 0xfd, 0x80, 0x5e, 0x4f, 0x3e, 0xb0, 0xfd, 0x7d, 0x4c, 0x6e, 0xee, 0x0e,
	0xb9, 0xcc, 0x21, 0xc5, 0xee, 0x31, 0x97, 0x3b, 0xbe, 0xfd, 0x2a, 0xfb, 0x77, 0xfb, 0xa1, 0xc2,
	0x39, 0x3f, 0xf9, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x3c, 0xac, 0x21, 0xf7, 0x0e, 0x00,
	0x00,
}
