// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eventti/eventti.proto

/*
Package eventti is a generated protocol buffer package.

It is generated from these files:
	eventti/eventti.proto

It has these top-level messages:
	From
	DeviceConfigUpdatedMsg
	Event
	EmailServerCfg
	SmsCfg
	Target
	CreateNotificationChannelReq
	NotificationChannel
	CreateNotificationChannelRes
	GetNotificationChannelReq
	GetNotificationChannelRes
*/
package eventti

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"
import common "github.com/sky-cloud-tec/proto/v1/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventType int32

const (
	EventType_UNKNOWN_EVENT_TYPE            EventType = 0
	EventType_DEVICE_CONFIG_UPDATED         EventType = 1
	EventType_DEVICE_RAW_CONFIG_SYNCING     EventType = 2
	EventType_DEVICE_RAW_CONFIG_SYNCED      EventType = 3
	EventType_DEVICE_OBJECT_CONFIG_ANALYSED EventType = 4
)

var EventType_name = map[int32]string{
	0: "UNKNOWN_EVENT_TYPE",
	1: "DEVICE_CONFIG_UPDATED",
	2: "DEVICE_RAW_CONFIG_SYNCING",
	3: "DEVICE_RAW_CONFIG_SYNCED",
	4: "DEVICE_OBJECT_CONFIG_ANALYSED",
}
var EventType_value = map[string]int32{
	"UNKNOWN_EVENT_TYPE":            0,
	"DEVICE_CONFIG_UPDATED":         1,
	"DEVICE_RAW_CONFIG_SYNCING":     2,
	"DEVICE_RAW_CONFIG_SYNCED":      3,
	"DEVICE_OBJECT_CONFIG_ANALYSED": 4,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}
func (EventType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NotificationChannelType int32

const (
	NotificationChannelType_UNKNOWN_NOTIFICATION_CHANNEL_TYPE NotificationChannelType = 0
	NotificationChannelType_EMAIL                             NotificationChannelType = 10
	NotificationChannelType_PHONE                             NotificationChannelType = 20
	NotificationChannelType_WEBSOCKET                         NotificationChannelType = 30
)

var NotificationChannelType_name = map[int32]string{
	0:  "UNKNOWN_NOTIFICATION_CHANNEL_TYPE",
	10: "EMAIL",
	20: "PHONE",
	30: "WEBSOCKET",
}
var NotificationChannelType_value = map[string]int32{
	"UNKNOWN_NOTIFICATION_CHANNEL_TYPE": 0,
	"EMAIL":     10,
	"PHONE":     20,
	"WEBSOCKET": 30,
}

func (x NotificationChannelType) String() string {
	return proto.EnumName(NotificationChannelType_name, int32(x))
}
func (NotificationChannelType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type EmailProtocol int32

const (
	EmailProtocol_UNKNOWN_PROTOCOL EmailProtocol = 0
	EmailProtocol_SMTP             EmailProtocol = 10
	EmailProtocol_SECURE_SMTP      EmailProtocol = 20
)

var EmailProtocol_name = map[int32]string{
	0:  "UNKNOWN_PROTOCOL",
	10: "SMTP",
	20: "SECURE_SMTP",
}
var EmailProtocol_value = map[string]int32{
	"UNKNOWN_PROTOCOL": 0,
	"SMTP":             10,
	"SECURE_SMTP":      20,
}

func (x EmailProtocol) String() string {
	return proto.EnumName(EmailProtocol_name, int32(x))
}
func (EmailProtocol) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type From struct {
	Host   string `protobuf:"bytes,10,opt,name=host" json:"host,omitempty"`
	Module string `protobuf:"bytes,20,opt,name=module" json:"module,omitempty"`
}

func (m *From) Reset()                    { *m = From{} }
func (m *From) String() string            { return proto.CompactTextString(m) }
func (*From) ProtoMessage()               {}
func (*From) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *From) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *From) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

type DeviceConfigUpdatedMsg struct {
	DeviceId   string `protobuf:"bytes,10,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	DeviceName string `protobuf:"bytes,20,opt,name=device_name,json=deviceName" json:"device_name,omitempty"`
	Message    string `protobuf:"bytes,30,opt,name=message" json:"message,omitempty"`
}

func (m *DeviceConfigUpdatedMsg) Reset()                    { *m = DeviceConfigUpdatedMsg{} }
func (m *DeviceConfigUpdatedMsg) String() string            { return proto.CompactTextString(m) }
func (*DeviceConfigUpdatedMsg) ProtoMessage()               {}
func (*DeviceConfigUpdatedMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeviceConfigUpdatedMsg) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeviceConfigUpdatedMsg) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *DeviceConfigUpdatedMsg) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Event struct {
	Id        string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type      EventType            `protobuf:"varint,20,opt,name=type,enum=eventti.EventType" json:"type,omitempty"`
	Timestamp int64                `protobuf:"varint,30,opt,name=timestamp" json:"timestamp,omitempty"`
	Metadata  *google_protobuf.Any `protobuf:"bytes,40,opt,name=metadata" json:"metadata,omitempty"`
	Target    *Target              `protobuf:"bytes,50,opt,name=target" json:"target,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_UNKNOWN_EVENT_TYPE
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetMetadata() *google_protobuf.Any {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Event) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

type EmailServerCfg struct {
	Account  string        `protobuf:"bytes,10,opt,name=account" json:"account,omitempty"`
	Password string        `protobuf:"bytes,20,opt,name=password" json:"password,omitempty"`
	Host     string        `protobuf:"bytes,30,opt,name=host" json:"host,omitempty"`
	Port     int32         `protobuf:"varint,40,opt,name=port" json:"port,omitempty"`
	Protocol EmailProtocol `protobuf:"varint,50,opt,name=protocol,enum=eventti.EmailProtocol" json:"protocol,omitempty"`
	Timeout  int32         `protobuf:"varint,60,opt,name=timeout" json:"timeout,omitempty"`
}

func (m *EmailServerCfg) Reset()                    { *m = EmailServerCfg{} }
func (m *EmailServerCfg) String() string            { return proto.CompactTextString(m) }
func (*EmailServerCfg) ProtoMessage()               {}
func (*EmailServerCfg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EmailServerCfg) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *EmailServerCfg) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *EmailServerCfg) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *EmailServerCfg) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *EmailServerCfg) GetProtocol() EmailProtocol {
	if m != nil {
		return m.Protocol
	}
	return EmailProtocol_UNKNOWN_PROTOCOL
}

func (m *EmailServerCfg) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type SmsCfg struct {
}

func (m *SmsCfg) Reset()                    { *m = SmsCfg{} }
func (m *SmsCfg) String() string            { return proto.CompactTextString(m) }
func (*SmsCfg) ProtoMessage()               {}
func (*SmsCfg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Target struct {
	Users []string `protobuf:"bytes,10,rep,name=users" json:"users,omitempty"`
	Roles []string `protobuf:"bytes,20,rep,name=roles" json:"roles,omitempty"`
}

func (m *Target) Reset()                    { *m = Target{} }
func (m *Target) String() string            { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()               {}
func (*Target) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Target) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Target) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type CreateNotificationChannelReq struct {
	Nc *NotificationChannel `protobuf:"bytes,10,opt,name=nc" json:"nc,omitempty"`
}

func (m *CreateNotificationChannelReq) Reset()                    { *m = CreateNotificationChannelReq{} }
func (m *CreateNotificationChannelReq) String() string            { return proto.CompactTextString(m) }
func (*CreateNotificationChannelReq) ProtoMessage()               {}
func (*CreateNotificationChannelReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateNotificationChannelReq) GetNc() *NotificationChannel {
	if m != nil {
		return m.Nc
	}
	return nil
}

type NotificationChannel struct {
	Id     string                  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name   string                  `protobuf:"bytes,10,opt,name=name" json:"name,omitempty"`
	Etypes []EventType             `protobuf:"varint,15,rep,packed,name=etypes,enum=eventti.EventType" json:"etypes,omitempty"`
	Type   NotificationChannelType `protobuf:"varint,20,opt,name=type,enum=eventti.NotificationChannelType" json:"type,omitempty"`
	Target *Target                 `protobuf:"bytes,30,opt,name=target" json:"target,omitempty"`
	// Types that are valid to be assigned to Cfg:
	//	*NotificationChannel_EmailServerCfg
	//	*NotificationChannel_SmsCfg
	Cfg isNotificationChannel_Cfg `protobuf_oneof:"cfg"`
}

func (m *NotificationChannel) Reset()                    { *m = NotificationChannel{} }
func (m *NotificationChannel) String() string            { return proto.CompactTextString(m) }
func (*NotificationChannel) ProtoMessage()               {}
func (*NotificationChannel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type isNotificationChannel_Cfg interface {
	isNotificationChannel_Cfg()
}

type NotificationChannel_EmailServerCfg struct {
	EmailServerCfg *EmailServerCfg `protobuf:"bytes,40,opt,name=email_server_cfg,json=emailServerCfg,oneof"`
}
type NotificationChannel_SmsCfg struct {
	SmsCfg *SmsCfg `protobuf:"bytes,50,opt,name=sms_cfg,json=smsCfg,oneof"`
}

func (*NotificationChannel_EmailServerCfg) isNotificationChannel_Cfg() {}
func (*NotificationChannel_SmsCfg) isNotificationChannel_Cfg()         {}

func (m *NotificationChannel) GetCfg() isNotificationChannel_Cfg {
	if m != nil {
		return m.Cfg
	}
	return nil
}

func (m *NotificationChannel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NotificationChannel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NotificationChannel) GetEtypes() []EventType {
	if m != nil {
		return m.Etypes
	}
	return nil
}

func (m *NotificationChannel) GetType() NotificationChannelType {
	if m != nil {
		return m.Type
	}
	return NotificationChannelType_UNKNOWN_NOTIFICATION_CHANNEL_TYPE
}

func (m *NotificationChannel) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *NotificationChannel) GetEmailServerCfg() *EmailServerCfg {
	if x, ok := m.GetCfg().(*NotificationChannel_EmailServerCfg); ok {
		return x.EmailServerCfg
	}
	return nil
}

func (m *NotificationChannel) GetSmsCfg() *SmsCfg {
	if x, ok := m.GetCfg().(*NotificationChannel_SmsCfg); ok {
		return x.SmsCfg
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*NotificationChannel) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _NotificationChannel_OneofMarshaler, _NotificationChannel_OneofUnmarshaler, _NotificationChannel_OneofSizer, []interface{}{
		(*NotificationChannel_EmailServerCfg)(nil),
		(*NotificationChannel_SmsCfg)(nil),
	}
}

func _NotificationChannel_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*NotificationChannel)
	// cfg
	switch x := m.Cfg.(type) {
	case *NotificationChannel_EmailServerCfg:
		b.EncodeVarint(40<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EmailServerCfg); err != nil {
			return err
		}
	case *NotificationChannel_SmsCfg:
		b.EncodeVarint(50<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SmsCfg); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("NotificationChannel.Cfg has unexpected type %T", x)
	}
	return nil
}

func _NotificationChannel_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*NotificationChannel)
	switch tag {
	case 40: // cfg.email_server_cfg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EmailServerCfg)
		err := b.DecodeMessage(msg)
		m.Cfg = &NotificationChannel_EmailServerCfg{msg}
		return true, err
	case 50: // cfg.sms_cfg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SmsCfg)
		err := b.DecodeMessage(msg)
		m.Cfg = &NotificationChannel_SmsCfg{msg}
		return true, err
	default:
		return false, nil
	}
}

func _NotificationChannel_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*NotificationChannel)
	// cfg
	switch x := m.Cfg.(type) {
	case *NotificationChannel_EmailServerCfg:
		s := proto.Size(x.EmailServerCfg)
		n += proto.SizeVarint(40<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *NotificationChannel_SmsCfg:
		s := proto.Size(x.SmsCfg)
		n += proto.SizeVarint(50<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CreateNotificationChannelRes struct {
	Ret *common.BaseRet `protobuf:"bytes,10,opt,name=ret" json:"ret,omitempty"`
	Id  int32           `protobuf:"varint,20,opt,name=id" json:"id,omitempty"`
}

func (m *CreateNotificationChannelRes) Reset()                    { *m = CreateNotificationChannelRes{} }
func (m *CreateNotificationChannelRes) String() string            { return proto.CompactTextString(m) }
func (*CreateNotificationChannelRes) ProtoMessage()               {}
func (*CreateNotificationChannelRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CreateNotificationChannelRes) GetRet() *common.BaseRet {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *CreateNotificationChannelRes) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetNotificationChannelReq struct {
	Page *common.Page `protobuf:"bytes,10,opt,name=page" json:"page,omitempty"`
}

func (m *GetNotificationChannelReq) Reset()                    { *m = GetNotificationChannelReq{} }
func (m *GetNotificationChannelReq) String() string            { return proto.CompactTextString(m) }
func (*GetNotificationChannelReq) ProtoMessage()               {}
func (*GetNotificationChannelReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetNotificationChannelReq) GetPage() *common.Page {
	if m != nil {
		return m.Page
	}
	return nil
}

type GetNotificationChannelRes struct {
	Ret   *common.BaseRet        `protobuf:"bytes,10,opt,name=ret" json:"ret,omitempty"`
	Page  *common.Page           `protobuf:"bytes,20,opt,name=page" json:"page,omitempty"`
	Total int32                  `protobuf:"varint,30,opt,name=total" json:"total,omitempty"`
	Ncs   []*NotificationChannel `protobuf:"bytes,40,rep,name=ncs" json:"ncs,omitempty"`
}

func (m *GetNotificationChannelRes) Reset()                    { *m = GetNotificationChannelRes{} }
func (m *GetNotificationChannelRes) String() string            { return proto.CompactTextString(m) }
func (*GetNotificationChannelRes) ProtoMessage()               {}
func (*GetNotificationChannelRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetNotificationChannelRes) GetRet() *common.BaseRet {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *GetNotificationChannelRes) GetPage() *common.Page {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *GetNotificationChannelRes) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetNotificationChannelRes) GetNcs() []*NotificationChannel {
	if m != nil {
		return m.Ncs
	}
	return nil
}

func init() {
	proto.RegisterType((*From)(nil), "eventti.From")
	proto.RegisterType((*DeviceConfigUpdatedMsg)(nil), "eventti.DeviceConfigUpdatedMsg")
	proto.RegisterType((*Event)(nil), "eventti.Event")
	proto.RegisterType((*EmailServerCfg)(nil), "eventti.EmailServerCfg")
	proto.RegisterType((*SmsCfg)(nil), "eventti.SmsCfg")
	proto.RegisterType((*Target)(nil), "eventti.Target")
	proto.RegisterType((*CreateNotificationChannelReq)(nil), "eventti.CreateNotificationChannelReq")
	proto.RegisterType((*NotificationChannel)(nil), "eventti.NotificationChannel")
	proto.RegisterType((*CreateNotificationChannelRes)(nil), "eventti.CreateNotificationChannelRes")
	proto.RegisterType((*GetNotificationChannelReq)(nil), "eventti.GetNotificationChannelReq")
	proto.RegisterType((*GetNotificationChannelRes)(nil), "eventti.GetNotificationChannelRes")
	proto.RegisterEnum("eventti.EventType", EventType_name, EventType_value)
	proto.RegisterEnum("eventti.NotificationChannelType", NotificationChannelType_name, NotificationChannelType_value)
	proto.RegisterEnum("eventti.EmailProtocol", EmailProtocol_name, EmailProtocol_value)
}

func init() { proto.RegisterFile("eventti/eventti.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 913 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x5d, 0x73, 0xdb, 0x44,
	0x14, 0x8d, 0x3f, 0x63, 0xdf, 0xd0, 0x44, 0xb3, 0x75, 0x53, 0x25, 0xa4, 0xc1, 0xd1, 0x0c, 0x60,
	0x3c, 0xd4, 0x06, 0xd3, 0x47, 0x98, 0xc1, 0x96, 0x95, 0xc4, 0xd4, 0x91, 0xcc, 0x5a, 0x69, 0x26,
	0xbc, 0x78, 0x36, 0xd2, 0x5a, 0xd1, 0xd4, 0xd2, 0x0a, 0xed, 0x3a, 0x8c, 0xff, 0x0c, 0x8f, 0xfc,
	0x06, 0x1e, 0xfa, 0xe3, 0x18, 0xad, 0x24, 0xa7, 0x81, 0x38, 0xf4, 0x49, 0x7b, 0xcf, 0xb9, 0xba,
	0x7b, 0xf7, 0x9e, 0xa3, 0x15, 0xbc, 0xa0, 0x77, 0x34, 0x14, 0xc2, 0xef, 0x66, 0xcf, 0x4e, 0x14,
	0x33, 0xc1, 0xd0, 0x76, 0x16, 0x1e, 0x1e, 0x78, 0x8c, 0x79, 0x0b, 0xda, 0x95, 0xf0, 0xcd, 0x72,
	0xde, 0x25, 0xe1, 0x2a, 0xcd, 0x39, 0x7c, 0xee, 0xb0, 0x20, 0x60, 0x61, 0x37, 0x7d, 0xa4, 0xa0,
	0xd6, 0x83, 0xf2, 0x69, 0xcc, 0x02, 0x84, 0xa0, 0x7c, 0xcb, 0xb8, 0x50, 0xa1, 0x59, 0x68, 0xd5,
	0xb1, 0x5c, 0xa3, 0x7d, 0xa8, 0x06, 0xcc, 0x5d, 0x2e, 0xa8, 0xda, 0x90, 0x68, 0x16, 0x69, 0x11,
	0xec, 0x0f, 0xe9, 0x9d, 0xef, 0x50, 0x9d, 0x85, 0x73, 0xdf, 0xbb, 0x8c, 0x5c, 0x22, 0xa8, 0x7b,
	0xc1, 0x3d, 0xf4, 0x39, 0xd4, 0x5d, 0xc9, 0xcc, 0x7c, 0x37, 0x2b, 0x55, 0x4b, 0x81, 0x91, 0x8b,
	0xbe, 0x80, 0x9d, 0x8c, 0x0c, 0x49, 0x90, 0xd7, 0x84, 0x14, 0x32, 0x49, 0x40, 0x91, 0x0a, 0xdb,
	0x01, 0xe5, 0x9c, 0x78, 0x54, 0x3d, 0x96, 0x64, 0x1e, 0x6a, 0x7f, 0x17, 0xa0, 0x62, 0x24, 0x27,
	0x44, 0xbb, 0x50, 0xf4, 0x5d, 0xb5, 0x20, 0xe9, 0xa2, 0xef, 0xa2, 0xaf, 0xa0, 0x2c, 0x56, 0x51,
	0x5a, 0x6d, 0xb7, 0x87, 0x3a, 0xf9, 0x58, 0x64, 0xb6, 0xbd, 0x8a, 0x28, 0x96, 0x3c, 0x3a, 0x82,
	0xba, 0xf0, 0x03, 0xca, 0x05, 0x09, 0x22, 0x59, 0xbd, 0x84, 0xef, 0x01, 0xf4, 0x1d, 0xd4, 0x02,
	0x2a, 0x88, 0x4b, 0x04, 0x51, 0x5b, 0xcd, 0x42, 0x6b, 0xa7, 0xd7, 0xe8, 0xa4, 0x83, 0xec, 0xe4,
	0x83, 0xec, 0xf4, 0xc3, 0x15, 0x5e, 0x67, 0xa1, 0xaf, 0xa1, 0x2a, 0x48, 0xec, 0x51, 0xa1, 0xf6,
	0x64, 0xfe, 0xde, 0x7a, 0x67, 0x5b, 0xc2, 0x38, 0xa3, 0xb5, 0x0f, 0x05, 0xd8, 0x35, 0x02, 0xe2,
	0x2f, 0xa6, 0x34, 0xbe, 0xa3, 0xb1, 0x3e, 0xf7, 0x92, 0x73, 0x12, 0xc7, 0x61, 0xcb, 0x30, 0x1f,
	0x77, 0x1e, 0xa2, 0x43, 0xa8, 0x45, 0x84, 0xf3, 0x3f, 0x58, 0xec, 0x66, 0xf3, 0x59, 0xc7, 0x6b,
	0x85, 0x8e, 0x3f, 0x52, 0x08, 0x41, 0x39, 0x62, 0xb1, 0x90, 0x3d, 0x57, 0xb0, 0x5c, 0xa3, 0x1e,
	0xd4, 0x64, 0xcf, 0x0e, 0x5b, 0xc8, 0xde, 0x76, 0x7b, 0xfb, 0xf7, 0x53, 0x49, 0x1a, 0x99, 0x64,
	0x2c, 0x5e, 0xe7, 0x25, 0x1d, 0x25, 0xc3, 0x60, 0x4b, 0xa1, 0xfe, 0x28, 0x4b, 0xe5, 0xa1, 0x56,
	0x83, 0xea, 0x34, 0xe0, 0xfa, 0xdc, 0xd3, 0xde, 0x40, 0x35, 0x3d, 0x1a, 0x6a, 0x40, 0x65, 0xc9,
	0x69, 0xcc, 0x55, 0x68, 0x96, 0x5a, 0x75, 0x9c, 0x06, 0x09, 0x1a, 0xb3, 0x05, 0xe5, 0x6a, 0x23,
	0x45, 0x65, 0xa0, 0x8d, 0xe1, 0x48, 0x8f, 0x29, 0x11, 0xd4, 0x64, 0xc2, 0x9f, 0xfb, 0x0e, 0x11,
	0x3e, 0x0b, 0xf5, 0x5b, 0x12, 0x86, 0x74, 0x81, 0xe9, 0xef, 0xe8, 0x5b, 0x28, 0x86, 0x8e, 0x1c,
	0xc3, 0x4e, 0xef, 0x68, 0xdd, 0xe7, 0x63, 0xc9, 0xc5, 0xd0, 0xd1, 0x3e, 0x14, 0xe1, 0xf9, 0x23,
	0xdc, 0x7f, 0x5c, 0x81, 0xa0, 0x2c, 0x3d, 0x96, 0xb9, 0x39, 0x59, 0xa3, 0x36, 0x54, 0x69, 0x62,
	0x05, 0xae, 0xee, 0x35, 0x4b, 0x1b, 0xbc, 0x92, 0x65, 0xa0, 0x37, 0x0f, 0x5c, 0xd5, 0x7c, 0xaa,
	0xaf, 0x8f, 0x3c, 0x76, 0xef, 0x89, 0xe3, 0x27, 0x3d, 0x81, 0x74, 0x50, 0x68, 0xa2, 0xc4, 0x8c,
	0x4b, 0x4f, 0xcc, 0x9c, 0xb9, 0x97, 0xd9, 0xee, 0xe5, 0x43, 0xa9, 0xd6, 0x9e, 0x39, 0xdf, 0xc2,
	0xbb, 0xf4, 0xa1, 0x8b, 0xda, 0xb0, 0xcd, 0x03, 0x2e, 0xdf, 0xfd, 0xb7, 0x05, 0x53, 0xc5, 0xce,
	0xb7, 0x70, 0x95, 0xcb, 0xd5, 0xa0, 0x02, 0x25, 0x67, 0xee, 0x69, 0xbf, 0x3e, 0x29, 0x06, 0x47,
	0x27, 0x50, 0x8a, 0xa9, 0xc8, 0xd4, 0xd8, 0xeb, 0x64, 0x17, 0xc5, 0x80, 0x70, 0x8a, 0xa9, 0xc0,
	0x09, 0x97, 0x4d, 0xba, 0x21, 0x4d, 0x52, 0xf4, 0x5d, 0xed, 0x27, 0x38, 0x38, 0xa3, 0x62, 0x83,
	0xb8, 0x4d, 0x28, 0x47, 0xc9, 0xd7, 0x9c, 0x16, 0xfc, 0x2c, 0x2f, 0x38, 0x21, 0x1e, 0xc5, 0x92,
	0xd1, 0xfe, 0x2a, 0x6c, 0x7e, 0xff, 0x93, 0xfa, 0xc9, 0xb7, 0x68, 0x6c, 0xda, 0x22, 0xf1, 0xa5,
	0x60, 0x82, 0x2c, 0xa4, 0x28, 0x15, 0x9c, 0x06, 0xa8, 0x03, 0xa5, 0xd0, 0xe1, 0x6a, 0xab, 0x59,
	0xfa, 0x5f, 0xe3, 0x25, 0x89, 0xed, 0x3f, 0x0b, 0x50, 0x5f, 0xfb, 0x04, 0xed, 0x03, 0xba, 0x34,
	0xdf, 0x9a, 0xd6, 0x95, 0x39, 0x33, 0xde, 0x19, 0xa6, 0x3d, 0xb3, 0xaf, 0x27, 0x86, 0xb2, 0x85,
	0x0e, 0xe0, 0xc5, 0xd0, 0x78, 0x37, 0xd2, 0x8d, 0x99, 0x6e, 0x99, 0xa7, 0xa3, 0xb3, 0xd9, 0xe5,
	0x64, 0xd8, 0xb7, 0x8d, 0xa1, 0x52, 0x40, 0xaf, 0xe0, 0x20, 0xa3, 0x70, 0xff, 0x2a, 0xa7, 0xa7,
	0xd7, 0xa6, 0x3e, 0x32, 0xcf, 0x94, 0x22, 0x3a, 0x02, 0xf5, 0x71, 0xda, 0x18, 0x2a, 0x25, 0x74,
	0x02, 0xaf, 0x32, 0xd6, 0x1a, 0xfc, 0x62, 0xe8, 0x76, 0x9e, 0xd0, 0x37, 0xfb, 0xe3, 0xeb, 0xa9,
	0x31, 0x54, 0xca, 0x6d, 0x0a, 0x2f, 0x37, 0xb8, 0x13, 0x7d, 0x09, 0x27, 0x79, 0xb7, 0xa6, 0x65,
	0x8f, 0x4e, 0x47, 0x7a, 0xdf, 0x1e, 0x59, 0xe6, 0x4c, 0x3f, 0xef, 0x9b, 0xa6, 0x31, 0xce, 0x9b,
	0xaf, 0x43, 0xc5, 0xb8, 0xe8, 0x8f, 0xc6, 0x0a, 0x24, 0xcb, 0xc9, 0xb9, 0x65, 0x1a, 0x4a, 0x03,
	0x3d, 0x83, 0xfa, 0x95, 0x31, 0x98, 0x5a, 0xfa, 0x5b, 0xc3, 0x56, 0x8e, 0xdb, 0x3f, 0xc3, 0xb3,
	0x07, 0x97, 0x08, 0x6a, 0x80, 0x92, 0x17, 0x9f, 0x60, 0xcb, 0xb6, 0x74, 0x6b, 0xac, 0x6c, 0xa1,
	0x1a, 0x94, 0xa7, 0x17, 0xf6, 0x44, 0x01, 0xb4, 0x07, 0x3b, 0x53, 0x43, 0xbf, 0xc4, 0xc6, 0x4c,
	0x02, 0x8d, 0xc1, 0x19, 0x1c, 0x86, 0x54, 0x74, 0xf8, 0xfb, 0x95, 0xb3, 0x60, 0x4b, 0x37, 0xbd,
	0x60, 0x73, 0x01, 0x7e, 0xfb, 0xc6, 0xf3, 0xc5, 0xed, 0xf2, 0x26, 0xd1, 0xb1, 0xcb, 0xdf, 0xaf,
	0x5e, 0xcb, 0x9c, 0xd7, 0x82, 0x3a, 0xe9, 0x1f, 0xad, 0x7b, 0xf7, 0x7d, 0xfe, 0xe7, 0xbb, 0xa9,
	0x4a, 0xe4, 0x87, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x49, 0xfc, 0x54, 0x87, 0x13, 0x07, 0x00,
	0x00,
}
